---
permalink: administration/concept_requirements_for_vcloud_vapp_backup_and_restore_operations_using_the_vmware_plug_in.html 
sidebar: sidebar 
keywords: snap, creator, backup, vcloud, vapp, vmware, director, api, vsphere, director, vcenter, vdc 
summary: Snap Creator는 VMware 플러그인을 통해 vCloud vApp 백업을 지원합니다. vApp 및 가상 머신 백업 복제본은 VMware vCloud Director API와 VMware vCenter Server에서 각각 호출되는 vCloud Director API와 vSphere API를 통해 VMware 플러그인에서 만들어집니다. 
---
= VMware 플러그인을 사용한 vCloud vApp 백업 및 복구 작업에 대한 요구 사항
:icons: font
:imagesdir: ../media/


[role="lead"]
Snap Creator는 VMware 플러그인을 통해 vCloud vApp 백업을 지원합니다. vApp 및 가상 머신 백업 복제본은 VMware vCloud Director API와 VMware vCenter Server에서 각각 호출되는 vCloud Director API와 vSphere API를 통해 VMware 플러그인에서 만들어집니다.

vApp 백업 및 복구 작업을 성공적으로 수행하려면 구성 파일에 다음 세부 정보를 제공해야 합니다.

* vCloud IP 및 자격 증명
* vCloud 조직, VDC(가상 데이터 센터) 및 vApp 이름



NOTE: vCloud에 vCenter가 두 개 이상 연결되어 있는 경우 모든 vCenter Server의 암호는 동일해야 합니다.

vCloud 백업 및 복구 작업을 수행할 때는 다음 사항을 고려해야 합니다.

* VMware와 vCloud의 백업 및 복구 프로세스는 탐색 프로세스를 제외하고 매우 유사하며, vCloud 백업 시 REST(Representational State Transfer) API를 사용하여 vCloud Director 메타데이터를 추가로 검색해야 합니다.
* 백업할 조직, VDC 및 vApp을 통해 vCloud에 대한 세부 정보를 제공해야 합니다.
* VDC가 나열되면 VDC의 모든 vApp이 백업됩니다.
* vCloud 모듈은 백업해야 하는 vApp과 연결된 가상 머신을 검색하여 백업 목록에 저장합니다.
* 백업을 위해 선택한 vApp이 조직 내에 포함되어 있거나 백업을 위해 선택된 VDC에 포함되어 있는 경우 vApp은 한 번만 백업됩니다.



NOTE: VMware 플러그인을 사용하는 VMFS(Virtual Machine File System) 복구 작업의 경우 LUN 크기와 동일한 LUN 클론을 생성할 수 있는 충분한 공간이 볼륨에 있어야 합니다.
