---
permalink: administration/concept_scf_component_plug_ins_ag.html 
sidebar: sidebar 
keywords: plug-in, applications, databases, snap, creator, plug-ins, binary, installation, integration, db2, ibm, domino, maxdb, mysql 
summary: 플러그인은 애플리케이션 또는 데이터베이스를 일관된 상태로 전환하는 데 사용됩니다. Snap Creator에는 바이너리 파일의 일부이며 추가 설치가 필요하지 않은 여러 플러그인이 포함되어 있습니다. 
---
= 애플리케이션 통합을 위한 플러그인
:icons: font
:imagesdir: ../media/


[role="lead"]
플러그인은 애플리케이션 또는 데이터베이스를 일관된 상태로 전환하는 데 사용됩니다. Snap Creator에는 바이너리 파일의 일부이며 추가 설치가 필요하지 않은 여러 플러그인이 포함되어 있습니다.

지원되는 애플리케이션 유형으로는 데이터베이스, 이메일, 하이퍼바이저 및 맞춤형 애플리케이션이 있습니다. Snap Creator에 사용할 수 있는 플러그인은 다음과 같습니다.

* 애플리케이션 및 데이터베이스 플러그인:
+
** DB2
** IBM Domino(Domino)
** 최대 DB
** MySQL
+

NOTE: MySQL 플러그인은 여러 데이터베이스의 백업 및 복원 작업을 지원하지 않습니다.

** 오라클
** SAP 고성능 분석 어플라이언스(HANA)
** Sybase Adaptive Server Enterprise(ASE)


* SnapManager 플러그인:
+
** Microsoft Exchange용 SnapManager
** Microsoft SQL Server용 SnapManager


* 하이퍼바이저 플러그인:
+
** Citrix XenServer를 참조하십시오
** Red Hat 커널 기반 가상 머신(KVM)
** VMware(개별 가상 머신 백업을 위한 vSphere 및 vApp 백업을 위한 vCloud Director)




자세한 내용은 Snap Creator를 구성하는 데 필요한 플러그인 정보를 참조하십시오. 맞춤형 플러그인("커뮤니티 플러그인"이라고도 함)은 개발자 커뮤니티에서 생성한 후 Snap Creator에서 활성화할 수 있지만 맞춤형 플러그인은 지원되지 않습니다. 이러한 플러그인은 Snap Creator에서 제공하는 인터페이스를 활용합니다.

자세한 내용은 을 참조하십시오 http://community.netapp.com/t5/Snap-Creator-Framework-Discussions/bd-p/snap-creator-framework-discussions["Snap Creator 프레임워크 토론 커뮤니티 포럼"].

* 관련 정보 *

xref:reference_information_required_to_configure_snap_creator.adoc[Snap Creator를 구성하는 데 필요한 플러그인 정보입니다]
