---
permalink: administration/concept_managing_user_access.html 
sidebar: sidebar 
keywords: snap, creator, security, features, rbac, snapcreator 
summary: 'Snap Creator는 역할 기반 액세스 제어\(RBAC\)와 같은 보안 기능을 제공하여 Snap Creator 내에서 사용자 액세스를 관리할 수 있도록 지원합니다.' 
---
= 사용자 액세스 관리
:icons: font
:imagesdir: ../media/


[role="lead"]
Snap Creator는 RBAC(역할 기반 액세스 제어)와 같은 보안 기능을 제공하여 Snap Creator 내에서 사용자 액세스를 관리할 수 있도록 지원합니다.

RBAC는 사용자, 역할, 권한, 운영 및 프로필을 포함합니다. 사용자, 역할 및 권한은 Snap Creator 사용자가 정의할 수 있습니다.



== 사용자

* 사용자는 사용자 이름 및 암호로 고유하게 식별됩니다.
* 사용자를 하나 이상의 역할 및 프로필에 할당 및 할당할 수 있습니다.
* Snap Creator Server가 시작되면 snapcreator.properties 파일의 SNAPCREATOR_USER가 사용자로 추가됩니다.
* snapcreator.properties 파일의 SNAPCREATOR_USER는 시작 시 사용자를 생성할 때 기본 관리자 역할이 할당됩니다.




== 역할

역할에는 하나 이상의 권한이 있습니다. 할당된 권한은 사용자가 수행할 수 있는 작업과 사용자가 액세스할 수 있는 GUI 요소를 결정합니다. 다음과 같은 세 가지 기본 역할이 있습니다.

* 관리자 *
+
모든 API에 대한 모든 액세스 권한이 있습니다. 사용자를 생성, 편집 및 삭제할 수 있는 유일한 역할입니다.

* * 연산자 *
+
이 역할은 고급 사용자로 구성되며 RBAC를 제외한 모든 API에 액세스할 수 있습니다.

* * 뷰어 *
+
액세스가 매우 제한되어 있습니다. 이 역할에는 읽기 전용 Snap Creator API 호출에 대한 액세스 권한이 있습니다.



이러한 기본 제공 역할은 추가, 제거 또는 수정할 수 없습니다.



== 권한

권한은 사용자가 수행할 수 있는 작업의 집합입니다. 다음은 기본 제공 사용 권한입니다.

* * 백업 *
+
백업 또는 클론 작업을 수행하는 데 필요합니다.

* * 구성 *
+
구성 파일을 생성, 읽기, 업데이트 및 삭제하는 데 필요합니다.

* * 맞춤형 *
+
사용자 지정 플러그인 작업을 시작하는 데 필요합니다.

* * extended_repository *
+
카탈로그(확장 리포지토리라고도 함) 작업을 수행하는 데 필요합니다.

* * 글로벌 *
+
글로벌 구성 파일을 생성, 편집 및 삭제하는 데 필요합니다.

* policy_admin * 을 선택합니다
+
정책 작업(예: addPolicy, updatePolicy, removePolicy)을 호출하는 데 필요합니다.

* * policy_viewer *
+
읽기 전용 정책 작업에 필요합니다.

* * RBAC_관리 *
+
사용자 관리(예: 사용자 및 역할 생성, 업데이트, 삭제)에 필요합니다. 역할, 사용 권한을 할당 및 할당 취소할 수도 있습니다.

* * RBAC_VIEW *
+
사용자 계정, 할당된 역할 및 할당된 권한을 보는 데 필요합니다.

* * 복원 *
+
복구 작업을 수행하는 데 필요합니다.

* * 스케줄러 *
+
스케줄러 작업을 수행하는 데 필요합니다.

* * 뷰어 *
+
읽기 전용 작업에 대한 권한을 제공합니다.





== 운영

작업은 Snap Creator에서 권한을 확인하는 기본 값입니다. 작업의 예로는 getTask, fileCloneCreate, createTask, dirCreate 등이 있습니다.


NOTE: 작업은 추가, 제거 또는 수정할 수 없습니다.



== 프로파일

* 프로파일이 사용자에게 할당됩니다.
* RBAC의 프로파일은 파일 시스템의 프로파일 디렉토리에 작성됩니다.
* 특정 Snap Creator API는 사용자가 프로파일에 할당되어 있는지 확인하고 작업에 대한 사용 권한도 확인합니다.
+
예를 들어 사용자가 작업 상태를 원할 경우 RBAC는 사용자에게 일정 관리 작업을 호출할 권한이 있는지 확인한 다음 작업과 연관된 프로파일이 사용자에게 할당되어 있는지 확인합니다.

* 운영자 역할이 할당된 사용자가 프로필을 만들면 해당 프로필이 사용자에게 자동으로 할당됩니다.




== 스토리지 컨트롤러에 대한 사용자 액세스 관리

Active IQ Unified Manager 프록시를 사용하지 않는 경우 스토리지 컨트롤러와 통신하려면 사용자 이름과 암호가 필요합니다. 보안을 위해 암호를 암호화할 수 있습니다.


NOTE: 루트 사용자 또는 admin/vsadmin 사용자를 사용해서는 안 됩니다. 가장 좋은 방법은 필요한 API 권한을 사용하여 백업 사용자를 생성하는 것입니다.

네트워크 통신은 HTTP(80) 또는 HTTPS(443)를 통해 이루어지므로 Snap Creator가 실행되는 호스트와 스토리지 컨트롤러 간에 이러한 포트 중 하나 또는 둘 모두가 열려 있어야 합니다. 인증을 위해 스토리지 컨트롤러에 사용자를 생성해야 합니다. HTTPS의 경우 스토리지 컨트롤러에서 사용자가 설정 및 구성되어 있는지 확인해야 합니다.
