---
permalink: administration/concept_vm_backup_and_restore_using_vmware_plug_in.html 
sidebar: sidebar 
keywords: snap, creator, support, backup, vmware, virtual, machines, vsphere, api, vmware, vcenter, credentials 
summary: Snap Creator는 VMware 플러그인을 통해 VMware 가상 머신의 백업을 지원합니다. 가상 머신 백업은 VMware vCenter Server의 vSphere API를 통해 수행됩니다. 
---
= VMware 플러그인을 사용하여 가상 머신 백업 및 복구
:icons: font
:imagesdir: ../media/


[role="lead"]
Snap Creator는 VMware 플러그인을 통해 VMware 가상 머신의 백업을 지원합니다. 가상 머신 백업은 VMware vCenter Server의 vSphere API를 통해 수행됩니다.

가상 머신 백업의 경우 구성 파일에 다음 세부 정보를 제공해야 합니다.

* vCenter IP 또는 호스트 이름 및 자격 증명
* vSphere 가상 머신 및 데이터 저장소 이름



NOTE: vCenter가 기본 포트(443)에 구성되어 있는 경우에만 Snap Creator가 vCenter를 검색합니다.

복원 작업의 경우 백업 매개 변수와 스냅샷 복사본 이름을 제공해야 합니다.

VMware 백업 및 복원 프로세스를 수행할 때는 다음 사항을 고려하십시오.

* 가상 머신이 나열되고 사용할 수 없는 경우 플러그인에서 오류 메시지를 표시합니다. 손실된 가상 시스템이 백업되어도 복구할 수 없습니다.
* 데이터 저장소가 나열되면 데이터 저장소의 모든 가상 머신이 백업됩니다.
* 지정된 데이터 저장소에 있는 나열된 가상 머신 또는 가상 머신만 백업됩니다.
* 백업용으로 선택한 가상 머신이 백업용으로 선택된 데이터 저장소 내에 포함된 경우 한 번만 백업됩니다.
* VMware 플러그인은 NFS(Network File System) 및 VMFS(VMware Virtual Machine File System) 데이터 저장소를 모두 지원합니다.
+
** NFS 데이터 저장소에서 가상 머신 복구는 스토리지 시스템에서 SFSR(Single File SnapRestore)을 사용하여 호스트 복제본을 방지합니다.
** VMFS 데이터 저장소에서 가상 머신을 복구하려면 다음 단계를 수행하십시오.
+
... 특정 복원 스냅샷 복사본에 포함된 LUN의 FlexClone 또는 LUN 클론을 사용합니다.
... 클러스터에 매핑합니다.
... vCenter API 호출을 사용하여 VMFS 데이터 저장소의 스냅샷 복제본에서 원래 VMFS 데이터 저장소로 컨텐츠를 복제합니다.





