---
permalink: administration/reference_vmware_vibe_plug_in.html 
sidebar: sidebar 
keywords: snap, creator, support, backup, virtual, machine, vmware, windows, linux, vcenter, ha 
summary: Snap Creator는 VMware Vibe 플러그인을 통해 VMware 가상 머신 및 vApp의 백업을 지원합니다. VMware 플러그인은 vSphere 및 vCloud Director를 사용하는 vApp이 있는 가상 머신 모두를 위한 통합 플러그인입니다. 
---
= VMware Vibe 플러그인
:icons: font
:imagesdir: ../media/


[role="lead"]
Snap Creator는 VMware Vibe 플러그인을 통해 VMware 가상 머신 및 vApp의 백업을 지원합니다. VMware 플러그인은 vSphere 및 vCloud Director를 사용하는 vApp이 있는 가상 머신 모두를 위한 통합 플러그인입니다.

VMware Vibe 플러그인을 사용할 때는 다음 사항을 고려해야 합니다.

* VMware 플러그인은 Windows 및 Linux에서만 지원됩니다.
+
비Windows 또는 비 Linux Snap Creator Server를 사용하는 경우 VMware 플러그인을 실행하려면 Snap Creator Windows 또는 Linux 에이전트가 필요합니다.

* 프록시로 Unified Manager 서버가 지원되지 않습니다.
* 오픈 시스템 SnapVault 및 아카이브 로그 관리를 사용한 마운트, 마운트 해제 및 백업 작업은 지원되지 않습니다.
* VMware 플러그인을 통한 VMware HA(고가용성)는 테스트되지 않았으며 지원되지 않습니다.
* VMware 플러그인을 사용하는 VMware vCenter 연결 모드는 테스트되지 않았으며 지원되지 않습니다.
* VMware 플러그인은 RDM(Raw Device Mapping)을 지원하지 않습니다.
* 볼륨은 자동 감지를 사용하여 검색됩니다.
+
검색된 대상 볼륨이 SnapMirror 관계에 있지 않으면 볼 수 없습니다. dpstatus 명령을 사용하여 SnapMirror 관계를 확인할 수 있습니다. SnapMirror 관계가 없는 경우 먼저 SnapMirror 관계를 생성해야 합니다.

* 복구 작업을 수행하기 전에 모든 VMware 스냅샷 복사본을 삭제해야 합니다.
* 복구 작업이 완료된 후 새 환경이 정리되고 모든 VMware 스냅샷 복사본이 제거되도록 복원된 가상 머신 및 vApp의 Snap Creator 백업을 실행해야 합니다.
+
VMware 플러그인이 VMware 스냅샷 복사본을 정리할 수 없고 오류가 표시되면 VMware 스냅샷 복사본을 수동으로 제거해야 합니다. VMware 플러그인은 VMware 스냅샷 복사본의 100% 제거를 보장하지 않습니다. 이는 알려진 VMware 문제입니다.

* VMware 플러그인은 32비트 Linux 시스템과 64비트 Linux 시스템을 사용하는 64비트 Snap Creator만 지원합니다.
* 삭제된 가상 시스템은 복구할 수 없습니다.
* 볼륨 복원 작업은 지원되지 않으며 애플리케이션 정의 복원 작업만 지원됩니다.
* sc_agent_timeout 매개 변수의 값은 1800 이상으로 설정해야 합니다.
* Vibe_vmware_snapshot 매개 변수(VMware 스냅샷 옵션)의 기본값은 N입니다
* app_defined_restore 값이 Y인 경우 그래픽 사용자 인터페이스(GUI)를 사용한 SnapVault 복구 작업은 지원되지 않습니다.
* GUI를 사용하여 SnapMirror 및 SnapVault 구성을 생성하는 동안 SnapMirror 및 SnapVault 관계가 자동으로 감지되지 않으므로 SnapMirror 및 SnapVault 매개 변수를 수동으로 입력해야 합니다.
* VMware 플러그인은 ISO 마운트 경로를 데이터 저장소로 검색합니다.


다음 표에는 VMware Vibe 플러그인 매개 변수가 나열되어 있고 매개 변수 설정이 제공되며 매개 변수에 대한 설명이 나와 있습니다.

|===
| 매개 변수 | 설정 | 설명 


 a| 
Vibe_dynamic_volumes_update
 a| 
Y 또는 nDefault: 설정되지 않음
 a| 
이 매개 변수를 N으로 설정하면 동적 볼륨 업데이트가 수행되지 않습니다. 즉, 볼륨, SnapVault_볼륨, SnapMirror_볼륨 및 NTAP_DFM_DATA_SET 매개 변수를 수동으로 설정해야 합니다.



 a| 
진동_비중
 a| 
기본값: N
 a| 
ICMP(Internet Control Message Protocol)가 VMware 플러그인 또는 스토리지 컨트롤러를 ping하는 데 사용되지 않도록 지정합니다.



 a| 
Vibe_vCloud_IPADDR
 a| 
해당 없음
 a| 
에 로그인하는 데 사용되는 vCloud Director의 IP 주소 또는 호스트 이름을 지정합니다(vCloud만 해당).



 a| 
ViBE_vCloud_USER입니다
 a| 
해당 없음
 a| 
vCloud Director에 로그인하는 데 사용할 사용자 이름을 지정합니다(vCloud만 해당). @org 또는 @system(최상위 vCloud 데이터베이스)을 설정해야 합니다.


NOTE: 백업 및 복구 작업을 수행하려면 vCloud Director 시스템 관리자 사용자 이름을 사용해야 합니다. 조직 관리자 자격 증명 또는 다른 사용자 자격 증명을 사용하는 경우 이러한 작업이 실패합니다.

예: 'administrator@system'



 a| 
Vibe_vCloud_PASSWD
 a| 
해당 없음
 a| 
지정된 Vibe_vCloud_user(vCloud만 해당)와 연결된 암호를 지정합니다.



 a| 
Vibe_vcenter_user.(진동 vCenter 사용자
 a| 
해당 없음
 a| 
vCenter에 로그인하는 데 사용할 사용자 이름을 지정합니다.



 a| 
Vibe_vcenter_PASSWD
 a| 
해당 없음
 a| 
지정된 Vibe_vcenter_user와 연결된 암호를 지정합니다.



 a| 
Vibe_vCloud_Names
 a| 
해당 없음
 a| 
백업할 조직, 가상 데이터 센터 및 vApp 객체 이름(vCloud만 해당)을 나열합니다. 예: 'org:VDC1, VDDC2:VAPP1, VAPP2, ORG2:VDC3:;ORG3::VAPP6'



 a| 
Vibe_vsphere_names를 선택합니다
 a| 
해당 없음
 a| 
에는 vCenter당 백업해야 하는 데이터 저장소와 가상 머신(vSphere만 해당)이 나와 있습니다. 예: 'VCENTER1:DS1:VM1;VCENTER2;DS2, DS3:;VCENTER3::VM4



 a| 
Vibe_TRIM_Vsphere_names를 참조하십시오
 a| 
해당 없음
 a| 
에는 vCenter당 백업에서 제거해야 하는 가상 머신이 나와 있습니다(vSphere만 해당). 예: 'VCENTER1:VM99; VCENTER2:VM5, VM12



 a| 
Vibe_restore_interval입니다
 a| 
기본값: 30초
 a| 
각 복원 검사 사이의 시간을 지정합니다.



 a| 
Vibe_restore_time
 a| 
기본값: 3600초
 a| 
전체 복원 작업이 완료될 때까지 대기하는 총 시간을 지정합니다.



 a| 
Vibe_vmware_snapshot
 a| 
기본값: N
 a| 
백업 중에 VMware 스냅샷 복사본을 생성합니다.



 a| 
Vibe_ignore_EXPORTFS=Y 또는 N
 a| 
기본값: N
 a| 
이 매개 변수를 Snap Creator Vibe 구성 파일에 수동으로 추가해야 합니다.

이 값을 Y로 설정하면 7-Mode 구성에서 작동하는 Data ONTAP는 컨트롤러의 모든 exportfs 값을 무시합니다. 대신 Data ONTAP는 볼륨 내보내기 경로를 /vol/datastore_name으로 매핑합니다. 여기서 데이터 저장소 이름은 백업용으로 지정됩니다. vFiler 유닛을 사용하는 이전 환경에서는 개별 데이터 저장소의 exportfs 정보를 vFiler 유닛에서 사용할 수 없기 때문에 이 방법을 사용할 수 있습니다. 대신 구성을 통해 쿼리를 기반으로 경로를 vfiler0에 매핑해야 합니다.

|===
* 관련 정보 *

http://mysupport.netapp.com/matrix["상호 운용성 매트릭스 툴: mysupport.netapp.com/matrix"]
