---
permalink: administration/reference_parameters_to_connect_to_vfiler_units_and_interface.html 
sidebar: sidebar 
keywords: several, parameter, snap, creator, sefver, vfiler, unit, interface, management, secondary 
summary: Snap Creator Server를 vFiler 유닛 및 인터페이스에 연결하려면 몇 가지 매개 변수가 필요합니다. 
---
= vFiler 유닛 및 인터페이스에 연결하는 매개 변수입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
Snap Creator Server를 vFiler 유닛 및 인터페이스에 연결하려면 몇 가지 매개 변수가 필요합니다.

|===
| 매개 변수 | 설정 | 설명 


 a| 
VFilers를 참조하십시오
 a| 
 a| 
vFiler 유닛 및 해당 호스팅 스토리지 시스템 또는 볼륨 나열 예: vFiler1@controller1:vol1,vol2,vol3;vFiler2@controller2:vol1;vFiler3@controller3:vol2,vol3** 참고:** vfiler 유닛에서는 HTTPS가 지원되지 않습니다.



 a| 
관리_인터페이스
 a| 
 a| 
에는 통신에 사용되는 기본 스토리지 컨트롤러 및 관리 인터페이스가 나와 있습니다. 예: management_interfaces=controller1:controller2:controller2-mgmt



 a| 
secondary_interfaces를 선택합니다
 a| 
 a| 
SnapVault 및 SnapMirror 관계의 기본 스토리지 컨트롤러 또는 vFiler 유닛 및 해당 보조 인터페이스의 소스 또는 대상을 나열합니다. 예: 컨트롤러1: 소스/컨트롤러2 - 대상


NOTE: 이 2차 인터페이스를 사용하려면 SnapVault 및 SnapMirror 관계를 구성해야 합니다. Snap Creator는 SnapMirror 및 SnapVault 관계를 관리하지 않습니다.



 a| 
use_proxy를 사용합니다
 a| 
(Y
| 해당 없음) 


 a| 
API 호출이 스토리지 컨트롤러 대신 Active IQ Unified Manager 서버 프록시를 통해 직접 이동할 수 있도록 합니다. 이 옵션을 사용하는 경우 NTAP_users는 필요하지 않습니다.
 a| 
IP_ADDR 허용
 a| 
(Y

|===