---
permalink: administration/reference_mysql_plug_in_parameters_settings_and_descriptions.html 
sidebar: sidebar 
keywords: mysql, plug-in, net-mysql, interoperability, matrix 
summary: MySQL 플러그인은 Net-MySQL을 사용하여 데이터베이스와 통신합니다. 
---
= MySQL 플러그인
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MySQL 플러그인은 Net-MySQL을 사용하여 데이터베이스와 통신합니다.

MySQL 플러그인은 여러 데이터베이스의 백업 및 복원 작업을 지원하지 않습니다. 상호 운용성 매트릭스에는 지원 및 호환성에 대한 최신 정보가 포함되어 있습니다.

Snap Creator 구성의 경우 MySQL 데이터베이스 사용자는 SUPER 및 reload 등의 다른 권한과 함께 잠금 테이블 권한이 부여되어야 합니다.

다음 표에는 MySQL 플러그인 매개 변수가 나열되어 있고, 해당 설정이 제공되며, 에 대한 설명이 나와 있습니다.

|===
| 매개 변수 | 설정 | 설명 


 a| 
APP_NAME입니다
 a| 
MySQL
 a| 
응용 프로그램 이름입니다



 a| 
mysql_databases
 a| 
db_name: user_name/password
 a| 
MySQL 데이터베이스, 사용자 이름 및 암호 목록 사용자 이름과 암호를 포함하는 여러 데이터베이스를 세미콜론으로 구분된 목록(예: dB1:user1/pwd1; DB2:user2/pwd2')으로 지정할 수 있습니다.



 a| 
호스트
 a| 
host_name(호스트 이름)
 a| 
데이터베이스가 있는 호스트의 이름입니다. * 참고: * validate_volumes는 host=localhost인 경우에만 제대로 작동합니다. host=ip_address인 경우 validate_volumes는 MySQL 데이터베이스를 검색하지 않습니다.



 a| 
포트
 a| 
db_name: port_number
 a| 
데이터베이스 및 수신 대기 중인 포트 목록(예: dB1:3307, DB2:3308).



 a| 
master_slave 를 선택합니다
 a| 
(예|아니오)
 a| 
백업 데이터베이스 환경을 지정합니다. Y로 설정하면 마스터 데이터베이스를 백업합니다.

N으로 설정하면 슬레이브 데이터베이스를 백업하거나 마스터 슬레이브 구성을 사용하지 않습니다.


NOTE: Snap Creator Framework 백업은 Master_Slave 옵션이 활성화된 MySQL 서버에서 필요한 MySQL 바이너리 로그 파일을 삭제합니다. Snap Creator Framework를 사용하는 MySQL(마스터) 데이터베이스 백업은 모든 바이너리 로그 파일을 제거하고 재설정 번호(.000001)가 있는 비어 있는 단일 바이너리 로그 파일만 남겨 둡니다. 이 문제 때문에 백업 작업 후 슬레이브 서버가 시작되지 않습니다.



 a| 
purge_binary_log입니다
 a| 
(예|아니오)
 a| 
이 매개변수는 MySQL 마스터-슬레이브 데이터베이스 설정에서 작동합니다.

이 옵션을 'Y'로 설정하면 사용 가능한 최신 바이너리 로그 파일까지 바이너리 로그를 삭제합니다.

N으로 설정하면 삭제 쿼리에 최근 타임스탬프가 사용됩니다.

|===
* 관련 정보 *

http://mysupport.netapp.com/matrix["상호 운용성 매트릭스 툴: mysupport.netapp.com/matrix"]
