---
permalink: administration/reference_snap_creator_variable_and_parameter_descriptions.html 
sidebar: sidebar 
keywords: snap, creator, built-in, variable, parameter, basic, configuration, description, snap, type, time, action 
summary: Snap Creator에는 기본 구성에 필요한 내장형 변수와 매개변수가 포함되어 있습니다. 
---
= Snap Creator 변수 및 매개 변수 설명
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Snap Creator에는 기본 구성에 필요한 내장형 변수와 매개변수가 포함되어 있습니다.

|===
| 변수 | 설명 


 a| 
%snap_type입니다
 a| 
Snap Creator를 실행할 때 사용되며, 보존 정책(매일, 매주, 매월)입니다.



 a| 
%snap_time입니다
 a| 
스냅샷 복사본의 이름 지정에 사용되는 타임스탬프(YYYYMMDDhhmmss)를 통해 모든 스냅샷 복사본에 대해 보장된 고유 이름을 생성합니다. 또한 백업 보고서 및 Sybase 트랜잭션 로그의 이름을 지정하는 데 사용됩니다.



 a| 
% 작업
 a| 
Snap Creator(백업)를 실행할 때 수행할 수 있는 작업 목록입니다



| CloneVol | CLoneLun 


| 아키텍처 | 복원 


| 백업델 | 백업 목록 


| CloneList(목록)를 클릭합니다 | Pmsetup 


| OSSV)  a| 
%MSG



 a| 
e-메일 또는 Tivoli와 같은 다른 프로그램으로 오류 메시지를 보내는 데 사용됩니다. SENDTRAP 기능에서만 사용할 수 있습니다.
 a| 
%user_defined

|===
다음 표에서는 기본 구성에 사용되는 Snap Creator 매개 변수를 나열하고 설명합니다.

|===


| 매개 변수 | 설정 | 설명 


 a| 
이름
 a| 
 a| 
고유해야 하는 스냅샷 복사본 명명 규칙을 지정합니다. 스냅샷 복사본은 명명 규칙에 따라 삭제됩니다.



 a| 
snap_timestamp_only
 a| 
(Y
| 해당 없음) 


 a| 
스냅샷 명명 규칙을 Y로 설정하면 스냅샷 복사본이 YYMMDDHHMMSS로 종료됩니다. 그렇지 않으면 새 스냅샷 복사본의 이름이 YYYYMMDDHHMMSS로 끝으로 변경됩니다.
 a| 
볼륨
 a| 



 a| 
에는 스냅샷 복사본을 생성하려는 운영 스토리지 컨트롤러 및 볼륨이 나와 있습니다. 예를 들면 다음과 같습니다.

[listing]
----
controller1:vol1,vol2,vol3;
controller2:vol1;
controller3:vol2,vol3
---- a| 
volume_groups 를 선택합니다
 a| 
vol_1, vol_2, vol_n



 a| 
여러 볼륨을 단일 그룹으로 정의합니다. 다중 볼륨은 쉼표로 구분된 목록 형식으로 지정됩니다. 예:

[listing]
----
VOLUMES_01=filer1:vol1,vol2,vol3;filer2:vol1
VOLUMES_02=filer1:vol3,vol4
VOLUMES_03=filer2:vol3,vol4
VOLUME_GROUPS=VOLUMES_01,VOLUMES_02,VOLUMES_03
----

NOTE: volume_groups는 백업 작업에만 지원됩니다. 이 매개 변수를 설정하면 백업 중에 볼륨 매개 변수가 무시됩니다.
 a| 
NTAP_snapshot_retentions
 a| 



 a| 
특정 의제로 유지할 스냅샷 복사본의 수를 결정합니다. 예:

[listing]
----
daily:7,weekly:4,monthly:1
---- a| 
NTAP_users
 a| 



 a| 
에는 스토리지 시스템과 해당 사용자 이름 및 암호가 나와 있습니다.예:

[listing]
----
controller1:joe/password1;
controller2:bob/password2;
controller3:ken/password3
----

NOTE: 암호에는 최소 두 개의 문자가 포함되어야 합니다.
 a| 
NTAP_PWD_protection
 a| 
(Y



| 해당 없음)  a| 
암호 보호 설정 또는 해제 모든 암호(스토리지 시스템 및 애플리케이션 또는 플러그인)를 암호화하고 암호화된 암호를 구성 파일에 저장해야 합니다.
 a| 
운송



 a| 
HTTP
| HTTPS  a| 
HTTP 또는 HTTPS를 사용하여 저장소 컨트롤러에 연결할 수 있습니다.** 참고:** HTTPS에는 openssl-devel 라이브러리가 필요할 수 있습니다.



 a| 
포트
 a| 
 a| 
스토리지 컨트롤러가 사용하는 포트 번호를 구성합니다(일반적으로 80 및 443)



 a| 
LOG_NUM
 a| 
 a| 
Snap Creator가 유지해야 하는 .debug 및 .out 보고서의 수를 지정합니다



 a| 
CONFIG_TYPE
 a| 
플러그인
| 표준 


 a| 
구성을 지정합니다. typeThere는 두 가지 유형의 구성인 플러그인과 표준입니다. 여러 플러그인 구성을 사용하여 복잡한 중지 및 중지 해제 백업 워크플로우를 구축할 수 있습니다.
 a| 
cmode_cluster_users입니다
 a| 



 a| 
(clustered Data ONTAP에 필요) 운영 클러스터 및 2차 clustered Data ONTAP 클러스터와 해당 사용자 이름 및 암호가 나열되어 있습니다.예:

[listing]
----
cluster1:joe/password1;
cluster2:bob/password2
----

NOTE: 암호에는 최소 두 개의 문자가 포함되어야 합니다.
 a| 
cmode_cluster_name입니다
 a| 



 a| 
(clustered Data ONTAP에 필요) 운영 clustered Data ONTAP 클러스터의 이름을 지정합니다
 a| 
cmode_snapshot_force_delete
 a| 
(Y



| 해당 없음)  a| 
Clustered Data ONTAP의 스냅샷 복사본 정책에 따라 삭제해야 하는 스냅샷 복사본이 삭제되도록 보장하고, 클론 복제 등 종속 항목이 있는 경우에는 스냅샷 복사본이 삭제되지 않습니다.
 a| 
log_trace_enable입니다



 a| 
(Y
| 해당 없음)  a| 
ONTAP 솔루션 결과 개체 관리가 비활성화되어 있으면 모든 이벤트의 로깅을 설정하거나 해제합니다.



 a| 
NTAP_timeout
 a| 
초
 a| 
모든 스토리지 컨트롤러에 대한 시간 초과 값을 설정합니다. ONTAP 솔루션 통화 관리 기본값은 60초입니다



 a| 
global_Config를 사용합니다
 a| 
(Y
| 해당 없음) 


 a| 
글로벌 구성을 사용하여 값을 저장할 수 있습니다
 a| 
federated_applications를 선택합니다
 a| 



 a| 
에서는 구성에 포함된 통합 애플리케이션의 구성 및 프로파일 이름을 보여 줍니다. 예를 들면 다음과 같습니다.

[listing]
----
databases@db2;databases@oracle
---- a| 
cmode_set
 a| 
(Y



| 해당 없음)  a| 
구성이 clustered Data ONTAP인지 7-Mode에서 운영되는 Data ONTAP인지 정의합니다
 a| 
allow_duplicate_SNAME를 선택합니다



 a| 
(Y
| 해당 없음)  a| 
(선택 사항) 중복 스냅샷 이름으로 구성 파일을 생성하는 기능을 활성화 또는 비활성화합니다. 이 매개변수는 전역(수퍼 글로벌 또는 프로파일 글로벌) 구성 파일에서 작동하지 않습니다.



 a| 
SNAPCREATOR_MISSEDJOB_RUN
 a| 
(Y
| 해당 없음) 
|===