---
permalink: administration/reference_citrix_xen_plug_in.html 
sidebar: sidebar 
keywords: snap, creator, support, backup, restore, citrix, xenserver, virtual, machine, vm, citrix, xenserver, plug-in 
summary: 'Snap Creator는 Citrix XenServer 플러그인을 사용하여 Citrix XenServer 가상 머신(VM)의 백업 및 복원을 지원합니다.' 
---
= Citrix XenServer 플러그인
:icons: font
:imagesdir: ../media/


[role="lead"]
Snap Creator는 Citrix XenServer 플러그인을 사용하여 Citrix XenServer 가상 머신(VM)의 백업 및 복원을 지원합니다.


NOTE: 지원 또는 호환성 매트릭스에 대한 최신 정보는 상호 운용성 매트릭스 를 참조하십시오.

Citrix XenServer 플러그인은 Windows 및 XenServer를 지원합니다.

Citrix XenServer 플러그인을 사용할 때는 다음 사항을 고려하십시오.

* 프록시로 Active IQ Unified Manager 서버를 지원하지 않습니다.
* 오픈 시스템 SnapVault 및 아카이브 로그 관리를 사용한 마운트, 마운트 해제 및 백업 작업은 지원되지 않습니다.
* 볼륨 복원 작업은 지원되지 않으며 애플리케이션 정의 복원 작업만 지원됩니다.
* 삭제된 VM은 복원할 수 있습니다.
* XenCenter가 설치된 호스트에 Snap Creator Agent가 설치되어 있어야 하며, Snap Creator Server가 XenServer에 설치되어 있지 않아야 합니다.
* SC_AGENT_TIMEOUT 값은 기본값 600 이상이어야 합니다.
* app_defined_restore 값이 Y인 경우 GUI를 사용한 SnapVault 복구 작업은 지원되지 않습니다.
* 풀 마스터가 서버 풀에서 다운되는 경우 추가 작업을 위해 Snap Creator 구성 파일을 새 마스터 서버와 함께 수동으로 수정해야 합니다.
* XenServer 툴은 모든 VM에 설치해야 합니다.
* SAN(Storage Area Network) 환경의 Fibre Channel에서는 Snap Creator Agent가 설치된 호스트에 plink.exe 툴을 설치하고 plink.exe 경로를 시스템 환경 변수에 추가해야 합니다.
+
plink.exe 경로를 시스템 환경 변수에 추가하는 방법에 대한 자세한 내용은 _Snap Creator Framework 설치 가이드_를 참조하십시오.

* VM 일시 중지 및 일시 중지 취소 작업은 순차적으로 수행됩니다.
+
여러 VM의 경우 백업 작업 중 일시 중지 상태의 VM 지속 시간은 VM 수에 따라 달라집니다.

* 볼륨 자동 검색이 지원됩니다.




== 지원되는 Citrix XenServer 구성

지원되는 Citrix XenServer 구성은 다음과 같습니다.

* 산
+
** 스토리지 저장소당 하나의 가상 디스크 이미지(VDI)를 사용하여 게스트 가상 머신을 지원합니다.
** 스토리지 저장소당 하나의 VDI로 데이터 디스크를 지원합니다


* NAS
+
** NFS 마운트에 설치된 게스트 VM을 지원합니다.
** NFS 마운트에서 데이터 디스크를 지원합니다.






== 매개 변수

다음 표에는 Citrix XenServer 플러그인 매개 변수가 나열되어 있습니다.

|===


| 매개 변수 | 설정 | 설명 


 a| 
Xen_VMs
 a| 
호스트 IP: VM #
 a| 
특정 호스트의 가상 머신을 슬래시(/)로 구분하여 나열합니다. 예: 10.10.192: VM1/VM2/VM3



 a| 
Xen_host_users
 a| 
호스트 IP: 사용자 이름/암호
 a| 
Xen 호스트 및 해당 사용자 이름 및 암호를 나열합니다.



 a| 
Xen_bin_path입니다
 a| 
예: c:\Program Files\Citrix\XenCenter\xe.exe
 a| 
XenServer 실행 파일(XE)의 경로를 지정합니다. XenCenter 콘솔은 VM 메타데이터를 가져오고 내보내는 데 필요합니다.



 a| 
Xen_metadata_path
 a| 
예: c:\scmetadata
 a| 
가상 머신 메타데이터를 다운로드할 수 있는 서버의 경로를 지정합니다.



 a| 
Xen_restore_VMs
 a| 
예: xenserver1:vm1, VM2; xenserver2:vm1, VM2
 a| 
복원해야 하는 VM이 포함되어 있습니다. 이 매개 변수는 복구 작업 중에만 필요합니다.

|===
* 관련 정보 *

http://mysupport.netapp.com/matrix["상호 운용성 매트릭스 툴: mysupport.netapp.com/matrix"]
