---
permalink: administration/reference_db2_plug_in.html 
sidebar: sidebar 
keywords: db2, plug-in, communicate, database 
summary: DB2 플러그인은 DB2 명령을 사용하여 데이터베이스와 통신합니다. 
---
= DB2 플러그인
:icons: font
:imagesdir: ../media/


[role="lead"]
DB2 플러그인은 DB2 명령을 사용하여 데이터베이스와 통신합니다.

다음 표에는 DB2 플러그인 매개 변수가 나열되어 있고 매개 변수 설정을 제공하며 매개 변수에 대한 설명이 나와 있습니다.

|===
| 매개 변수 | 설정 | 설명 


 a| 
APP_NAME입니다
 a| 
DB2
 a| 
애플리케이션 이름을 제공합니다.



 a| 
DB2_데이터베이스
 a| 
db_name:user_name입니다
 a| 
DB2 데이터베이스와 사용자 이름을 나열합니다. 여러 데이터베이스 및 사용자 이름은 세미콜론으로 구분된 목록(예: dB1:user1; DB2:user2)으로 지정할 수 있습니다.



 a| 
DB2_CMD
 a| 
path_to_db2cli_cmd를 입력합니다
 a| 
데이터베이스에서 추가 명령을 실행할 수 있도록 데이터베이스 연결을 초기화하는 데 사용되는 경로를 지정합니다.

* UNIX 기반 환경: ''dB2_install_directory/sqllib/bin/db2'
+
예: `/home/db2inst1/sqllib/bin/db2'

* Windows: dB2_install_directory\SQLLIB\bin\db2cmd.exe"
+
예: 'C:\"Program Files"\IBM\SQLIB\bin\db2cmd.exe'



경로를 지정하지 않으면 sqllib/DB2가 경로로 사용됩니다.

|===
* 참고: * DB2 플러그인은 기본적으로 WAFL(Write Anywhere File Layout) 작업을 처리합니다. DB2 플러그인을 사용하여 정합성 보장 그룹 백업을 백업하려면 매개 변수를 ntap_consistency_group_WAFL_sync 매개 변수로 N으로 설정해야 합니다 이 매개변수를 Y로 설정하면 추가 및 중복 동기화 작업이 수행됩니다.

지원 또는 호환성 매트릭스를 보는 방법에 대한 최신 정보는 상호 운용성 매트릭스 를 참조하십시오.

* 관련 정보 *

http://mysupport.netapp.com/matrix["상호 운용성 매트릭스 툴: mysupport.netapp.com/matrix"]
