---
permalink: administration/reference_snap_creator_agent_error_messages.html 
sidebar: sidebar 
keywords: snap, creator, agent, error, message, aft, sc_agentconfiguration, parameter, remote, port 
summary: 다음 표에는 Snap Creator Agent 오류 메시지가 나와 있습니다. 
---
= Snap Creator 에이전트 오류 메시지
:icons: font
:imagesdir: ../media/


[role="lead"]
다음 표에는 Snap Creator Agent 오류 메시지가 나와 있습니다.

|===
| 오류 코드 | 설명/해상도 


 a| 
agt-00001
 a| 
지정된 포트에서 Snap Creator 에이전트 또는 다른 프로세스가 실행되고 있습니다. 다른 포트를 사용해 보십시오.



 a| 
agt-00003
 a| 
지정된 매개 변수가 Snap Creator Agent를 시작하는 데 올바르지 않습니다. 필요한 매개 변수를 확인하십시오.



 a| 
agt-00004
 a| 
SC_AGENTconfiguration 매개변수는 원격 에이전트를 사용할 때 정의해야 합니다.



 a| 
agt-00005
 a| 
일시 중지 작업을 뒤로 되돌릴 수 없으며 하나의 작업이 이미 실행 중입니다. 일시 중지 해제를 기다리거나 실행합니다.



 a| 
agt-00006)을 참조하십시오
 a| 
감시 장치 프로세스를 실행할 수 없습니다. 시스템이 최대 프로세스 수에 도달했을 가능성이 높습니다. 구성에서 감시 장치를 비활성화하거나 운영 체제 설정을 확인합니다.



 a| 
agt-00008
 a| 
일시 중지 및 일시 중지 해제 작업이 완료되지 않았으며 백업이 충돌의 일관성만 있습니다. 로그를 확인합니다. 일시 중지 작업이 너무 오래 걸리고 감시장치를 사용하는 경우 이 문제가 발생할 수 있습니다. Watchdog 프로세스는 구성에 정의된 대로 x초 후 강제 중지 해제를 수행합니다.



 a| 
agt-00009
 a| 
에이전트 측의 agent.conf에서 pRE 및 Post 명령을 허용해야 합니다. agent.conf를 업데이트하고 필요한 명령을 허용합니다.



 a| 
agt-00010
 a| 
에이전트가 구성 파일을 읽을 수 없습니다. agent.conf 파일의 권한을 확인합니다.



 a| 
agt-00011
 a| 
상담원에게 명령이 전송되었지만 허용되지 않습니다. agent.conf를 업데이트하여 명령을 허용합니다.



 a| 
agt-00012
 a| 
이 오류는 플러그인을 로드하는 동안 발생합니다. plug-in 및 app_name 설정을 확인한다.



 a| 
agt-00013
 a| 
이 오류는 플러그인 내에서 setenv 메서드를 실행하는 동안 발생합니다. 플러그인을 확인하고 구문이 올바른지 확인합니다.

|===