---
permalink: administration/reference_storage_error_messages.html 
sidebar: sidebar 
keywords: storage troubleshoot, error, message 
summary: 스토리지 관련 오류 메시지는 발생한 문제를 해결하는 데 도움이 될 수 있습니다. 
---
= 스토리지 오류 메시지
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 관련 오류 메시지는 발생한 문제를 해결하는 데 도움이 될 수 있습니다.

다음 표에는 오류 코드 및 메시지와 함께 오류에 대한 간단한 설명 및 권장 해결 방법이 나와 있습니다.

|===
| 오류 코드 | 오류 메시지 | 설명/해상도 


 a| 
스토리지 - 00001
 a| 
날짜 형식 [%s]이(가) 올바르지 않습니다: [%s]
 a| 
스냅 생성기에서 볼륨 클론을 생성하지 않았거나 클론 이름에 추가된 시간 스탬프가 잘못되었습니다.



 a| 
스토리지 - 00002
 a| 
executor를 검색할 수 없습니다
 a| 
보관을 위해 실행자가 생성되지 않았습니다. 로그에서 NetApp 관리 효율 오류를 확인하여 문제의 원인을 밝혀낼 수 있습니다.



 a| 
스토리지 - 00003
 a| 
호스트에 연결할 수 없습니다
 a| 
호스트에 연결할 수 없습니다. 로컬 방화벽 설정이 올바른지, 그리고 호스트가 Snap Creator Server가 설치된 시스템에서 ping을 수행할 수 있는지 확인합니다.



 a| 
스토리지 - 01003
 a| 
이벤트 ID [%s], 카테고리 [%s], 설명 [%s], 레벨 [%s], 호스트 이름 [%s]을(를) 사용하여 AutoSupport 메시지를 생성하지 못했습니다. 오류 [%s].
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 01004
 a| 
파일 복구의 경우 소스 볼륨과 타겟 볼륨이 같아야 합니다.
 a| 
소스 볼륨과 타겟 볼륨이 다릅니다. 소스 볼륨 및 타겟 볼륨과 동일한 볼륨을 제공하십시오.



 a| 
스토리지 - 02003
 a| 
[%s] 볼륨에 정합성 보장 그룹 스냅샷 복사본 [%s]을(를) 생성하지 못했습니다. 오류: [%s];
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 02006
 a| 
CG ID가 [%s]인 [%s]의 일관성 그룹 스냅샷 복사본을 커밋하는 데 실패했습니다. 오류 [%s]
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 02009
 a| 
[%s] 볼륨에 대한 스냅샷 복사본 [%s]을(를) 생성하지 못했습니다. 오류: [%s]
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 02015
 a| 
[%s] 볼륨의 스냅샷 복사본 [%s]을(를) 제거하지 못했습니다. 오류: [%s]
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지-02021
 a| 
[%s] 볼륨의 스냅샷 복사본 [%s]을(를) 복원하지 못했습니다. 오류: [%s]
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지-02025
 a| 
스냅샷 복사본 [%s]에서 [%s](으)로 파일 [%s]을(를) 복원하지 못했습니다. 오류 [%s]
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 02028
 a| 
볼륨 [%s]에 대한 기본 SnapVault 스냅샷 복사 일정 [%s]을(를) 생성하지 못했습니다. 오류 [%s]
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 02034
 a| 
오류 [%s](으)로 인해 볼륨 [%s]에서 기본 SnapVault 스냅샷 복사본 일정을 제거하지 못했습니다.
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 02038
 a| 
스냅샷 복사본 [%s]을(를) 기반으로 볼륨 [%s]의 클론 [%s]을(를) 생성하지 못했습니다. 오류 [%s]
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 02041
 a| 
스냅샷 복사본 [%s]을(를) 기반으로 [%s] 볼륨의 [%s] 파일을 [%s](으)로 클론 복제하지 못했습니다. 오류 [%s]
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 02043
 a| 
경로 [%s]에 파일을 나열하지 못했습니다. 오류 [%s]
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 02046
 a| 
공간 예약 [%s]을(를) 가진 스냅샷 복사본 [%s]을(를) 기반으로 [%s]을(를) [%s]에 따라 LUN [%s]을(를) 클론 복제하지 못했습니다. 오류 [%s]
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 02049
 a| 
[%s] 볼륨에서 [%s] LUN을 삭제하지 못했습니다. 오류: [%s]
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 02052
 a| 
오류 [%s](으)로 인해 LUN 나열에 실패했습니다.
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지-02062
 a| 
액세스 [%s]을(를) 사용하여 호스트 이름 [%s]에 대한 NFS 내보내기 [%s]을(를) 추가하지 못했습니다. 오류 [%s]
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 02072
 a| 
오류 [%s](으)로 인해 컨트롤러 [%s]에서 SnapMirror 상태를 검색하지 못했습니다.
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 02075
 a| 
오류 [%s](으)로 인해 컨트롤러 [%s]에서 SnapMirror 관계를 검색하지 못했습니다.
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
보관 - 02082
 a| 
스냅샷 복사본 [%s]을(를) 기반으로 SnapMirror 관계 [%s]을(를) 업데이트하지 못했습니다. 오류 [%s]
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 02092
 a| 
[%s] 볼륨의 스냅샷 복사본을 나열하지 못했습니다. 오류 [%s]
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 02102
 a| 
[%s] 볼륨의 [%s] 스냅샷 복사본 이름을 [%s] 에서 [%s](으)로 바꾸지 못했습니다. 오류 [%s]
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
보관 - 02112
 a| 
오류 [%s](으)로 인해 컨트롤러 [%s]에서 SnapVault 상태를 검색하지 못했습니다.
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
보관 - 02115
 a| 
오류 [%s](으)로 인해 컨트롤러 [%s]에서 SnapVault 관계를 검색하지 못했습니다.
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 02122
 a| 
스냅샷 복사본 [%s]을(를) 기반으로 SnapVault 관계 [%s]을(를) 업데이트하지 못했습니다. 오류 [%s]
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 02132
 a| 
[%s] 볼륨을 기반으로 클론 생성된 볼륨을 나열하지 못했습니다. 오류 [%s]
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 02142
 a| 
[%s] 볼륨을 삭제하지 못했습니다. 오류: [%s]
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 02152
 a| 
[%s] 오류로 인해 볼륨을 나열하지 못했습니다.
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 02155
 a| 
[%s] 볼륨을 나열하지 못했습니다. 오류 메시지 [%s]
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 02162
 a| 
[%s] 볼륨의 스냅샷 복사본 [%s]을(를) 복원하지 못했습니다. 오류: [%s]
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 03001
 a| 
Clustered ONTAP 노드 [%s]에서 vserver 검색 중
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 05003
 a| 
오류 [%s](으)로 인해 NetApp 관리 콘솔 데이터세트 [%s]을(를) 생성하지 못했습니다.
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 05006
 a| 
스토리지 컨트롤러 [%s]에서 데이터 세트 [%s]의 NetApp 관리 콘솔 기반 백업을 생성하지 못했습니다. 오류 [%s]
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 05009
 a| 
오류 [%s](으)로 인해 데이터세트 [%s]에 대한 NetApp 관리 콘솔 데이터세트 상태를 검색하지 못했습니다.
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 05012
 a| 
오류 [%s](으)로 인해 NetApp 관리 콘솔 데이터 세트 [%s]의 검증에 실패했습니다.
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 05018
 a| 
[%s]에 OM 이벤트 [%s] 생성 중
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 03002
 a| 
오류 [%s](으)로 인해 LUN [%s]의 매핑 igroup [%s]이(가) 실패했습니다.
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 03005
 a| 
[%s] 볼륨의 [%s] LUN을 만들지 못했습니다. 오류: [%s]
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 03008
 a| 
볼륨 [%s]에 대한 기본 SnapVault 스냅샷 복사본 [%s]을(를) 생성하지 못했습니다. 오류 [%s]
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
보관 - 03011
 a| 
[%s] 데이터 세트에 대한 NetApp 관리 콘솔 백업 복사본을 나열하지 못했습니다. 오류: [%s]
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 03014
 a| 
오류 [%s](으)로 인해 NetApp 관리 콘솔 백업 버전 ID [%s]을(를) 삭제하지 못했습니다.
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 03019
 a| 
[%s]([%s])에 대한 NetApp 관리 콘솔 백업을 시작하지 못했습니다. 종료합니다.
 a| 
로그에 오류가 있는지 확인하십시오. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 03022
 a| 
작업 ID [%s]에 대한 NetApp 관리 콘솔 백업 진행 시작이 실패했습니다. 종료합니다.
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 03025
 a| 
[%s] 경로에서 파일을 삭제하지 못했습니다. 오류: [%s]
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지-03030
 a| 
[%s]에서 clustered Data ONTAP 노드를 검색하지 못했습니다
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 03033
 a| 
[%s]의 시스템 버전 세부 정보를 가져오는 데 실패했습니다. 오류 [%s]
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 03036
 a| 
[%s] 경로에 디렉토리를 생성하지 못했습니다. 오류: [%s]
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 03039
 a| 
[%s] 경로에서 디렉토리를 삭제하지 못했습니다. 오류: [%s]
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 03043
 a| 
경로 [%s]에 파일 생성이 실패했습니다. 오류 [%s]
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
보관 - 03046
 a| 
데이터 세트 [%s]에 대한 NetApp 관리 콘솔 데이터 세트를 수정하지 못했습니다.
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 03049
 a| 
파일 [%s]의 파일 내용을 읽을 수 없습니다
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 03052
 a| 
[%s] 옵션에 대한 옵션을 가져오지 못했습니다
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
보관 - 03055
 a| 
개체 [%s]에 대한 성능 카운터를 가져오지 못했습니다
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 03058
 a| 
객체 [%s]에 대한 성능 인스턴스 가져오기에 실패했습니다
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
보관 - 03061
 a| 
[%s]에 대한 NetApp 관리 콘솔 데이터 세트 정보가 실패했습니다
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 03064
 a| 
시스템 CLI 명령 [%s]에 실패했습니다
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 03067
 a| 
오류 [%s](으)로 인해 NetApp 관리 콘솔 데이터세트 [%s]을(를) 삭제하지 못했습니다.
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 03070
 a| 
스냅샷 복사본 [%s]을(를) 기반으로 SnapVault 관계 [%s]을(를) 복원하지 못했습니다. 오류 [%s]
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 03073
 a| 
[%s]:[%s]에 대한 CIFS 내보내기에 실패했습니다!
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
보관 - 03076
 a| 
오류 [%s](으)로 인해 컨트롤러 [%s]의 루트 볼륨을 가져오지 못했습니다.
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
보관 - 03079
 a| 
볼륨 [%s]에 대한 접합 경로 가져오기에 실패했습니다
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
보관 - 03082
 a| 
시스템 이름을 가져오지 못했습니다
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
스토리지 - 03085
 a| 
컨트롤러 [%s]에서 NFS 서비스를 가져오지 못했습니다
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
보관 - 03088
 a| 
호스트 [%s] 경로 이름 [%s] 권한 [%s]에 대한 NFS 권한 검사에 실패했습니다
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
보관 - 03091
 a| 
컨트롤러 [%s]에서 네트워크 인터페이스를 가져오지 못했습니다
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
보관 - 03094
 a| 
볼륨 [%s]의 qtree 목록에 실패했습니다
 a| 
로그에서 오류를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.

|===