---
permalink: administration/reference_parameters_to_set_up_netapp_management_console_data_protection_capability.html 
sidebar: sidebar 
keywords: parameter, netapp, management, console, protection, capability, ntap, update, set, backup, format 
summary: NetApp Management Console 데이터 보호 기능을 설정하려면 여러 매개 변수가 필요합니다. 
---
= NetApp Management Console 데이터 보호 기능을 설정하는 데 필요한 매개 변수입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Management Console 데이터 보호 기능을 설정하려면 여러 매개 변수가 필요합니다.

|===
| 매개 변수 | 설정 | 설명 


 a| 
NTAP_PM_update
 a| 
(예|아니오)
 a| 
NetApp Management Console 데이터 보호 기능에 Snap Creator Snapshot 복사본을 등록하는 NetApp Management Console 데이터 보호 기능 업데이트를 설정 및 해제할 수 있습니다. * 참고: * NTAP_PM_update가 활성화된 경우 NTAP_DFM_DATA_SET을 구성해야 합니다.



 a| 
NTAP_DFM_DATA_SET
 a| 
 a| 
에는 스토리지 시스템과 NetApp Management Console 데이터 보호 기능 데이터 세트가 볼륨 상관관계에 대해 정리되어 있습니다. 즉, 컨트롤러 1은 dataSet1/vol1, vol2, 컨트롤러 1은 dataet2/vol3입니다.



 a| 
NTAP_PM_run_backup
 a| 
(예|아니오)
 a| 
NetApp Management Console 데이터 보호 기능 백업을 시작하고 진행 상황과 상태를 확인한 후 완료될 때까지 기다립니다.



 a| 
NTAP_DFM_SNSHOT_FORMAT
 a| 
 a| 
NetApp Management Console의 데이터 보호 기능을 사용할 때 보조 스냅샷 복사본의 형식을 지정하는 선택적 설정입니다. 이 옵션을 사용하려면 OnCommand 5.0 이상 버전이 필요합니다. 필수 변수:

* 타임스탬프: %T


선택적 변수:

* 보존 유형: %R
* 데이터셋 레이블: %L
* 저장 컨트롤러: %H
* 볼륨 이름: %N
* 응용 프로그램별 데이터: %A


이 옵션을 설정하지 않으면 NetApp 관리 콘솔 데이터 보호 기능에 대한 기본 명명 규칙이 사용됩니다. 명명 규칙은 데이터셋 생성 시에만 설정할 수 있습니다.

|===