---
permalink: administration/reference_repository_error_messages.html 
sidebar: sidebar 
keywords: table, repository, error, message, global, configuration, repo 
summary: 다음 표에는 리포지토리 오류 메시지가 나열되어 있습니다. 
---
= 리포지토리 오류 메시지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다음 표에는 리포지토리 오류 메시지가 나열되어 있습니다.

|===
| 오류 코드 | 오류 메시지 | 설명/해상도 


 a| 
01001)을 참조하십시오
 a| 
글로벌 구성이 없습니다
 a| 
configs 폴더에 global.conf 파일이 있는지 확인합니다.



 a| 
01002로 재포하십시오
 a| 
글로벌 구성이 이미 있습니다
 a| 
global.conf 파일이 configs 폴더에 이미 있습니다. 먼저 글로벌 구성 파일을 삭제하거나 기존 파일을 업데이트합니다.



 a| 
01103)
 a| 
오류 [%s](으)로 인해 글로벌 구성을 생성하지 못했습니다.
 a| 
configs 폴더에 global.conf 파일을 생성하지 못했습니다. Snap Creator를 실행하는 사용자의 권한을 디렉토리에 대해 확인하십시오.



 a| 
01203으로 재포하십시오
 a| 
오류 [%s](으)로 인해 글로벌 구성을 업데이트하지 못했습니다.
 a| 
configs 폴더에서 global.conf 파일을 업데이트하지 못했습니다. Snap Creator를 실행하는 사용자의 권한을 디렉토리에 대해 확인하십시오.



 a| 
01303으로 문의하십시오
 a| 
[%s] 오류로 인해 글로벌 구성을 제거하지 못했습니다.
 a| 
configs 폴더에서 global.conf 파일을 제거하지 못했습니다. 파일이 configs 폴더에 있는지 확인하거나 Snap Creator를 실행하는 사용자의 권한을 디렉토리에 대해 확인합니다



 a| 
01403)을 참조하십시오
 a| 
오류 [%s](으)로 인해 글로벌 구성을 내보내지 못했습니다.
 a| 
configs 폴더에서 global.conf 파일을 읽지 못했습니다. 글로벌 구성 파일이 삭제되었는지 확인합니다.



 a| 
01503번)
 a| 
오류 [%s](으)로 인해 전역 설정 [%s]을(를) 가져오지 못했습니다.
 a| 
configs 폴더에서 global.conf 파일을 업데이트하지 못했습니다. Snap Creator를 실행하는 사용자의 권한을 디렉토리에 대해 확인하십시오.



 a| 
01603)을 참조하십시오
 a| 
오류 [%s](으)로 인해 글로벌 구성을 검색하지 못했습니다.
 a| 
configs 폴더에서 global.conf 파일을 읽지 못했습니다. 글로벌 구성 파일이 삭제되었는지 확인합니다.



 a| 
2002년 5월 6일
 a| 
프로파일 [%s]이(가) 이미 있습니다. 다른 이름을 사용하십시오.
 a| 
같은 이름의 프로파일이 이미 있습니다. 프로파일이 표시되지 않으면 사용자에게 이 프로파일에 대한 권한이 없는 것입니다.



 a| 
2003년 5월 6일
 a| 
프로필 [%s]이(가) 없습니다
 a| 
프로필 이름이 바뀌거나 삭제되었는지 확인합니다. 또한 사용자에게 이 프로필에 대한 권한이 없을 수도 있습니다.



 a| 
o-02103으로 이동합니다
 a| 
오류 [%s](으)로 인해 글로벌 프로파일 구성 [%s]을(를) 만들지 못했습니다.
 a| 
프로필에 global.conf 파일을 만들지 못했습니다. Snap Creator를 실행하는 사용자의 권한을 디렉토리에 대해 확인하십시오.



 a| 
o-02106을 참조하십시오
 a| 
프로필 구성 [%s]을(를) 만들지 못했습니다. 오류 [%s]
 a| 
configs 폴더에서 프로필을 생성하지 못했습니다. Snap Creator를 실행하는 사용자의 권한을 디렉토리에 대해 확인하십시오.



 a| 
2002203으로 재포하십시오
 a| 
프로필 구성 [%s]을(를) 업데이트하지 못했습니다. 오류 [%s]
 a| 
configs 폴더에서 프로필을 업데이트하지 못했습니다. Snap Creator를 실행하는 사용자의 권한을 디렉토리에 대해 확인하십시오.



 a| 
02213으로 다시 이동합니다
 a| 
[%s] 프로파일을 [%s](으)로 이름을 바꾸지 못했습니다. 오류 [%s]
 a| 
configs 폴더에서 프로파일의 이름을 바꾸지 못했습니다. Snap Creator를 실행하는 사용자의 권한을 디렉토리에 대해 확인하거나 프로파일 이름이 이미 변경되었거나 삭제되었는지 확인하십시오.



 a| 
302로 재포하십시오
 a| 
프로파일 구성 [%s]을(를) 제거하지 못했습니다
 a| 



 a| 
02403)을 참조하십시오
 a| 
프로필 구성 [%s]을(를) 내보내지 못했습니다. 오류 [%s]
 a| 



 a| 
02503)을 참조하십시오
 a| 
프로파일 구성 [%s]을(를) 가져오지 못했습니다. 오류 [%s]
 a| 



 a| 
repo-02603
 a| 
오류 [%s](으)로 인해 글로벌 프로필을 검색하지 못했습니다.
 a| 



 a| 
o-02606)을 참조하십시오
 a| 
[%s] 프로필을 검색하지 못하여 오류 [%s] 발생
 a| 



 a| 
02703)을 참조하십시오
 a| 
[%s] 오류로 인해 프로필을 나열하지 못했습니다.
 a| 
프로필을 나열하지 못했습니다. configs 폴더 경로를 확인합니다.



 a| 
03002로 재포하십시오
 a| 
프로파일 [%s]에 대한 구성 [%s]이(가) 이미 있습니다.
 a| 
지정한 프로파일에 대해 동일한 이름의 구성 파일이 이미 있습니다. 다른 이름을 선택하십시오.



 a| 
03103으로 이동합니다
 a| 
프로파일 [%s]에 대한 구성 [%s]을(를) 만드는 데 실패했습니다. 오류 [%s]
 a| 



 a| 
03203으로 이동합니다
 a| 
프로필 [%s]에 대한 구성 [%s]을(를) 업데이트하지 못했습니다. 오류 [%s]
 a| 



 a| 
03212로 재포하십시오
 a| 
프로파일 [%s]의 설정 [%s]을(를) [%s](으)로 이름을 바꾸지 못했습니다
 a| 
프로파일에서 설정 이름을 바꾸지 못했습니다. 구성 이름이 바뀌거나 삭제되었는지 확인하고 Snap Creator를 실행하는 사용자의 권한을 디렉토리에 대해 확인합니다.



 a| 
03303으로 재포하십시오
 a| 
프로파일 [%s]에서 구성 [%s]을(를) 제거하지 못했습니다
 a| 
configs 폴더의 프로필에서 구성을 삭제하지 못했습니다. Snap Creator를 실행하는 사용자의 권한을 디렉토리에 대해 확인하십시오.



 a| 
03403으로 이동합니다
 a| 
프로파일 [%s]에 대한 구성 [%s]을(를) 내보내지 못했습니다. 오류 [%s]
 a| 



 a| 
503)
 a| 
구성 [%s]을(를) 프로파일 [%s]에 가져오지 못했습니다. 오류 [%s]
 a| 



 a| 
03603)을 참조하십시오
 a| 
프로파일 [%s]에서 구성 [%s]을(를) 검색하지 못했습니다. 오류 [%s]
 a| 



 a| 
03703으로 다시 이동합니다
 a| 
프로파일 [%s]의 설정을 나열하지 못했습니다. 오류 [%s]
 a| 



 a| 
repo-04003
 a| 
프로필 [%s], 구성 [%s] 및 타임스탬프 [%s]에 대한 카탈로그를 읽는 데 실패했습니다. 오류 [%s]
 a| 



 a| 
04103)을 참조하십시오
 a| 
프로필 [%s], 구성 [%s] 및 타임스탬프 [%s]에 대한 카탈로그를 쓰는 데 실패했습니다. 오류 [%s]
 a| 



 a| 
04203)를 참조하십시오
 a| 
프로필 [%s], 구성 [%s] 및 타임스탬프 [%s]에 대한 카탈로그를 지우는 중 오류가 발생하여 실패했습니다. [%s]
 a| 



 a| 
04303으로 재포하십시오
 a| 
프로필 [%s] 및 구성 [%s]에 대한 인벤토리 카탈로그 실패, 오류 [%s]
 a| 



 a| 
04304를 참조하십시오
 a| 
구성 [%s]이(가) 없습니다
 a| 



 a| 
04309를 참조하십시오
 a| 
정책 개체를 추가하지 못했습니다. [%s]
 a| 
데이터베이스 오류. 자세한 내용은 스택 추적을 확인하십시오.



 a| 
repo-04313
 a| 
정책 ID: %s에 대한 정책 개체를 제거하지 못했습니다
 a| 
데이터베이스 오류. 자세한 내용은 스택 추적을 확인하십시오.



 a| 
415315를 참조하십시오
 a| 
정책 개체를 업데이트하지 못했습니다: %s
 a| 
데이터베이스 오류. 자세한 내용은 스택 추적을 확인하십시오.



 a| 
04316 으로 이동합니다
 a| 
정책을 나열하지 못했습니다
 a| 
데이터베이스 오류. 자세한 내용은 스택 추적을 확인하십시오.



 a| 
4월 321로 재포하십시오
 a| 
백업 유형 객체를 추가하지 못했습니다[%s]
 a| 
데이터베이스 오류. 자세한 내용은 스택 추적을 확인하십시오.



 a| 
04323으로 재포하십시오
 a| 
백업 유형 ID: %s에 대한 백업 유형 항목이 없습니다
 a| 
유효한 백업 유형을 전달합니다.



 a| 
325)를 참조하십시오
 a| 
백업 유형 ID: %s에 대한 백업 유형 객체를 제거하지 못했습니다
 a| 
데이터베이스 오류. 자세한 내용은 스택 추적을 확인하십시오.



 a| 
04327)을 참조하십시오
 a| 
백업 유형 객체를 업데이트하지 못했습니다: %s
 a| 
데이터베이스 오류. 자세한 내용은 스택 추적을 확인하십시오.



 a| 
04328로 재포하십시오
 a| 
백업 유형을 나열하지 못했습니다
 a| 
데이터베이스 오류. 자세한 내용은 스택 추적을 확인하십시오.



 a| 
po-04333을 참조하십시오
 a| 
스케줄러 작업 객체를 추가하지 못했습니다. [%s]
 a| 
데이터베이스 오류. 자세한 내용은 스택 추적을 확인하십시오.



 a| 
04335)를 참조하십시오
 a| 
작업 ID: %s에 대한 스케줄러 작업 항목이 없습니다
 a| 
유효한 스케줄러 작업을 전달합니다.



 a| 
04337로 재포하십시오
 a| 
작업 ID: %s에 대한 스케줄러 작업 객체를 제거하지 못했습니다
 a| 
데이터베이스 오류. 자세한 내용은 스택 추적을 확인하십시오.



 a| 
04339)를 참조하십시오
 a| 
스케줄러 작업 객체를 업데이트하지 못했습니다: %s
 a| 
데이터베이스 오류. 자세한 내용은 스택 추적을 확인하십시오.



 a| 
3440)을 참조하십시오
 a| 
스케줄러 작업을 나열하지 못했습니다
 a| 
데이터베이스 오류. 자세한 내용은 스택 추적을 확인하십시오.



 a| 
po-04341
 a| 
정책 개체를 추가하지 못했습니다. 동일한 이름의 정책 [%s]이(가) 이미 있습니다
 a| 
같은 이름의 정책이 이미 있습니다. 다른 이름으로 시도하십시오.



 a| 
04342)를 참조하십시오
 a| 
백업 유형 객체를 추가하지 못했습니다. 이름이 같은 백업 유형 [%s]이(가) 이미 있습니다
 a| 
같은 이름의 백업 유형이 이미 있습니다. 다른 이름으로 시도하십시오.



 a| 
04343으로 전화하십시오
 a| 
스케줄러 객체를 추가하지 못했습니다. 동일한 작업 이름을 가진 스케줄러 [%s]이(가) 이미 있습니다
 a| 



 a| 
04344를 참조하십시오
 a| 
프로파일 [%s]을(를) 업데이트하지 못했습니다. 프로필이 비어 있습니다.
 a| 



 a| 
주소 - 04345
 a| 
새 정책을 추가하는 동안 정책 유형은 null일 수 없습니다
 a| 



 a| 
04346으로 이동합니다
 a| 
스토리지 객체는 null일 수 없습니다
 a| 



 a| 
4월 347로 이동합니다
 a| 
스토리지 객체를 추가하지 못했습니다. 동일한 이름/IP를 가진 스토리지 [%s]이(가) 이미 있습니다
 a| 



 a| 
04348로 재포하십시오
 a| 
저장소 세부 정보를 가져오지 못했습니다. 데이터베이스 오류!
 a| 



 a| 
04349로 재포하십시오
 a| 
호스트 이름이 잘못되었습니다. 호스트 이름 /IP [%s]의 스토리지가 없습니다
 a| 



 a| 
04350)로 전화 주십시오
 a| 
호스트 이름은 null일 수 없습니다
 a| 
호스트 이름이 잘못되었습니다



 a| 
반포 04351
 a| 
[%s] 저장소를 삭제하지 못했습니다. 오류: [%s]
 a| 
저장소를 삭제하지 못했습니다. 데이터베이스 오류!



 a| 
4월 355를 참조하십시오
 a| 
[%s] 저장소를 업데이트하지 못했습니다. 오류: [%s]
 a| 
저장소를 업데이트하지 못했습니다. 데이터베이스 오류!



 a| 
4월 356번
 a| 
클러스터 객체는 null일 수 없습니다
 a| 



 a| 
4월 358로 문의하십시오
 a| 
[%s] 저장소를 추가하지 못했습니다. 오류: [%s]
 a| 



 a| 
04359를 참조하십시오
 a| 
[%s] 오류로 인해 [%s] 클러스터를 업데이트하지 못했습니다.
 a| 



 a| 
04360
 a| 
클러스터 객체를 추가하지 못했습니다. 동일한 이름/IP를 가진 [%s] 클러스터가 이미 있습니다
 a| 
동일한 호스트 이름의 클러스터가 이미 있습니다

|===