---
permalink: administration/reference_snap_creator_terminology.html 
sidebar: sidebar 
keywords: snap, creator, terminology,action, backup, lun, clone, volume, agent, monitor, archive, log, configuration, discover, global, job, mount, ossv, profile, policy, quiesce, restore, scdump, schedule, umount, unquiesce, watchdog 
summary: Snap Creator는 몇 가지 서로 다른 구문으로 구성되어 있으며 언어와 개념을 이해하는 것이 중요합니다. 
---
= Snap Creator 용어
:icons: font
:imagesdir: ../media/


[role="lead"]
Snap Creator는 몇 가지 서로 다른 구문으로 구성되어 있으며 언어와 개념을 이해하는 것이 중요합니다.

* * 작업 *
+
Snap Creator는 구성 파일에 대해 다양한 작업을 수행할 수 있습니다. 이것은 일반적으로 원하는 결과를 얻기 위해 정의된 워크플로입니다. 작업을 실행하려면 GUI에서 구성 파일을 선택하고 * 작업 * 을 클릭한 후 드롭다운 목록에서 다음 작업 중 하나를 선택합니다.

+
** * 백업 *
+
구성 파일에 지정된 환경을 백업합니다. 백업 워크플로는 선택한 구성 파일의 설정에 따라 변경되는 다단계 작업입니다. 플러그인이 구성된 백업 작업의 예로는 애플리케이션 또는 데이터베이스 중지, 정의된 모든 볼륨의 스냅샷 복사본 생성, 선택한 애플리케이션 또는 데이터베이스 중지 해제, SnapVault 및/또는 SnapMirror 업데이트 수행, 보존 정책 작업, 아카이브 로그 설정 작업 등이 있습니다.

** * LUN 클론 *
+
LUN의 새 스냅샷 복사본을 생성하고 새 스냅샷 복사본을 클론 복제합니다.

** * 볼륨 클론 *
+
볼륨의 새 스냅샷 복사본을 생성하고 새 스냅샷 복사본을 클론 복제합니다.



* * 상담원 모니터 *
+
Agent Monitor는 구성 파일에 정의된 모든 에이전트를 Snap Creator Server에 쿼리하고 해당 상태를 확인하도록 에이전트를 쿼리합니다. 에이전트 모니터는 에이전트가 실행 중인지 여부, 상담원이 수신 대기 중인 포트 및 사용 중인 에이전트 버전을 보고합니다.

* * 아카이브 로그 *
+
아카이브 로그 작업은 구성 파일의 아카이브 로그 관리 설정에 있는 모든 설정에 대해 작동합니다. 이 작업은 일반적으로 Snap Creator에서 더 이상 필요하지 않은 로그를 지웁니다.

* * 구성 파일 *
+
구성 파일은 Snap Creator의 핵심입니다. Snap Creator를 구성하고, 애플리케이션 플러그인이 실행될 수 있도록 하며, 필요한 변수를 설정하고, 스냅샷 복사본에 캡처된 볼륨을 정의합니다. 구성 파일은 Snap Creator의 동작에 영향을 주기 위해 설정할 수 있는 다양한 매개 변수로 구성됩니다. 구성 파일은 종종 구성 또는 구성으로 단축됩니다.

* * 발견 *
+
검색 작업은 구성 파일에 자세히 설명된 환경에서 스토리지 레벨 검색을 수행합니다. 모든 플러그인이 검색을 지원하는 것은 아닙니다.

* * 글로벌 구성 파일 *
+
슈퍼 글로벌 수준(매개 변수는 전체 Snap Creator Server 환경의 모든 구성 파일에 영향을 줌) 또는 프로파일 수준(매개 변수는 지정된 프로필의 모든 구성 파일에 영향을 줌)에서 작동할 수 있는 구성 파일입니다. Superglobal 매개변수는 프로파일 수준 글로벌에 지정된 매개 변수로 재정의됩니다. 마찬가지로, 구성 파일에 지정된 매개 변수는 수퍼 또는 프로파일 수준 글로벌 구성 파일의 모든 매개 변수를 재정의합니다. 글로벌 구성 파일은 종종 전역 구성으로 단축됩니다.

* * 작업 *
+
Snap Creator에서 수행하는 모든 작업은 작업으로 간주됩니다. 일부 작업은 여러 작업으로 구성될 수 있습니다. Snap Creator에서 실행된 모든 작업이 Job Monitor에 나열됩니다.

* * 작업 모니터 *
+
작업 모니터는 사용하기 쉬운 대시보드 인터페이스로, 이전에 실행 중이거나 실행된 Snap Creator 작업의 상태를 간단히 확인할 수 있습니다. 작업 모니터는 설정 시 활성화되며 1에서 1,000개의 작업을 저장할 수 있습니다.

* * 마운트 *
+
마운트 작업을 통해 클론 복제 및 마운트할 기존 스냅샷 복사본을 지정할 수 있습니다.

* OSSV * 입니다
+
OSSV(Open Systems SnapVault) 작업은 OSSV 작업을 수행합니다.

* * 프로파일 *
+
프로필은 기본적으로 구성 파일을 구성하는 데 사용되는 폴더입니다. 프로파일은 역할 기반 액세스 제어(RBAC)의 객체 역할도 합니다. 즉, 특정 프로파일 및 에 포함된 구성 파일에 대한 액세스를 허용할 수 있습니다.

* * 정책 *
+
보존 정책에 대한 정책이 짧습니다. 일반적으로 정책은 스냅샷 보존 정책(유지할 스냅샷 복사본 수) 및 보존 기간(스냅샷 복사본을 삭제하기 전에 보관할 기간)을 정의합니다. 예를 들어, 일별 정책은 30일 이상 경과해야 하는 Snapshot 복사본의 30일을 ``가치 있는’’로 유지할 수 있습니다. 보존 기간 설정을 사용하면 같은 날짜에 여러 스냅샷 복사본이 생성된 후 스냅샷 복사본이 30일이 경과해야 한다고 SLA를 우회하지 못하게 됩니다. SnapVault를 사용하는 경우 이 정책은 SnapVault 복제본에 대한 보존 설정도 정의합니다. 현재 정책은 구성 파일에 직접 저장하거나 정책 개체의 일부로 저장할 수 있습니다. 정책이 구성 파일의 일부인 경우 로컬 보존 정책이라고 할 수 있습니다.

* * 정책 개체 *
+
정책 객체는 프로필 레벨에서 적용할 수 있는 보존 정책입니다. 정책과 마찬가지로 정책 개체는 보존 정책을 정의하지만 스케줄과 레이블을 정의할 수도 있습니다. 다음은 정책 개체의 구성 요소입니다.

+
** * 백업 유형 *
+
백업 유형은 정책 개체에서 설정할 수 있는 레이블입니다.

** * 정책 할당 *
+
정책 할당은 정책 관리에서 생성된 정책을 프로필의 특정 프로필에 할당합니다.

** * 정책 관리 *
+
정책 관리는 정책 개체 내에 정책을 만듭니다. 이를 통해 스냅샷 복사본의 보존 수와 기간을 정의할 수 있습니다. SnapVault를 사용하는 경우 연관된 보존 수 및 기간을 설정할 수도 있습니다. 정책 관리를 통해 선택 사항으로 정책 일정 및 백업 유형을 선택할 수도 있습니다.

** * 정책 일정 *
+
정책 스케줄은 지정된 스케줄에 수행할 작업을 정의합니다.



* * 정지 *
+
일시 중지 작업은 응용 프로그램 또는 데이터베이스를 정합성 보장 상태로 전환하는 데 필요한 작업을 수행합니다. 작업의 이름이 quiesce인 경우에도 플러그인 또는 구성 파일 설정에 따라 실제 중지 작업이 아닐 수 있습니다. 예를 들어 Domino 플러그인은 Domino API 호출을 수행하여 Domino 데이터베이스를 백업 시작 상태로 전환하는 반면, DB2 플러그인은 DB2 쓰기 일시 중지 명령을 수행합니다.

* * 복원 *
+
복구 작업은 구성 파일에 지정된 하나 이상의 볼륨에 대해 볼륨 또는 단일 파일 복원 작업을 수행합니다. 구성 파일에 사용된 플러그인에 따라 추가 복원 작업을 사용할 수 있습니다.

* scdump *
+
scdump는 프로파일 수준에서 모든 구성 파일 및 로그 파일을 수집하고 일부 표준 Snap Creator Server 로그 및 환경 정보를 수집하는 문제 해결 작업입니다. 수집된 모든 파일은 zip 파일로 압축되며, 이 파일은 다운로드하라는 메시지가 표시됩니다. 그런 다음 scdump zip 파일을 이메일로 보내거나 Support에 업로드하여 분석할 수 있습니다.

* * 스케줄 *
+
Snap Creator Server에는 중앙 집중식 스케줄러가 포함되어 있습니다. 따라서 정책 일정(정책 개체의 일부)을 통해 또는 스케줄러를 통해 직접 생성된 Snap Creator 작업을 예약할 수 있습니다. 스케줄러는 최대 10개의 작업을 동시에 실행하고 실행 중인 작업이 완료될 때까지 추가 작업을 대기열에 저장합니다.

* Snap Creator 에이전트 *
+
Snap Creator Agent는 일반적으로 애플리케이션 또는 데이터베이스가 설치된 동일한 호스트에 설치됩니다. Agent는 플러그인이 있는 위치입니다. 때때로 Snap Creator 내에서 Agent가 scAgent로 짧아집니다.

* Snap Creator 프레임워크 *
+
Snap Creator는 프레임워크이며, 완벽한 제품 이름은 NetApp Snap Creator Framework입니다.

* Snap Creator 플러그인 *
+
플러그인은 애플리케이션 또는 데이터베이스를 일관된 상태로 전환하는 데 사용됩니다. Snap Creator에는 이미 바이너리 파일의 일부이며 추가 설치가 필요하지 않은 여러 플러그인이 포함되어 있습니다.

* Snap Creator 서버 *
+
Snap Creator Server는 일반적으로 물리적 호스트 또는 가상 호스트에 설치됩니다. 서버는 Snap Creator GUI와 작업, 일정, 사용자, 역할, 프로필 및 구성 파일 및 플러그인의 메타데이터 때때로 서버는 Snap Creator 내에서 scServer로 축소됩니다.

* * umount *
+
마운트 해제 작업을 사용하면 마운트 해제할 기존 마운트 지점을 지정할 수 있습니다.

* * 정지 해제 *
+
일시 중지 해제 작업은 응용 프로그램이나 데이터베이스를 정상 작동 모드로 되돌리는 데 필요한 작업을 수행합니다. 작업의 이름이 Unquiesce인 경우에도 플러그인 또는 구성 파일 설정에 따라 이 작업은 실제 일시 중지 해제 작업이 아닐 수 있습니다. 예를 들어 Domino 플러그인은 Domino API 호출을 수행하여 Domino 데이터베이스를 백업 중지 상태로 전환하는 반면 DB2 플러그인은 쓰기 재개 명령을 수행합니다.

* * 감시장치 *
+
감시장치는 에이전트가 실행 중인 작업의 상태를 모니터링하는 Snap Creator Agent의 일부입니다. 지정된 시간 내에 Agent가 응답하지 않으면 감시장치가 Agent를 다시 시작하거나 특정 작업을 종료할 수 있습니다. 예를 들어 중지 작업이 시간 초과 값을 초과하면 감시장치가 일시 중지 작업을 중지하고 일시 중지 해제를 시작하여 데이터베이스를 다시 정상 작동 모드로 되돌릴 수 있습니다.


