---
permalink: administration/reference_snap_creator_framework_error_messages.html 
sidebar: sidebar 
keywords: snap, creator, framework, error, message, troubleshoot, issue, scf, serial, number, plug-in, snapcreator, application 
summary: Snap Creator 프레임워크 오류 메시지는 발생한 문제를 해결하는 데 도움이 될 수 있습니다. 
---
= Snap Creator 프레임워크 오류 메시지
:icons: font
:imagesdir: ../media/


[role="lead"]
Snap Creator 프레임워크 오류 메시지는 발생한 문제를 해결하는 데 도움이 될 수 있습니다.

|===
| 오류 코드 | 오류 메시지 | 설명/해상도 


 a| 
SCF-00001
 a| 
일련 번호 [%s]을(를) 가져올 수 없습니다.
 a| 
Snap Creator 설정 명령이 실행되지 않습니다. snapcreator--profile setup 명령을 실행합니다. 일련 번호가 비어 있거나 숫자 값으로 설정되어 있는지 확인합니다.



 a| 
SCF-00002
 a| 
[%s] 오류 및 종료 코드 [%s] 오류로 인해 플러그인 [%s]의 백업 처리가 실패했습니다. 종료합니다.
 a| 
응용 프로그램 오류로 인해 응용 프로그램 백업이 실패했습니다. 로그 및 응용 프로그램 설정을 확인합니다.



 a| 
SCF-00003
 a| 
[%s] 오류 및 종료 코드 [%s] 오류로 인해 플러그인 [%s]의 백업 정리 처리가 실패했습니다. 종료합니다.
 a| 
응용 프로그램 오류로 인해 응용 프로그램 백업 정리에 실패했습니다. 로그 및 응용 프로그램 설정을 확인합니다.



 a| 
SCF-00004
 a| 
플러그인 [%s]의 클론 처리에 실패했습니다. 오류 [%s] 및 종료 코드 [%s], 종료!
 a| 
응용 프로그램 오류로 인해 응용 프로그램 복제에 실패했습니다. 로그 및 응용 프로그램 설정을 확인합니다.



 a| 
SCF-00005
 a| 
플러그인 [%s]의 클론 정리 처리에 실패했습니다. 오류 [%s] 및 종료 코드 [%s], 종료!
 a| 
애플리케이션 오류로 인해 애플리케이션 클론 정리에 실패했습니다. 로그 및 응용 프로그램 설정을 확인합니다.



 a| 
SCF-00006
 a| 
[%s]의 사전 클론 처리에 실패했습니다. 오류 [%s] 및 종료 코드 [%s], 종료!
 a| 
애플리케이션 오류로 인해 애플리케이션 사전 클론 작업이 실패했습니다. 로그 및 응용 프로그램 설정을 확인합니다.



 a| 
SCF-00007
 a| 
플러그인 [%s]의 사후 클론 처리에 실패했습니다. 오류 [%s] 및 종료 코드 [%s], 종료!
 a| 
애플리케이션 오류로 인해 애플리케이션 사후 클론 작업이 실패했습니다. 로그 및 응용 프로그램 설정을 확인합니다.



 a| 
SCF-00008
 a| 
[%s]에서 [%s]의 클론 LUN igroup을 [%s]igroup에 매핑하지 못했습니다. 종료됩니다!
 a| 
LUN 클론에 대한 igroup 매핑에 실패했습니다. 오류 로그를 확인합니다. NetApp Manageability SDK 솔루션 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
SCF-00009
 a| 
종료 코드 [%s](으)로 인해 데이터세트 [%s]에 대한 NetApp 관리 콘솔 백업 목록 종료가 실패했습니다. 종료됩니다!
 a| 
Snap Creator가 NetApp Management Console에서 백업 삭제 작업을 시작했지만 스냅샷 복사본을 나열하지 못했습니다. Snap Creator가 백업을 등록하고 NTAP_PM_update 및 NTAP_DFM_DATA_SET 매개 변수의 구성을 확인합니다.



 a| 
SCF-00010
 a| 
NetApp Management Console 백업 목록이 정의되지 않았습니다. 데이터 세트 [%s]에 대한 백업이 없습니다. 종료합니다.
 a| 
Snap Creator가 NetApp Management Console에서 백업 삭제 작업을 시작했지만 스냅샷 복사본이 있습니다. Snap Creator가 백업을 등록하고 NTAP_PM_update 및 NTAP_DFM_DATA_SET 매개 변수의 구성을 확인합니다.



 a| 
SCF-00011
 a| 
종료 코드 [%s](으)로 인해 데이터세트 [%s]에 대한 NetApp 관리 콘솔 백업 버전 ID [%s] 타임스탬프 [%s] 삭제가 실패했습니다. 종료합니다.
 a| 
Snap Creator가 백업을 등록하고 NTAP_PM_update 및 NTAP_DFM_DATA_SET 매개 변수의 구성을 확인합니다.



 a| 
SCF-00012
 a| 
종료 코드 [%s](으)로 인해 데이터세트 [%s]에 대한 NetApp 관리 콘솔 데이터 세트 상태를 검색하지 못했습니다. 종료됩니다!
 a| 
데이터세트가 있고 상태가 규정을 준수하는지 확인합니다. 또한 Snap Creator에서 데이터 세트가 생성되었는지 확인합니다. Snap Creator에서 생성되지 않은 데이터 세트는 애플리케이션 데이터 세트가 아니며 이러한 데이터 세트는 작동하지 않습니다.



 a| 
SCF-00013
 a| 
데이터 세트 [%s] 종료 코드 [%s]에 스냅샷 복사본을 등록하지 못했습니다.
 a| 
NTAP_PM_update 및 NTAP_DFM_DATA_SET 매개 변수의 구성을 확인하십시오.



 a| 
SCF-00014
 a| 
[%s]([%s])에 대한 NetApp 관리 콘솔 백업을 시작하지 못했습니다. 종료합니다.
 a| 
NTAP_PM_update 및 NTAP_DFM_DATA_SET 매개 변수의 구성을 확인하십시오.



 a| 
SCF-00015
 a| 
작업 ID [%s]에 대한 NetApp 관리 콘솔 백업이 완료되었지만 오류가 발생했습니다 - [%s]
| [%s] 


| [%s] | [%s]  a| 
Snap Creator가 NetApp Management Console 백업을 시작했지만 백업 작업의 진행률을 가져오지 못했습니다. NTAP_PM_update 및 NTAP_DFM_DATA_SET 매개 변수의 구성을 확인하십시오.



 a| 
SCF-00016
 a| 
[%s]에 대한 SnapMirror 상태가 실패했습니다. 종료합니다.
 a| 
Snap Creator가 주어진 컨트롤러에 대한 SnapMirror 관계를 찾을 수 없습니다. 스토리지 컨트롤러에 로그인하고 SnapMirror 상태 명령을 실행하여 관계가 존재하는지 확인합니다.



 a| 
SCF-00017
 a| 
[%s]:[%s]에 대한 SnapMirror 관계가 없습니다. 종료합니다.
 a| 
Snap Creator가 주어진 컨트롤러 볼륨에 대한 SnapMirror 관계를 찾을 수 없습니다. 스토리지 컨트롤러에 로그인하고 SnapMirror 상태 명령을 실행한 다음 지정된 컨트롤러 이름에 대한 관계가 있는지 확인합니다. 다른 이름을 사용하는 경우 보조 _INTERFACESParameter를 구성하여 Snap Creator에 스토리지 컨트롤러에 매핑되는 것을 알려야 합니다.



 a| 
SCF-00018
 a| 
[%s]에 대한 SnapVault 상태 목록 실패, 종료!
 a| 
Snap Creator가 주어진 컨트롤러에 대한 SnapVault 관계를 찾을 수 없습니다. 스토리지 컨트롤러에 로그인하여 SnapVault status 명령을 실행하십시오. SnapVault 관계가 있는지 확인합니다.



 a| 
SCF-00019
 a| 
[%s]:[%s]에 대한 SnapVault 관계가 없습니다. 종료합니다.
 a| 
Snap Creator에서 SnapVault 관계를 찾을 수 없습니다. 스토리지 컨트롤러에 로그인하여 SnapVault status 명령을 실행하십시오. 지정된 컨트롤러 이름에 대한 SnapVault 관계가 있는지 확인합니다. 다른 이름을 사용하는 경우, 보조_인터페이스 매개 변수를 구성하여 Snap Creator에서 스토리지 컨트롤러에 매핑되는 것을 지정해야 합니다.



 a| 
SCF-00020
 a| 
원본 [%s]을(를) 사용하여 대상 [%s]에서 SnapVault 업데이트를 실행하지 못했습니다!
 a| 
Snap Creator가 SnapVault 업데이트를 시작할 수 없습니다. 스토리지 컨트롤러에 로그인하고 SnapVault status 명령을 실행합니다. 지정된 컨트롤러 이름에 대한 SnapVault 관계가 있는지 확인합니다. 다른 이름을 사용하는 경우, 보조_인터페이스 매개 변수를 구성하여 Snap Creator에서 스토리지 컨트롤러에 매핑되는 것을 지정해야 합니다.



 a| 
SCF-00021
 a| 
SnapMirror 전송 오류가 감지됨 - [%s], 종료 중!
 a| 
오류 및 스토리지 컨트롤러 설정에서 SnapMirror를 확인하십시오.



 a| 
SCF-00022
 a| 
[%s] 소스에 대한 SnapMirror 업데이트를 [%s]분 내에 완료하지 못했습니다. 종료됩니다!
 a| 
SnapMirror 업데이트가 구성된 대기 시간보다 오래 걸렸습니다. 구성 파일에서 ntap_nSnapMirror_wait 값을 늘려 대기 시간을 조정할 수 있습니다.



 a| 
SCF-00023
 a| 
[%s] 소스에 대한 SnapVault 업데이트를 [%s]분 내에 완료하지 못했습니다. 종료합니다.
 a| 
SnapVault 업데이트가 구성된 대기 시간보다 오래 걸렸습니다. 구성 파일에서 ntap_snapvault_wait 값을 늘려 대기 시간을 조정할 수 있습니다.



 a| 
SCF-00024
 a| 
SnapVault 전송 오류 감지됨 - [%s], 종료 중!
 a| 
SnapVault에 대한 오류 및 스토리지 컨트롤러 설정을 확인합니다.



 a| 
SCF-00025
 a| 
[%s] 오류 및 종료 코드 [%s](으)로 인해 플러그인 [%s]의 사후 복원 처리가 실패했습니다.
 a| 
응용 프로그램 오류로 인해 응용 프로그램 사후 복원 작업이 실패했습니다. 로그 및 응용 프로그램 설정을 확인합니다.



 a| 
SCF-00026
 a| 
[%s] 오류 및 종료 코드 [%s](으)로 인해 플러그인 [%s]의 복원 정리 처리가 실패했습니다.
 a| 
응용 프로그램 오류로 인해 응용 프로그램 복원 정리 작업이 실패했습니다. 로그 및 응용 프로그램 설정을 확인합니다.



 a| 
SCF-00027
 a| 
[%s] 오류 및 종료 코드 [%s](으)로 인해 플러그인 [%s]의 사전 복원 처리가 실패했습니다.
 a| 
응용 프로그램 오류로 인해 응용 프로그램 사전 복원 작업이 실패했습니다. 로그 및 응용 프로그램 설정을 확인합니다.



 a| 
SCF-00028
 a| 
플러그인 [%s]에 대한 자동 검색이 오류 [%s] 및 종료 코드 [%s](으)로 실패했습니다. 종료합니다!
 a| 
응용 프로그램 오류로 인해 응용 프로그램을 검색하지 못했습니다. 로그 및 응용 프로그램 설정을 확인합니다. 또한 app_Auto_discovery=N을 설정하고 validate_volumes에 주석을 달어 자동 검색을 비활성화할 수 있습니다.



 a| 
SCF-00029
 a| 
플러그인 [%s]에 대한 자동 검색이 실패했습니다. 환경이 비어 있습니다. 종료합니다.
 a| 
애플리케이션 플러그인은 자동 검색 사용을 지원하지 않습니다. APP_AUTO_DISCOVERY=N을 설정하여 자동 검색을 사용하지 않도록 설정합니다



 a| 
SCF-00030
 a| 
플러그인 [%s]에 대한 파일 시스템 정지 실패, 오류 [%s] 및 종료 코드 [%s], 종료!
 a| 
파일 시스템 오류로 인해 파일 시스템을 정지하지 못했습니다. 로그 및 파일 시스템 설정을 확인합니다. 오류를 무시하고 백업을 진행하려면 app_ignore_error=Y를 설정할 수 있습니다



 a| 
SCF-00031
 a| 
플러그인 [%s]에 대한 파일 시스템 정지 중 오류가 발생했습니다. 종료 코드 [%s], 백업을 계속 진행합니다!
 a| 
파일 시스템 오류로 인해 파일 시스템을 정지하지 못했습니다. 그러나 app_ignore_error=Y;Snap Creator가 백업을 진행합니다. 로그 및 파일 시스템 설정을 확인합니다.



 a| 
SCF-00032
 a| 
응용 프로그램 오류로 인해 응용 프로그램 중지 해제에 실패했습니다. 응용 프로그램 오류를 무시하고 백업을 진행하려면 app_ignore_error=Y를 설정할 수 있습니다
 a| 
로그 및 응용 프로그램 설정을 확인합니다.



 a| 
SCF-00033
 a| 
종료 코드 [%s](으)로 인해 플러그인 [%s]에 대한 응용 프로그램 중지 해제에 실패했습니다. 백업을 계속 진행하십시오!
 a| 
응용 프로그램 오류로 인해 응용 프로그램 중지 해제에 실패했습니다. 그러나 app_ignore_error=Y; Snap Creator는 백업을 진행합니다. 로그 및 응용 프로그램 설정을 확인합니다.



 a| 
SCF-00034
 a| 
[%s]의 [%s]에서 [%s]의 LUN 클론 생성에 실패했습니다: [%s]을(를) 종료하는 중입니다!
 a| 
LUN 클론을 생성하지 못했습니다. 오류 로그를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
SCF-00035
 a| 
[%s]의 LUN 인벤토리에 실패했습니다. 종료합니다.
 a| 
LUN 목록을 생성하지 못했습니다. 오류 로그를 확인합니다. NetApp 관리 효율 오류가 있을 수 있습니다. 로그에 문제의 원인이 드러날 수 있습니다.



 a| 
SCF-00036
 a| 
플러그인 [%s]에 대한 응용 프로그램 중지 실패, 플러그인에서 반환된 종료 코드가 없습니다. 종료합니다!
 a| 
종료 코드 없이 응용 프로그램 중기를 완료했습니다. 로그 및 응용 프로그램 설정을 확인합니다.



 a| 
SCF-00037
 a| 
[%s] 오류 및 종료 코드 [%s], 종료로 인해 플러그인 [%s]에 대한 응용 프로그램 중지 실패, 종료!
 a| 
응용 프로그램 오류로 인해 응용 프로그램을 정지하지 못했습니다. 로그 및 응용 프로그램 설정을 확인합니다. 응용 프로그램 오류를 무시하고 백업을 진행하려면 app_ignore_error=Y를 설정할 수 있습니다



 a| 
SCF-00038
 a| 
종료 코드 [%s](으)로 인해 플러그인 [%s]에 대한 응용 프로그램 중지 실패, 백업 계속.
 a| 
응용 프로그램 오류로 인해 응용 프로그램을 정지하지 못했습니다. 그러나 app_ignore_error=Y; Snap Creator는 백업을 진행합니다. 로그 및 응용 프로그램 설정을 확인합니다.



 a| 
SCF-00039
 a| 
지정한 컨트롤러 [%s]이(가) 구성에 지정된 컨트롤러와 일치하지 않습니다. 구성 파일에서 ntap_users 매개 변수를 확인하십시오.
 a| 
NTAP_users를 확인하고 스토리지 컨트롤러가 구성 파일에 정의되어 있는지 확인합니다.



 a| 
SCF-00040
 a| 
지정한 볼륨 [%s]이(가) 구성에 지정된 스토리지 시스템 또는 볼륨과 일치하지 않습니다. 구성 파일에서 volumes 매개 변수를 확인합니다.
 a| 
구성 파일에서 볼륨 설정을 확인하고 올바른 컨트롤러 볼륨이 구성되었는지 확인합니다.



 a| 
SCF-00041
 a| 
Clustered Data ONTAP이 감지되었지만 cmode_cluster_name이 올바르게 구성되지 않았습니다. 구성 매개 변수를 확인하십시오. 종료합니다.
 a| 
cmode_cluster_name 매개 변수가 필요하며 AutoSupport 및 SnapMirror에 사용됩니다. 구성 파일에서 이 매개 변수를 올바르게 정의해야 합니다.



 a| 
SCF-00042
 a| 
Clustered Data ONTAP이 감지되었지만 cmode_cluster_users가 올바르게 구성되지 않았습니다. 구성 매개 변수를 확인하십시오. 종료합니다.
 a| 
매개 변수 cmode_cluster_name과 cmode_cluster_users가 필요하며 AutoSupport 및 SnapMirror에 사용됩니다. 구성 파일에서 이러한 매개 변수를 올바르게 정의해야 합니다.



 a| 
SCF-00043
 a| 
Data ONTAP는 clustered SnapVault에서 지원되지 않습니다. 구성에서 ntap_snapvault_update를 N으로 설정합니다.
 a| 
구성을 확인하고 매개 변수를 변경합니다. Clustered Data ONTAP은 SnapVault을 지원하지 않습니다.



 a| 
SCF-00044
 a| 
meta_data_volume 매개 변수가 정의되었지만 지정된 스토리지 시스템: 볼륨이 volumes 매개 변수에 구성된 것과 일치하지 않습니다. 구성을 확인합니다.
 a| 
META_DATA_VOLUME 매개 변수가 볼륨에 지정되지 않았습니다. 메타데이터 볼륨을 볼륨에 추가합니다.



 a| 
SCF-00045
 a| 
meta_data_volume 매개 변수가 정의되었지만 volumes 매개 변수에 지정된 볼륨만 될 수는 없습니다. 메타데이터 볼륨은 개별 볼륨이어야 합니다.
 a| 
META_DATA_VOLUME에 지정된 볼륨이 볼륨에 있는 유일한 볼륨입니다. 다른 볼륨도 있어야 합니다. 일반 스냅샷 작업에는 meta_data_volume을 사용하지 마십시오.



 a| 
SCF-00046
 a| 
NetApp 관리 콘솔은 타임스탬프 스냅샷 복사본만 지원합니다.
 a| 
구성 파일을 업데이트하고 snap_timestamp_only 옵션을 Y로 설정합니다



 a| 
SCF-00047
 a| 
호환되지 않는 설정을 선택했습니다. NTAP_SnapVault_update 및 NTAP_SnapVault_snapshot 옵션은 둘 다 활성화할 수 없습니다
 a| 
구성 파일을 편집하고 두 옵션 중 하나를 비활성화합니다.



 a| 
SCF-00048
 a| 
[%s] 오류 및 종료 코드 [%s] 오류로 인해 플러그인 [%s]의 마운트 처리가 실패했습니다. 종료합니다.
 a| 
애플리케이션 오류로 인해 애플리케이션을 마운트하지 못했습니다. 로그 및 응용 프로그램 설정을 확인합니다.



 a| 
SCF-00049
 a| 
[%s] 오류 및 종료 코드 [%s] 오류로 인해 플러그인 [%s]의 마운트 해제 처리가 실패했습니다. 종료합니다.
 a| 
애플리케이션 오류로 인해 애플리케이션 마운트 해제에 실패했습니다. 로그 및 응용 프로그램 설정을 확인합니다.



 a| 
SCF-00050
 a| 
사용자 지정 작업은 애플리케이션 플러그인에만 지원됩니다
 a| 
app_name 매개 변수가 구성 파일에 설정되어 있지 않습니다. 이 매개변수는 사용할 플러그인을 결정합니다. 사용자 지정 작업은 응용 프로그램 플러그인에서만 지원됩니다.



 a| 
SCF-00051
 a| 
종료 코드 [%s]이(가) 있는 [%s]에 대한 NetApp 관리 콘솔 데이터 세트를 생성하지 못했습니다. 종료됩니다!
 a| 
디버그 오류 메시지를 확인합니다. Active IQ Unified Manager 서버와 통신하는 동안 문제가 발생할 수 있습니다.



 a| 
SCF-00052
 a| 
[%s] 종료 코드 [%s] 오류로 인해 플러그인 [%s]의 복원 처리가 실패했습니다. 종료합니다.
 a| 
응용 프로그램 오류로 인해 복원에 실패했습니다. 로그 및 응용 프로그램 설정을 확인합니다.



 a| 
SCF-00053
 a| 
플러그인 [%s]에 대한 파일 시스템 정지 해제에 실패했습니다. 오류 [%s] 및 종료 코드 [%s], 종료!
 a| 
파일 시스템 오류로 인해 파일 시스템 중지 해제에 실패했습니다. 그러나 app_ignore_error=Y; Snap Creator는 백업을 진행합니다. 로그 및 파일 시스템 설정을 확인합니다.



 a| 
SCF-00054
 a| 
플러그인 [%s]에 대한 파일 시스템 정지 해제에 오류가 발생했습니다. 종료 코드 [%s], 백업을 계속 진행합니다!
 a| 
파일 시스템 오류로 인해 파일 시스템 중지 해제에 실패했습니다. 그러나 app_ignore_error=Y; Snap Creator는 백업을 진행합니다. 로그 및 파일 시스템 설정을 확인합니다.



 a| 
SCF-00055
 a| 
스토리지 컨트롤러 [%s]의 정책 [%s]을(를) 사용하여 데이터 세트 [%s]의 NetApp 관리 콘솔 기반 백업 [%s]
 a| 
해당 없음



 a| 
SCF-00056
 a| 
스토리지 컨트롤러 [%s]의 정책 [%s]을(를) 사용하여 데이터 세트 [%s]의 NetApp 관리 콘솔 기반 백업 [%s]을(를) 성공적으로 생성했습니다
 a| 
해당 없음



 a| 
SCF-00057
 a| 
스토리지 컨트롤러 [%s]의 정책 [%s]을(를) 사용하여 데이터 세트 [%s]의 NetApp 관리 콘솔 기반 백업 [%s]을(를) 생성하지 못했습니다. 오류 [%s]
 a| 
NTAP_PM_update 및 NTAP_DFM_DATA_SET 매개 변수의 구성을 확인하십시오.



 a| 
SCF-00058
 a| 
[%s]에 대한 응용 프로그램 검색 값으로 구성을 업데이트하지 못했습니다. 종료합니다.
 a| 
권한 문제 또는 응용 프로그램에서 반환된 값을 구문 분석하지 못하여 파일을 업데이트할 수 없습니다. Snap Creator를 실행하는 사용자의 권한을 확인하고 사용 권한이 올바른지 확인합니다.



 a| 
SCF-00059
 a| 
종료 코드 [%s]을(를) 종료하여 플러그인 [%s]에 대한 [%s] 덤프가 실패했습니다. 종료합니다!
 a| 
응용 프로그램 오류로 인해 scdump 작업이 실패했습니다. 로그 및 응용 프로그램 설정을 확인합니다.



 a| 
SCF-00060
 a| 
잘못된 DTO: [%s]
 a| 
DTO의 필수 필드가 설정되지 않았거나 유효하지 않아 DTO 처리 시 유효성 검사 오류가 발생했습니다. 문제를 해결하고 DTO를 재전송합니다.



 a| 
SCF-00061
 a| 
[%s] 오류로 인해 아카이브 로그를 삭제하지 못했습니다. 종료합니다.
 a| 
Snap Creator가 애플리케이션의 아카이브 로그를 삭제할 수 없습니다. Snap Creator 사용자의 권한을 확인합니다. 구성에 따라 Snap Creator Server 또는 Snap Creator Agent가 될 수 있습니다.



 a| 
SCF-00062
 a| 
인증에 실패했습니다!
 a| 
사용자에게 작업을 수행할 권한이 없으므로 인증에 실패했습니다.



 a| 
SCF-00063
 a| 
[%s]에 대한 검색이 반환 코드 [%s] 및 메시지 [%s]로 실패했습니다.
 a| 
응용 프로그램 오류로 인해 validate_volumes=data를 사용한 응용 프로그램 검색이 실패했습니다. 로그 및 응용 프로그램 설정을 확인합니다.



 a| 
SCF-00064
 a| 
검색 결과 스토리지 객체가 검색되지 않았습니다
 a| 
validate_volumes=데이터를 사용한 응용 프로그램 검색에 실패했습니다. Snap Creator가 스토리지 시스템에 상주하는 데이터 볼륨을 검색할 수 없습니다. 자동 검색을 사용하지 않도록 설정하려면 Validate_volumes를 주석으로 처리합니다.



 a| 
SCF-00065
 a| 
[%s]의 볼륨 [%s]이(가) 구성 파일에 포함되어 있지 않습니다
 a| 
애플리케이션 검색에서 일부 볼륨이 누락되었음을 감지했습니다. 누락된 볼륨이 있는지 확인하고 볼륨 매개 변수에 추가하여 백업에 포함될 수 있도록 합니다.



 a| 
SCF-00066
 a| 
[%s]에 대한 에이전트 유효성 검사에 실패했습니다. 오류 [%s]
 a| 
구성된 에이전트에 연결할 수 없습니다. 에이전트가 다운되었거나 로컬 방화벽 문제가 있을 수 있습니다. 구성 매개 변수 SC_AGENT를 확인합니다.



 a| 
SCF-00067
 a| 
이름 패턴 [%s]에 대한 외부 스냅샷 복사본을 나열하지 못했습니다.
 a| 
Snap Creator가 regex 패턴 ntap_external_snapshot_Regex를 기반으로 외부 스냅샷 복사본을 찾을 수 없습니다. 컨트롤러에 로그인하고 스냅 목록 출력과 regex 패턴을 일치시킵니다.



 a| 
SCF-00068
 a| 
플러그인 [%s]에 대한 파일 시스템 pre_restore가 종료 코드 [%s]과(와) 함께 실패했습니다. 종료합니다.
 a| 
파일 시스템 오류로 인해 파일 시스템 사전 복원이 실패했습니다. 로그 및 파일 시스템 설정을 확인합니다.



 a| 
SCF-00069
 a| 
플러그인 [%s]에 대한 파일 시스템 pre_restore에서 종료 코드 [%s]에 오류가 발생했습니다. 백업을 계속 진행하십시오!
 a| 
파일 시스템 오류로 인해 파일 시스템 사전 복원이 실패했습니다. 그러나 app_ignore_error = Y; Snap Creator는 다른 작업을 진행합니다. 로그 및 파일 시스템 설정을 확인합니다.



 a| 
SCF-00070
 a| 
플러그인 [%s]에 대한 파일 시스템 post_restore가 종료 코드 [%s]과(와) 함께 실패했습니다. 종료합니다.
 a| 
파일 시스템 오류로 인해 파일 시스템 사후 복구가 실패했습니다. 로그 및 파일 시스템 설정을 확인합니다.



 a| 
SCF-00071
 a| 
플러그인 [%s]에 대한 파일 시스템 post_restore에서 오류가 발생했습니다. 종료 코드 [%s], 백업을 진행중입니다!
 a| 
파일 시스템 오류로 인해 파일 시스템 사후 복구가 실패했습니다. 그러나 app_ignore_error = Y; Snap Creator는 다른 작업을 진행합니다. 로그 및 파일 시스템 설정을 확인합니다.



 a| 
SCF-00072
 a| 
[%s] 정책이 구성에 정의된 스냅샷 복사본 보존 정책이 아닙니다. 종료합니다.
 a| 
사용 중인 정책이 잘못되었습니다. 구성 파일을 확인하고 ntap_snapshot_retentions를 올바르게 구성합니다.

|===