---
permalink: administration/reference_logs.html 
sidebar: sidebar 
keywords: snap, creator, error, troubleshoot, cmd, output, debug, warn, error, out, debug, stderr 
summary: Snap Creator는 유용한 오류 메시지와 문제 해결 로그를 제공합니다. 
---
= 오류 메시지 유형 및 문제 해결 로그
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Snap Creator는 유용한 오류 메시지와 문제 해결 로그를 제공합니다.

Snap Creator에서는 다음과 같은 유형의 오류 메시지를 제공합니다.

* * 정보 *
+
표준, 일반적으로 발생하는 작업의 경우.

* * CMD *
+
구성에 따라 Snap Creator가 실행되고 명령 또는 스크립트의 반환 코드가 기록되는 외부 명령 또는 스크립트입니다. 일반적으로 이러한 명령은 사전, POST 또는 앱 일시 중지 또는 일시 중지 해제 명령입니다.

* * 출력 *
+
Data ONTAPI 라이브러리 호출의 경우

* * 디버그 *
+
디버그 정보.

* * 경고 *
+
관심을 끌기 위해, 일반적으로는 정상적인 작업으로 간주되지만 어떤 작업도 필요하지 않습니다(예: 스냅샷 복사본을 삭제하는 경우).

* * 오류 *
+
문제를 나타내며, 대개 오류를 해결하기 위해 수동 작업이 필요할 수 있습니다. Snap Creator가 오류 메시지를 종료합니다. 다시 실행하기 전에 발생한 문제를 해결하는 것이 중요합니다. Snap Creator는 자동으로 문제를 해결하지는 않지만 구성 파일에 정의된 pre_exit_CMD를 사용하여 Snap Creator를 종료하기 전에 수행할 작업을 지정할 수 있습니다.



문제 해결 로그에는 Snap Creator에서 실행되는 모든 외부 명령 또는 스크립트(예: SnapDrive)의 출력이 포함되어 있습니다. Snap Creator를 통해 다른 스크립트를 호출하는 경우 이러한 스크립트의 종료 코드와 출력을 올바르게 설정하는 것이 중요합니다. 문제가 발생하면 상태 0으로 종료해서는 안 됩니다.

모든 Snap Creator 프로필 및 구성에는 다음 로그가 제공됩니다.

* * 출력 *
+
자세한 로깅 정보만 포함합니다.

* * 디버그 *
+
자세한 정보 및 디버그 로깅 정보를 포함합니다. 기본 설정인 구성 파일에 추적 메시지가 활성화되어 있으면 이 로그에 추적 정보가 표시됩니다. 추적 메시지를 활성화하는 매개변수는 LOG_TRACE_ENABLE-(Y|N)입니다.

* * 오류 *
+
지정된 구성에 대한 모든 오류 이벤트의 기록을 포함합니다. 오류 로그를 사용하면 사용자가 이벤트를 상호 연결하고 기간별 관점을 얻을 수 있도록 이전 오류에 대한 정보를 볼 수 있습니다. 이 Snap Creator를 모니터링 애플리케이션과 통합하는 방법으로 모니터링 및 사용할 수 있습니다.

* * stderr *
+
Snap Creator 코드와 관련된 문제가 발생한 경우 정보를 포함하지만 표준 오류 스트림 로그는 일반적으로 비어 있습니다.



out, Debug 및 stderr 로그는 오류 로그가 항상 추가되는 동안 구성 파일의 log_NUM 값에 의해 정의된 대로 유지됩니다. 모든 로그는 /scServer_install_path /engine/logs/profile 디렉토리에 기록됩니다.

Snap Creator Agent는 필요에 따라 out, Debug 및 stderr 로그도 생성합니다. 기본적으로 다음 매개 변수 설정으로 활성화됩니다. sc_agent_log_enable=Y
