---
permalink: administration/reference_parameters_to_set_up_cloning.html 
sidebar: sidebar 
keywords: parameter, snap, creator, server, cloning, operation 
summary: Snap Creator Server 클론 복제 작업을 설정하려면 몇 가지 매개 변수가 필요합니다. 
---
= 클론 생성 작업을 설정하는 매개 변수입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
Snap Creator Server 클론 복제 작업을 설정하려면 몇 가지 매개 변수가 필요합니다.

|===
| 매개 변수 | 설정 | 설명 


 a| 
NTAP_VOL_clone_reserve
 a| 
없음
| 파일 


| 볼륨  a| 
이는 클론 복제된 볼륨에 대한 공간 보장입니다.
 a| 
NTAP_LUN_clone_reservation



 a| 
참
| 거짓  a| 
true로 설정하면 cloneLun 작업이 선택된 경우 클론 복제된 LUN에 대해 공간이 예약됩니다. 그렇지 않으면 공간이 예약되지 않습니다.



 a| 
NTAP_clone_iGroup_map을 참조하십시오
 a| 
 a| 
스토리지 시스템, 소스 볼륨 및 iGroup을 지정합니다. 그런 다음 iGroup은 볼륨 클론에 상주하는 소스 볼륨 또는 클론 복제된 LUN에 상주하는 클론 복제된 LUN(예: " src_volume1/igroup1, src_volume2/igroup1, src_volume2/igroup1, src_volume3/igroup1, controller2: src_volume1/igroup2, src_volume2/igroup2, src_volume3/igroup2)에 매핑됩니다. * 참고: *

* LUN 클론은 상위 볼륨 또는 LUN과 동일한 이름을 사용하고 _clone으로 종료합니다. 즉, 볼륨이 myvol이라고 하는 경우 클론은 myvol_clone이 됩니다.
* 볼륨 클론은 cl_로 시작하고 -YYYYMMDDHHMMSS 로 종료합니다.




 a| 
NTAP_clone_for_backup
 a| 
(Y
| 해당 없음) 


 a| 
사용하도록 설정하면 다른 작업이 완료된 후에 클론(볼륨 및 LUN)이 생성되고 삭제됩니다. 그렇지 않으면 작업이 완료되기 전에 클론이 삭제됩니다. * 참고: * 클론을 테이프에 백업하는 경우 Y로 설정해야 합니다 데이터베이스 새로 고침을 수행하는 경우 N으로 설정해야 합니다
 a| 
NTAP_clone_secondary
 a| 
(Y



| 해당 없음)  a| 
활성화된 경우 SnapMirror 업데이트가 완료된 후 SnapMirror 대상에 클론이 생성됩니다. * 참고: * 이 설정은 NTAP_SnapMirror_use_snapshot, NTAP_SnapMirror_wait, NTAP_clone_secondary_volumes 및 cloneVol 작업과 함께 사용해야 합니다.
 a| 
NTAP_clone_secondary_volumes



 a| 
 a| 
운영 또는 2차 스토리지 시스템과 2차 볼륨의 매핑입니다. 이 작업은 Snap Creator가 보조 볼륨을 찾을 수 있도록 필요합니다(예: controller1-sec/vol1, controller1:controller1-sec/vol2).
 a| 
NTAP_NUM_VOL_CLones



 a| 
 a| 
유지하고자 하는 볼륨 클론 수입니다. 이 방식은 스냅샷 복사본 보존 정책과 비슷하게 작동합니다. * 참고: * 이 기능은 스토리지 컨트롤러에서 FlexClone 라이센스가 필요한 볼륨 클론에만 사용할 수 있습니다.
 a| 
NTAP_NFS_EXPORT_HOST



 a| 
호스트 IP입니다
 a| 
클론을 내보낼 호스트 이름 또는 IP 주소입니다. NFS를 사용하여 클론 볼륨을 마운트하는 호스트입니다.
 a| 
NTAP_NFS_EXPORT_ACCESS



 a| 
루트
| 읽기-쓰기 | 읽기 전용 


 a| 
ntap_nfs_export_host에 지정된 호스트는 클론 볼륨에 대한 액세스 또는 권한을 받습니다.

* 루트
+
루트 액세스 권한이 부여됩니다.

* 읽기 전용
+
읽기 전용 액세스 권한이 부여됩니다.

* 읽기-쓰기
+
읽기/쓰기 권한이 부여됩니다.


 a| 
NTAP_NFS_export_persistent
 a| 
참



| 거짓  a| 
NFS 내보내기가 지속되는지 여부를 결정합니다. TRUE를 선택하면 클론 볼륨이 내보내지고 스토리지 컨트롤러의 /etc/exports 파일이 업데이트됩니다.
 a| 
NTAP_cifs_export_enable



 a| 
(Y
| 해당 없음)  a| 
CIFS를 사용하여 클론 복제된 볼륨을 공유하는 설정입니다.

|===