---
permalink: administration/reference_parameters_to_set_up_snapmirror.html 
sidebar: sidebar 
keywords: parameter, snapmirror, snap, creator, server, update, cascading, volume 
summary: Snap Creator Server에 SnapMirror를 설정하려면 몇 가지 매개 변수가 필요합니다. 
---
= SnapMirror 설정을 위한 매개 변수입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Snap Creator Server에 SnapMirror를 설정하려면 몇 가지 매개 변수가 필요합니다.

|===
| 매개 변수 | 설정 | 설명 


 a| 
NTAP_SnapMirror_update
 a| 
"Y" 또는 "N"
 a| 
SnapMirror 업데이트 기능을 설정 및 해제할 수 있습니다.



 a| 
NTAP_SnapMirror_cascading_update 를 참조하십시오
 a| 
"Y" 또는 "N"
 a| 
계단식 SnapMirror 업데이트 기능을 설정하거나 해제할 수 있습니다. SnapVault 대상 볼륨을 사용하는 SnapMirror 업데이트입니다.


NOTE: Clustered Data ONTAP에서는 지원되지 않습니다.



 a| 
SnapMirror_볼륨
 a| 
 a| 
SnapMirror 업데이트를 수행할 소스 스토리지 시스템 및 볼륨의 목록을 지정합니다(예: 컨트롤러 1: vol1, vol2, vol3; controller2: vol1; controller3: vol2, vol3). * 참고: * VMware 플러그인(vSphere 및 vCloud)의 경우 이 값을 auto:detect로 설정해야 합니다.



 a| 
SnapMirror_cascading_volumes를 참조하십시오
 a| 
 a| 
SnapVault 업데이트 후 SnapMirror 업데이트를 수행할 SnapVault 대상 스토리지 시스템 및 볼륨 목록을 지정합니다(예: Sec-controller1:vol1-sec, vol2-sec). 소스 볼륨에 여러 대상이 있는 경우 다중 구간 복제에서는 이 기능이 지원되지 않습니다.


NOTE: Clustered Data ONTAP에서는 지원되지 않습니다.



 a| 
NTAP_SnapMirror_WAIT
 a| 
 a| 
SnapMirror 대상에 클론을 생성하기 전에 SnapMirror 업데이트 프로세스가 완료될 때까지 대기 시간(분)을 지정합니다. NTAP_clone_secondary가 Y로 설정된 경우 Snap Creator는 SnapMirror 업데이트가 완료될 때까지 기다린 후 작업을 진행합니다.


NOTE: 이 기능은 NTAP_clone_secondary 및 cloneVol 작업에서만 사용할 수 있습니다(현재 볼륨 클론만 지원됨).



 a| 
NTAP_SnapMirror_use_snapshot
 a| 
"Y" 또는 "N"
 a| 
이 매개 변수를 사용하는 경우 SnapMirror 업데이트는 새로 생성된 스냅샷 복사본을 사용하므로 SnapMirror 대상에 스냅샷 복사본을 생성합니다. * 참고: * SnapMirror 대상에 클론을 생성하려면 스냅샷 복사본이 필요하므로 NTAP_clone_secondary에 필요합니다.



 a| 
NTAP_SnapMirror_MAX_TRANSFER
 a| 
 a| 
SnapMirror에서 사용할 수 있는 최대 대역폭(kbps)을 지정합니다. 이 매개 변수를 설정하지 않으면 SnapMirror에서 최대 사용 가능한 대역폭을 사용합니다.



 a| 
SnapMirror_qtree_include
 a| 
 a| 
SnapMirror 업데이트에 포함될 운영 스토리지 컨트롤러 및 qtree 경로 목록을 지정합니다(예: controller1:/vol/qtree/qtree1, /vol/volume/qtree2, controller2:/vol/volume/qtree1). 이 옵션을 사용하지 않으면 볼륨에 있는 모든 qtree가 백업됩니다. 이 옵션을 사용하여 목록을 지정하면 나열된 qtree만 백업됩니다. 즉, 나머지 qtree는 무시됩니다.

|===