---
permalink: administration/reference_parameters_to_set_up_a_snapshot_copy.html 
sidebar: sidebar 
keywords: parameter, snapshot, copy, snap, creator, server, retention, snapdrive 
summary: Snap Creator Server에 대한 스냅샷 복사본을 설정하려면 몇 가지 구성 파일 매개 변수가 필요합니다. 
---
= 스냅샷 복사본 설정을 위한 매개 변수
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Snap Creator Server에 대한 스냅샷 복사본을 설정하려면 몇 가지 구성 파일 매개 변수가 필요합니다.

|===
| 매개 변수 | 설정 | 설명 


 a| 
NTAP_snapshot_retention_age
 a| 
 a| 
스냅샷 복사본의 보존 기간(일)을 정의할 수 있습니다. 구성한 경우, NTAP_snapshot_retentions 매개 변수에 정의된 수를 초과하고 보존 기간(일)보다 오래된 경우에만 스냅샷 복사본이 삭제됩니다.



 a| 
SnapDrive
 a| 
"Y" 또는 "N"
 a| 
SnapDrive API 대신 Data ONTAP를 사용하여 스냅샷 복사본을 생성할 수 있습니다.



 a| 
SnapDrive_discovery 를 선택합니다
 a| 
"Y" 또는 "N"
 a| 
SnapDrive를 사용하여 스토리지를 검색할 수 있습니다. 이는 validate_volumes 매개 변수를 사용할 때 SAN 또는 ISAN 환경에서 필요합니다.



 a| 
NTAP_snapshot_disable
 a| 
"Y" 또는 "N"
 a| 
Snap Creator에서 SnapManager용 SnapVault 또는 SnapMirror를 처리할 수 있도록 스냅샷 복사본을 생성하지 않습니다. 이 설정을 사용하려면 SnapManager 스냅샷 복사본이 다음 명명 규칙을 따라야 합니다. snapshot_copy_name -policy_recent.



 a| 
NTAP_SNSHOT_NODELETE
 a| 
"Y" 또는 "N"
 a| 
NTAP_snapshot_retentions 매개 변수를 재정의하고 스냅샷 복사본이 삭제되지 않도록 합니다. 이 변수를 활성화하면 볼륨이 가득 찰 수 있습니다.



 a| 
NTAP_snapshot_delete_CMD
 a| 
 a| 
스냅샷 보존을 기반으로 Snap Creator 대신 SnapDrive를 통해 스냅샷을 삭제합니다. * 참고: * 이 SnapDrive 명령에 사용된 모든 볼륨(마운트 드라이브)이 구성 파일에도 포함되어야 합니다.



 a| 
NTAP_snapshot_delete_by_age_only
 a| 
(운영
| 보조 


| 둘 다 해당되며 | 해당 없음)  a| 
이전 Snapshot 복사본을 삭제할 수 있습니다. 이 매개 변수에는 ntap_snapshot_retention_age 매개 변수가 필요하며, 스냅샷 복사본 수가 아닌 스냅샷 복사본 보관 기간에 따라 강제로 삭제해야 합니다.



 a| 
NTAP_snapshot_dependency_ignore
 a| 
"Y" 또는 "N"
 a| 
backupDel 작업을 사용하여 스냅샷 복사본 삭제에만 적용됩니다. 종속성이 있는 스냅샷 복사본은 수동으로 삭제할 수 없습니다.



 a| 
NTAP_snapshot_create_CMD##
 a| 
 a| 
스냅샷 복사본을 생성하고 파일 시스템 버퍼를 플러시합니다. ##은 1에서 99 사이의 숫자입니다. * 참고: * 이 설정은 SnapDrive 매개 변수를 사용하는 경우에 필요합니다. Data ONTAP API는 여전히 다른 모든 작업을 수행하는 데 사용되지만 SnapDrive 옵션은 스냅샷 복사본을 생성합니다.



 a| 
NTAP_metadata_snapshot_create_CMD##
 a| 
 a| 
메타데이터 볼륨 Snapshot 복제본을 생성하고 파일 시스템 버퍼를 플러시합니다. ##은 1에서 99 사이의 숫자입니다.



 a| 
NTAP_consistency_group_snapshot
 a| 
"Y" 또는 "N"
 a| 
일관성 그룹을 사용하여 여러 볼륨 전체에서 일관된 스냅샷 복사본을 생성할 수 있습니다.



 a| 
NTAP_consistency_group_snapshot_retry_count
 a| 
 a| 
장애 시 정합성 보장 그룹 스냅샷을 재시도해야 하는 횟수를 지정합니다.



 a| 
NTAP_consistency_group_snapshot_retry_wait
 a| 
시간(초)
 a| 
정합성 보장 그룹 스냅샷의 각 재시도 간 대기 시간을 지정합니다.



 a| 
NTAP_consistency_group_timeout입니다
 a| 
(긴급
| 중간 


| 권장)  a| 
스토리지 컨트롤러가 스냅샷 복사본을 일관되게 그룹화할 대기 시간을 지정합니다.
 a| 
NTAP_consistency_group_WAFL_sync입니다



 a| 
"Y" 또는 "N"
 a| 
CG-start 전에 WAFL-sync를 통해 CP(Consistency Point)를 강제 적용하면 일관성 그룹 스냅샷 복사본의 성능이 향상됩니다. * 참고: * DB2 플러그인으로 정합성 보장 그룹 백업을 수행하는 경우 이 매개 변수를 ""N""으로 설정해야 합니다.
 a| 
NTAP_snapshot_restore_Auto_detect



 a| 
"Y" 또는 "N"
 a| 
이 설정을 비활성화하면 단일 파일 복원을 수행할 때 항상 SFSR(단일 파일 SnapRestore)이 강제 적용됩니다.
 a| 
NTAP_snapshot_cleanup



 a| 
"Y" 또는 "N"
 a| 
백업 실패 시 생성된 모든 스냅샷 복사본을 제거합니다.
 a| 
NTAP_use_external_snapshot



 a| 
"Y" 또는 "N"
 a| 
Snap Creator가 아닌 Snapshot 복사본을 가져올 수 있습니다. 가장 최근의 스냅샷 복사본이 일치됩니다.
 a| 
NTAP_external_snapshot_Regex 를 참조하십시오

|===