---
permalink: administration/reference_parameters_used_to_configure_the_client_and_server.html 
sidebar: sidebar 
keywords: parameter, snap, creator, agent, host, client, port 
summary: Snap Creator Agent 호스트 클라이언트 및 Snap Creator Server를 구성하기 위한 매개 변수에 대해 알고 있어야 합니다. 
---
= Snap Creator Agent 호스트 클라이언트 및 Snap Creator Server를 구성하기 위한 매개 변수입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
Snap Creator Agent 호스트 클라이언트 및 Snap Creator Server를 구성하기 위한 매개 변수에 대해 알고 있어야 합니다.

|===
| 매개 변수 | 설정 | 설명 


 a| 
sc_agent_##
 a| 
호스트 이름 또는 IP_address: port입니다
 a| 
단일 구성을 사용하여 여러 원격 호스트에서 동시에 명령 또는 작업을 실행합니다. 작업은 정의된 플러그인(매개 변수 app_name) 또는 _CMD 명령(예: ntap_snapshot_create_cMD01)으로 지정된 명령입니다.

원격 호스트를 지정하려면 해당 이름 또는 IP 주소와 콜론 및 Snap Creator Agent가 수신 대기 중인 포트를 입력해야 합니다.

예: sc_agent_number = IP 주소: 포트

SC_AGENT_01 = 에이전트 IP: 에이전트 포트

SC_AGENT_02 = 에이전트 IP: 에이전트 포트

원격 호스트에서 <path to scAgent_v <#>> /bin/scAgent start 명령을 실행하여 Snap Creator Agent를 시작할 수 있습니다.



 a| 
sc_clone_target 을 참조하십시오
 a| 
클론 타겟의 호스트 이름 또는 IP_address: port입니다
 a| 
클론 작업을 활성화합니다. {pre.에서 * cloneVol * 매개 변수를 사용합니다



| post}_clone_create_cMDxx 매개 변수를 사용하면 원격 측에서 원격 스토리지 객체를 관리할 수 있습니다(예: 파일 시스템 마운트 또는 마운트 해제). 클론 타겟을 지정하려면 해당 이름 또는 IP 주소와 콜론, 그리고 Snap Creator Agent가 수신 대기 중인 포트를 입력해야 합니다.  a| 
sc_agent_timeout입니다
 a| 
시간(초)



 a| 
에이전트 서비스의 시간 제한(초)을 지정합니다. 구현된 클라이언트/서버 아키텍처는 시간 제한 메커니즘을 사용합니다. 즉, 클라이언트가 지정된 간격으로 응답하지 않으면 서버가 시간 초과 메시지와 함께 실패합니다. 그러나 클라이언트의 작업은 중단되지 않으며 추가 조사가 필요합니다.

시간 초과는 기본적으로 300초로 설정됩니다. 로드가 높거나 오래 실행 중인 알려진 작업(예: 사용자 작성 스크립트 또는 복잡한 SnapDrive 작업)이 있는 서버에서 제한 시간을 확장하고 요구 사항에 따라 이 값을 수정해야 합니다.

이 매개 변수를 작업에 걸릴 수 있는 최대 시간으로 설정해야 합니다. 예를 들어, 정지 시간이 1,800분 걸리는 경우 이 매개 변수를 1800으로 설정해야 합니다.


NOTE: 일부 플러그인에는 특정 SC_AGENT_TIMEOUT 값 요구 사항이 있습니다.
 a| 
sc_agent_dWatchdog_enable입니다
 a| 
"Y" 또는 "N"



 a| 
SC_AGENT_WATCHDOG_ENABLE 매개변수는 Snap Creator Agent 버전이 4.1 이전 버전인 경우에만 적용됩니다. 이 매개 변수는 감시 프로세스를 활성화하거나 비활성화합니다. Snap Creator Agent 4.1 이상의 경우 Watchdog 프로세스가 항상 활성화되어 있으므로 이 매개 변수는 무시됩니다. 매개 변수를 사용(즉, Y로 설정)하고 Snap Creator Agent 버전이 4.1 이상인 경우 Snap Creator Agent에서 중지 요청을 수신하면 감시 프로세스가 시작됩니다.

감시 프로세스는 SC_AGENT_UNSCIEE_TIMEOUT 매개변수를 시간 초과로 사용하여 응용 프로그램 중지를 해제합니다. 매개 변수를 사용하지 않도록 설정하고(즉, N으로 설정) Snap Creator Agentversion이 4.1 이전 버전인 경우 감시 프로세스에서 응용 프로그램을 중지하지만 scAgent/etc/agent.properties 경로에서 operation_timeout_in_msec 매개 변수(기본값: 1시간)를 사용합니다.


NOTE: Snap Creator Agent 4.1에서는 SC_AGENT_WATCHDOG_ENABLE 매개 변수가 사용되지 않으며, Snap Creator Agent 4.0에서만 사용할 수 있습니다. Snap Creator Agent 4.1부터는 이 매개변수에 설정된 값에 관계없이 감시 기능 프로세스가 하드 코딩되므로 활성화됩니다.
 a| 
sc_agent_unquiesce_timeout입니다
 a| 
시간(초)



 a| 
일시 중지 시간 제한 해제(초)를 지정합니다. Snap Creator Agent 버전이 4.1 이전 버전인 경우 이 매개 변수는 SC_AGENT_WATCHDOG_ENABLE이 Y로 설정된 경우에만 사용됩니다 Snap Creator Agent 4.1 이상을 사용하는 경우 Snap Creator Agent 감시 프로세스가 항상 켜져 있기 때문에 매개 변수를 항상 적용할 수 있습니다. Snap Creator Agent와의 통신이 불가능하고 애플리케이션이 정지 상태인 경우 Snap Creator Agent는 서버와의 통신 없이 애플리케이션을 자동으로 정상 작동 모드로 되돌립니다. 기본적으로 Unquiesce 제한 시간은 SC_AGENT_TIMEOUT 매개 변수 값에 5초를 더한 값으로 설정됩니다.
 a| 
SC_TMP_DIR
 a| 
"Y" 또는 "N"



 a| 
사용자 정의 대체 임시 디렉토리를 사용하여 Snap Creator 관련 파일을 저장할 수 있습니다. 사용자가 디렉토리를 생성하고 사용자 액세스를 관리합니다. 플러그인은 데이터베이스와 상호 작용하기 위해 임시 파일을 사용합니다. 임시 파일은 모든 사용자에 대한 쓰기 권한이 있는 호스트의 기본 임시 디렉토리에 생성됩니다. 임시 디렉토리가 가득 차면 Snap Creator에서 임시 파일을 생성하는 동안 오류가 표시됩니다.
 a| 
sc_agent_log_enable입니다
 a| 
"Y" 또는 "N"

|===