---
permalink: administration/reference_maxdb_plug_in.html 
sidebar: sidebar 
keywords: maxdb, plug-in, automates, backup, restore, operations 
summary: MaxDB 플러그인은 MaxDB 데이터베이스에서 백업 및 복원 작업을 자동화합니다. 
---
= MaxDB 플러그인
:icons: font
:imagesdir: ../media/


[role="lead"]
MaxDB 플러그인은 MaxDB 데이터베이스에서 백업 및 복원 작업을 자동화합니다.


NOTE: 지원에 대한 최신 정보를 보거나 호환성 매트릭스를 보려면 상호 운용성 매트릭스 를 참조하십시오.

MaxDB 플러그인은 다음과 같은 기능을 제공합니다.

* MaxDB 데이터베이스를 백업, 복원, 복제하는 중앙 집중식 프레임워크
* 데이터베이스와 통합 및 애플리케이션 정합성 보장 프로비저닝
* Snapshot 기술을 활용하여 데이터베이스의 시점 복사본을 생성합니다
* 용량 또는 파일 수에 상관없이 SnapRestore를 활용하여 이전 스냅샷 복사본과 애플리케이션 정합성 보장 데이터베이스를 몇 초 이내에 복원합니다
* FlexClone 기술을 사용하여 스냅샷 복사본 백업을 기반으로 데이터베이스의 빠르고 공간 효율적인 클론을 생성할 수 있습니다


다음 표에는 MaxDB 플러그인 매개 변수가 나열되어 있으며, 설정에 대한 설명과 설명이 나와 있습니다.

|===
| 매개 변수 | 설정 | 설명 


 a| 
APP_NAME입니다
 a| 
maxdb입니다
 a| 
응용 프로그램 이름을 지정합니다.



 a| 
XUSER_ENABLE을 선택합니다
 a| 
(Y
| 해당 없음) 


 a| 
데이터베이스 사용자에게 암호가 필요하지 않도록 MaxDB에 대한 xuser 사용을 활성화 또는 비활성화합니다.
 a| 
handle_LOGWRITER
 a| 
(Y



| 해당 없음)  a| 
로그 작성기 일시 중지(N) 또는 로그 작성기 다시 시작(Y) 작업을 실행합니다.
 a| 
DBMCLICMD



 a| 
path_to_dbmcli_cmd를 입력합니다
 a| 
MaxDB dbmcli 명령의 경로를 지정합니다. 설정하지 않으면 검색 경로에서 dbmcli가 사용됩니다.


NOTE: Windows 환경에서 경로는 큰따옴표("...")에 포함되어야 합니다.
 a| 
SQLCLICMD를 참조하십시오



 a| 
sqlcli_cmd 경로
 a| 
MaxDB sqlcli 명령의 경로를 지정합니다. 설정하지 않으면 sqlcli가 검색 경로에 사용됩니다.
 a| 
MAXDB_UPDATE_HIST_LOG



 a| 
(Y
| 해당 없음)  a| 
MaxDB 백업 프로그램에서 MaxDB 기록 로그를 업데이트할지 여부를 지정합니다.



 a| 
MAXDB_데이터베이스
 a| 
db_name: user_name/password
 a| 
사용자 이름과 암호로 백업할 데이터베이스를 나열합니다. 쉼표로 구분된 목록(예: dB1:user1/password, DB2:user2/password)을 사용하여 여러 데이터베이스 및 사용자 이름을 지정할 수 있습니다.



 a| 
MAXDB_CHECK_SNSHOT_DIR
 a| 
예: "+SID1: directory [, directory...]; [SID2: directory[, directory...]+"
 a| 
Snap Creator 스냅샷 복사 작업이 성공적인지 확인하고 스냅샷 복사본이 생성되는지 확인합니다. 이는 NFS에만 적용됩니다. 디렉토리는 .snapshot 디렉토리가 포함된 위치를 가리켜야 합니다.

쉼표로 구분된 목록에 여러 디렉토리를 포함할 수 있습니다. 여러 데이터베이스를 세미콜론으로 구분된 목록으로 지정할 수 있습니다.

MaxDB 7.8 이상 버전에서는 데이터베이스 백업 요청이 백업 기록에서 Failed(실패) 로 표시됩니다.



 a| 
MAXDB_BACKUP_templates
 a| 
template_name 예: 'na_snap
 a| 
각 데이터베이스에 대한 백업 템플릿을 지정합니다. 템플릿은 이미 존재해야 하며 백업 템플릿의 외부 유형이어야 합니다.

MaxDB 7.8 이상의 Snapshot 복사본 통합을 활성화하려면 MaxDB 백그라운드 서버 기능이 있고 이미 구성된 MaxDB 백업 템플릿이 있어야 합니다.



 a| 
MAXDB_BG_SERVER_PREFIX
 a| 
BG_server_prefix 예: 'na_bg
 a| 
백그라운드 서버 이름의 접두사를 지정합니다. MAXDB_BACKUP_templates 매개 변수가 설정된 경우 MAXDB_BG_SERVER_PREFIX 매개 변수도 설정해야 합니다. 접두사를 설정하지 않으면 기본값인 na_bg_database가 사용됩니다.

|===
* 관련 정보 *

http://mysupport.netapp.com/matrix["상호 운용성 매트릭스 툴: mysupport.netapp.com/matrix"]
