---
permalink: administration/reference_sybase_plug_in.html 
sidebar: sidebar 
keywords: sybase, ase, plug-in, isql, command, database, parameter, user, server 
summary: Sybase ASE 플러그인은 isql 명령을 사용하여 Sybase 데이터베이스와 상호 작용합니다. 
---
= Sybase ASE 플러그인
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sybase ASE 플러그인은 isql 명령을 사용하여 Sybase 데이터베이스와 상호 작용합니다.


NOTE: 지원에 대한 최신 정보를 보거나 호환성 매트릭스를 보려면 상호 운용성 매트릭스 를 참조하십시오.

다음 표에는 Sybase 플러그인 매개 변수가 나열되어 있고, 해당 설정이 제공되며, 에 대한 설명이 나와 있습니다.

|===
| 매개 변수 | 설정 | 설명 


 a| 
Sybase_USER입니다
 a| 
사용자 이름
 a| 
isql 명령을 실행할 수 있는 운영 체제 사용자를 지정합니다. 이 매개 변수는 UNIX에 필요합니다. 이 매개 변수는 Snap Creator Agentstart 및 stop 명령(일반적으로 루트 사용자)을 실행하는 사용자와 isql 명령을 실행하는 사용자가 다른 경우 필요합니다.



 a| 
Sybase_server를 참조하십시오
 a| 
data_server_name
 a| 
isql 명령의 Sybase 데이터 서버 이름(-S 옵션)을 지정합니다(예: ' p_test ')



 a| 
Sybase_databases(Sybase 데이터베이스
 a| 
db_name: user_name/password
 a| 
백업할 인스턴스 내의 데이터베이스를 나열합니다. 마스터 데이터베이스가 추가됩니다. 예를 들어, DBATest2:sa/53616c7404351e와 같이 추가됩니다. +ALL이라는 데이터베이스를 사용하면 데이터베이스 자동 검색이 사용되고 sybsyntax, sybsystemdb, sybsystemprocs 및 tempdb 데이터베이스는 제외됩니다.

예: `+모두:sa/53616c71a6351e'

NTAP_PWD_PROTURCE 매개 변수가 설정된 경우 암호화된 암호가 지원됩니다.



 a| 
Sybase_databases_exclude를 선택합니다
 a| 
db_name입니다
 a| 
All 구문을 사용하는 경우 데이터베이스를 제외할 수 있습니다. 세미콜론으로 구분된 목록을 사용하여 여러 데이터베이스를 지정할 수 있습니다(예: ' pub2;test_db1')



 a| 
Sybase_Tran_dump
 a| 
db_name: directory_path
 a| 
스냅샷 복사본을 생성한 후 Sybase 트랜잭션 덤프를 수행할 수 있습니다. 예: "pubs2:/sybasedumps/pubs2

트랜잭션 덤프가 필요한 각 데이터베이스를 지정해야 합니다.



 a| 
Sybase_Tran_dump_format
 a| 
%S_%D_%T. CMN
 a| 
덤프 명명 규칙을 지정할 수 있습니다. 다음 키를 지정할 수 있습니다.

* %S = Sybase_SERVER의 인스턴스 이름입니다
* %D = Sybase_databases의 데이터베이스입니다
* %T = 고유한 타임 스탬프입니다


다음은 '%S_%D_%T. log'의 예입니다



 a| 
Sybase_Tran_dump_compress
 a| 
(Y
| 해당 없음) 


 a| 
기본 Sybase 트랜잭션 덤프 압축을 설정하거나 해제합니다.
 a| 
Sybase_ISQL_CMD
 a| 
예: /opt/sybase/OCS-15__0/bin/isql



 a| 
isql 명령의 경로를 정의합니다.
 a| 
Sybase
 a| 
예: /Sybase



 a| 
Sybase 설치 위치를 지정합니다.
 a| 
Sybase_LOGDIR
 a| 
예: /usr/local/ntap/scServer/logs



 a| 
Snap Creator 로그를 저장할 디렉토리를 정의합니다.
 a| 
sSybase_manifest
 a| 
예: dtest2:/t_inf_nzL_devs/'



 a| 
매니페스트 파일을 배치해야 하는 위치와 함께 매니페스트 파일을 만들 데이터베이스를 지정합니다.
 a| 
Sybase_manifest_format
 a| 
%S__%D_%T 매니페스트 예: "%S_%D_%T 매니페스트"



 a| 
매니페스트 파일 명명 규칙을 지정할 수 있습니다. 다음 키를 지정할 수 있습니다.

* %S = Sybase_SERVER의 인스턴스 이름입니다
* %D = Sybase_databases의 데이터베이스입니다
* %T = 고유한 타임 스탬프이며, 스냅샷 복사본 이름 지정에 사용된 것과 동일합니다

 a| 
Sybase_manifest_delete를 선택합니다
 a| 
(Y



| 해당 없음)  a| 
스냅샷 복사본이 생성된 후 매니페스트를 삭제할 수 있도록 합니다. 매니페스트 파일은 항상 백업에서 사용할 수 있도록 스냅샷 복사본에서 캡처되어야 합니다.
 a| 
Sybase_EXCLUDE_tempdb입니다



 a| 
(Y
| 해당 없음)  a| 
사용자가 생성한 임시 데이터베이스를 자동으로 제외하도록 설정합니다.

|===
* 관련 정보 *

http://mysupport.netapp.com/matrix["상호 운용성 매트릭스 툴: mysupport.netapp.com/matrix"]
