---
permalink: administration/reference_red_hat_kvm_plug_in.html 
sidebar: sidebar 
keywords: kernel, kvm, virtualization, linux, snap, creator, virsh, command, plug-in, red, hat, guideline 
summary: '커널 기반 가상 머신(KVM)은 Linux 커널용 가상화 솔루션입니다. Snap Creator는 KVM 플러그인을 사용하여 게스트 가상 머신을 백업 및 복구합니다.' 
---
= Red Hat KVM 플러그인 지침
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
커널 기반 가상 머신(KVM)은 Linux 커널용 가상화 솔루션입니다. Snap Creator는 KVM 플러그인을 사용하여 게스트 가상 머신을 백업 및 복구합니다.


NOTE: 지원 또는 호환성 매트릭스에 대한 최신 정보는 상호 운용성 매트릭스 를 참조하십시오.

KVM 플러그인은 Linux, Windows 및 Solaris와 같은 게스트 운영 체제를 지원합니다.

플러그인은 내부적으로 virsh 명령을 사용합니다.

KVM 플러그인을 사용할 때는 다음 사항을 고려해야 합니다.

* 프록시로 Active IQ Unified Manager 서버를 지원하지 않습니다.
* 오픈 시스템 SnapVault 및 아카이브 로그 관리를 사용한 마운트, 마운트 해제 및 백업 작업은 지원되지 않습니다.
* SAN(Storage Area Network) 환경에서는 스토리지 컨트롤러에서 LUN 및 볼륨에 대한 정보를 수집하는 데 LHU(Linux Host Utilities) 키트가 필요합니다.
+
LHU 키트는 Snap Creator Agent와 동일한 위치에 있는 KVM 하이퍼바이저에 설치해야 합니다.

+

NOTE: LHU 키트가 설치되어 있지 않고 구성이 네트워크 연결 스토리지 및 스토리지 영역 네트워크 환경의 혼합인 경우 백업 및 복원 작업은 NFS(Network File System)에서만 작동합니다.

* KVM 플러그인은 Snap Creator 4.0 및 4.1 Agent의 Linux 버전만 지원합니다.
* 볼륨 복구는 지원되지 않으며 애플리케이션 정의 복원 작업만 지원됩니다.
* 삭제된 가상 시스템(VM)은 복원할 수 없습니다.
* 스토리지 컨트롤러 IP 및 호스트는 KVM 호스트의 /etc/hosts 또는 DNS(Domain Name System)에 있어야 합니다.
* 구성당 하나의 KVM 호스트만 지원됩니다.
* ISO 리포지토리를 사용하여 가상 시스템을 생성한 경우 작업을 수행하려면 CD-ROM 옵션의 Virt Manager 콘솔을 통해 가상 시스템에서 이 리포지토리를 분리해야 합니다.
* SC_AGENT_TIMEOUT 값은 기본값 600 이상이어야 합니다.
* 볼륨은 자동 감지를 사용하여 자동으로 검색됩니다.
+
대상이 SnapMirror 관계에 있지 않으면 검색된 대상 볼륨을 볼 수 없습니다. dpstatus를 사용하여 SnapMirror 관계의 상태를 확인해야 합니다. SnapMirror 관계가 없는 경우 먼저 SnapMirror 관계를 생성해야 합니다.

* app_defined_restore 값이 Y인 경우 GUI를 사용한 SnapVault 복구 작업은 지원되지 않습니다.
* SnapMirror 및 SnapVault 관계가 자동으로 감지되지 않으므로 GUI를 사용하여 SnapMirror 및 SnapVault 구성을 생성할 때 볼륨 세부 정보를 수동으로 입력해야 합니다.
* VM에 매핑된 데이터 디스크는 백업되지 않습니다.
* VM 일시 중지 및 재개 작업은 순차적으로 수행됩니다.
+
여러 VM의 경우 백업 작업 중 일시 중지 상태의 VM 기간은 VM 수에 따라 달라집니다.





== 지원되는 KVM 구성

* SAN: 원시 다중 경로 장치(다중 경로가 있는 LUN)에 설치된 게스트 가상 시스템을 지원합니다.
* NAS: NFS 볼륨에 설치된 게스트 가상 머신을 지원합니다.



NOTE: 단일 다중 경로 장치에 여러 가상 시스템을 설치한 구성은 지원되지 않습니다.

LVM 또는 SAN 환경의 이미지 파일에 설치된 게스트 가상 시스템은 지원되지 않습니다.

다음 표에서는 KVM 플러그인 매개 변수에 대해 설명합니다.

|===
| 매개 변수 | 설정 | 설명 


 a| 
KVM_RESTORE_VM_LIST
 a| 
예: 'VM1, VM2'
 a| 
복구할 VM 목록을 지정합니다. 이 매개 변수는 복원 중에만 필요합니다.



 a| 
KVM_VM_매핑
 a| 
예: 'VM1:s_C1:/vol/vol1/lun1; VM2:s_C2:/vol/vol2/lun2;'
 a| 
(필수) VM과 관련 스토리지 컨트롤러, LUN 또는 파일 경로 간의 매핑을 지정합니다. 이 매개 변수는 검색 프로세스 중에 동적으로 업데이트됩니다.



 a| 
KVM_VM_CONFIG_DIR
 a| 
기본값: /etc/libvirt/qemu
 a| 
(선택 사항) VM의 모든 XML 구성 파일이 저장되는 디렉토리의 경로를 지정합니다.



 a| 
KVM_CMD_RETRY_COUNT
 a| 
기본값: 3입니다
 a| 
(선택 사항) KVM 플러그인에서 명령을 실행할 때 명령을 다시 실행하는 횟수를 지정합니다.

|===
* 관련 정보 *

http://mysupport.netapp.com/matrix["상호 운용성 매트릭스 툴: mysupport.netapp.com/matrix"]
