---
permalink: administration/task_creating_configuration_files_using_sc_gui.html 
sidebar: sidebar 
keywords: configuration, file, wizard, gui, management 
summary: 구성 마법사를 사용하여 구성 파일을 생성할 수 있습니다. 
---
= 구성 파일을 만드는 중입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
구성 마법사를 사용하여 구성 파일을 생성할 수 있습니다.

. Snap Creator GUI의 기본 메뉴에서 * 관리 * > * 구성 * 을 선택합니다.
. 프로파일 및 구성 창에서 새 구성 파일을 찾을 프로파일을 마우스 오른쪽 단추로 클릭한 다음 * 새 구성 * 을 선택합니다.
+
오른쪽 창에 구성 마법사가 열립니다.

. 
+
.. 구성 페이지에서 구성 파일의 이름을 입력합니다.
+

NOTE: 기본적으로 구성 파일에서 암호가 일반 텍스트로 표시되지 않도록 암호 암호화가 사용됩니다.

.. 플러그인 유형 페이지에서 플러그인 유형을 선택합니다.
+
구성 마법사에서 로 이동한 페이지는 선택한 옵션에 따라 다릅니다.

+
|===
| 플러그인 유형 옵션입니다 | 다음 페이지 | 다음 페이지 


 a| 
애플리케이션 플러그인
 a| 
* 애플리케이션 플러그인 * 구성할 플러그인을 선택합니다.
 a| 
* 플러그인 매개 변수 * 선택한 플러그인 옵션과 관련된 구성 세부 정보를 제공합니다.



 a| 
가상화 플러그인
 a| 
* 가상화 플러그인 * 구성할 플러그인을 선택합니다.
 a| 
* 플러그인 매개 변수 * 선택한 플러그인 옵션과 관련된 구성 세부 정보를 제공합니다.



 a| 
커뮤니티 플러그인
 a| 
* 커뮤니티 플러그인 * 구성할 플러그인을 선택합니다.
 a| 
* 플러그인 매개 변수 * 선택한 플러그인 옵션과 관련된 구성 세부 정보를 제공합니다.



 a| 
없음(플러그인을 사용하지 않는 경우)
 a| 
* 에이전트 구성 *
 a| 
--

--
|===
+
플러그인 매개 변수 및 구성에 대한 자세한 내용은 플러그인 설명서를 참조하십시오.

.. 에이전트 구성 페이지에서 Snap Creator Agent의 구성 정보를 입력합니다.
.. 저장소 연결 설정 페이지에서 전송 유형(HTTP 또는 HTTPS)을 선택합니다.
+
선택한 전송 유형에 대한 표준 포트가 표시됩니다. 스토리지 시스템이 비표준 포트를 사용하는 경우 포트 필드에 포트 정보를 입력합니다.

.. 컨트롤러/Vserver 자격 증명 페이지에서 각 스토리지 컨트롤러, SVM에 대한 IP 주소와 로그인 자격 증명을 이 구성 파일의 볼륨이 포함된 입력합니다.
+

NOTE: 구성에 스토리지 컨트롤러 또는 SVM을 하나 이상 추가해야 합니다.

.. 컨트롤러/Vserver 볼륨 창에서 포함할 각 볼륨을 선택하고 오른쪽 창으로 끌거나 오른쪽 화살표를 클릭하여 볼륨을 오른쪽 창으로 이동한 다음 * Save * 를 클릭합니다.
+

IMPORTANT: 스냅샷 복사본을 SnapMirror 또는 SnapVault 대상에 복제하려는 경우 이 단계에서 입력하는 SVM의 이름은 SnapMirror 또는 SnapVault 관계를 생성할 때 사용한 SVM의 이름과 정확히 같아야 합니다. 관계를 만들 때 정규화된 도메인 이름을 지정한 경우, Snap Creator에서 제공하는 정보를 통해 SVM을 찾을 수 있는지 여부와 관계없이 이 단계에서 정규화된 도메인 이름을 지정해야 합니다. 이름(대문자 또는 소문자)에 사용하는 대/소문자를 나타냅니다.

+
SnapMirror show 명령을 사용하여 운영 스토리지 시스템에서 SVM의 이름을 확인할 수 있습니다.

+
[listing]
----
snapmirror show -destination-path destination_SVM:destination_volume
----
+
여기서 destination_SVM_name은 대상 시스템의 SVM 이름이고, destination_volume은 볼륨입니다.

.. 컨트롤러 자격 증명 페이지에서 컨트롤러에 올바른 정보가 표시되는지 확인합니다.
+
변경이 필요한 경우 컨트롤러를 선택한 다음 * 편집 * 을 클릭합니다.

.. 스냅샷 세부 정보 페이지에서 스냅샷 복사본 세부 정보를 제공합니다.
+
|===
| 필드에 입력합니다 | 설명 


 a| 
스냅샷 복사본 이름
 a| 
일반적으로 스냅샷 복사본 이름을 지정할 수 있지만 스냅샷 복사본의 이름은 구성 파일과 같지만, 스냅샷 복사본 이름은 백업 중인 데이터를 반영할 수 있습니다.

참고: 스냅샷 복사본 이름을 지정할 때 특수 문자를 사용하지 마십시오.



 a| 
스냅샷 복사본 레이블
 a| 
스냅샷 복사본 레이블을 지정할 수 있습니다. 이 옵션은 clustered Data ONTAP 8.2 이상에서 사용할 수 있습니다. Clustered Data ONTAP 8.2 이전 Data ONTAP 릴리스의 경우 이 필드는 기능을 제공하지 않습니다.



 a| 
정책 유형
 a| 
정책 유형을 선택할 수 있습니다. 두 가지 옵션이 있습니다.

*** 정책: 이 옵션은 Snapshot copy Policies 영역에 표시되는 기본 제공 정책 중 하나를 사용하도록 설정하고 보존 정책(보존할 백업 수)을 지정합니다.
*** 정책 개체 사용: 정책 개체가 이미 생성된 경우 이 옵션을 선택해야 합니다.




 a| 
스냅샷 복사본 정책
 a| 
활성화할 정책을 선택할 수 있는 옵션을 제공합니다



 a| 
스냅샷 복사본 삭제 방지
 a| 
에서 스냅샷 복사본의 삭제를 방지할 수 있는지 여부를 결정할 수 있습니다



 a| 
정책 보존 기간
 a| 
정책 보존 기간을 지정할 수 있습니다



 a| 
명명 규칙
 a| 
백업의 명명 규칙(최근 또는 타임스탬프)을 지정할 수 있습니다. SAP HANA, Vibe, Domino와 같은 플러그인은 "최근"에서 지원되지 않습니다.

를 누릅니다

|===
.. 스냅샷 세부 정보 계속 페이지에서 사용자 환경에 적용할 수 있는 추가 설정을 구성합니다.
.. 데이터 보호 페이지에서 SnapMirror와 통합할지 SnapVault 작업과의 통합이 필요한지 여부를 선택합니다.
+
SnapMirror 또는 SnapVault 기술을 선택한 경우 추가 정보가 필요합니다. SnapMirror 및 SnapVault 기술의 경우 IP 주소가 아닌 스토리지 시스템 이름을 제공해야 합니다.

.. DFM/OnCommand 설정 페이지에서 Snap Creator 구성을 NetApp OnCommand 관리 툴과 통합하려는 경우 을 선택하고 세부 정보를 제공합니다.
.. 요약을 검토하고 * Finish * 를 클릭합니다.



