---
permalink: administration/task_starting_verifying_and_stopping_the_snap_creator_server_on_windows.html 
sidebar: sidebar 
keywords: snap, creator, server, service, start, verify, stop, windows 
summary: Snap Creator Server 서비스를 시작 및 중지하고 Snap Creator Server 서비스가 Windows 시스템에서 실행 중인지 확인할 수 있습니다. 
---
= Windows에서 Snap Creator Server 시작, 확인 및 중지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Snap Creator Server 서비스를 시작 및 중지하고 Snap Creator Server 서비스가 Windows 시스템에서 실행 중인지 확인할 수 있습니다.

. Snap Creator 그래픽 사용자 인터페이스(GUI)가 열려 있지 않은 경우 다음을 엽니다.
+
.. 웹 브라우저에 Snap Creator Server의 URL을 입력합니다. "https://IP_address:gui_port"[]
+
기본적으로 포트는 8443입니다.

.. Snap Creator GUI에 대한 자격 증명을 사용하여 로그인합니다.


+
Snap Creator GUI가 열리면 Snap Creator Server 서비스가 실행 중입니다.

. 명령 프롬프트에서 Snap Creator Server 서비스를 시작 또는 중지하거나 Snap Creator Server 서비스가 실행 중인지 확인합니다.
+
|===
| 원하는 작업 | 다음을 입력하십시오. 


 a| 
Snap Creator Server 서비스를 시작합니다
 a| 
sc start snapcreatorserverservice를 시작합니다



 a| 
Snap Creator Server 서비스가 실행 중인지 확인합니다
 a| 
SC 쿼리 snapcreatorserverservice입니다



 a| 
Snap Creator Server 서비스를 중지합니다
 a| 
sc stop snapcreatorserverservice입니다

|===
+
Snap Creator를 포그라운드에서 실행하려면 SC start 명령을 사용하는 대신 다음 단계를 수행하십시오.

+
.. Snap Creator Server가 설치된 호스트에서 명령 프롬프트를 열고 Snap Creator Serverdirectory:'cd\install_path\scServer4.3.0\bin\'으로 이동합니다
.. Snap Creator Server를 시작하려면 배치 스크립트 'cServer.bat start'를 실행합니다
+
명령 프롬프트를 닫으면 Snap Creator Server 서비스가 중지됩니다. 배치 스크립트(scServer.bat)는 포그라운드에서 Snap Creator를 실행하기 때문에 명령 프롬프트가 열려 있는 경우에만 Snap Creator Server가 실행됩니다. 백그라운드에서 Snap Creator를 실행하려면 Snap Creator Server 서비스 명령을 사용해야 합니다.




