---
permalink: administration/task_customizing_the_default_keystore.html 
sidebar: sidebar 
keywords: keystore, certificate, keytool, windows, unix 
summary: Windows 및 UNIX에서 사용할 수 있는 keytool 명령을 사용하여 기본 키 저장소 또는 인증서를 사용자 지정할 수 있습니다. 
---
= 기본 키 저장소 사용자 지정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows 및 UNIX에서 사용할 수 있는 keytool 명령을 사용하여 기본 키 저장소 또는 인증서를 사용자 지정할 수 있습니다.

keytool 명령은 Java에서 제공합니다. 일부 환경에서는 keytool 명령을 실행하기 위해 Java 설치 디렉토리로 전환해야 할 수도 있습니다.

Snap Creator는 Truststore를 지원하지 않습니다.

. Snap Creator 에이전트를 중지합니다.
. 단일 인증서로 새 키 저장소를 생성합니다.
+
"keytool-genkeypair-alias_name-keystore keystore_file-keystore private_key_password-storepass keystore_password"를 입력합니다

+
Keytool -keypenair -alias servicekey -keystore serviceKeystore.jks -keykeypass kypswd123 -storepass kystrpswd123

. keystore 파일을 scAgent4.3.0/etc/ 디렉토리에 복사합니다.
. Snap Creator Agent 구성 파일(scAgent4.3.0/etc/allowed_commands.config)에서 keystore_file=keystore_file 및 keystore_pass=keystore 암호 매개 변수를 업데이트합니다.
. Snap Creator 에이전트를 시작합니다.


* 관련 정보 *

xref:task_starting_verifying_and_stopping_the_snap_creator_agent_on_windows.adoc[Windows에서 Snap Creator Agent 시작, 확인 및 중지]

xref:task_starting_verifying_and_stopping_the_snap_creator_agent_on_unix.adoc[UNIX에서 Snap Creator Agent 시작, 확인 및 중지]
