---
permalink: administration/task_starting_verifying_and_stopping_the_snap_creator_agent_on_windows.html 
sidebar: sidebar 
keywords: snap, creator, agent, service, start, verify, stop, windows 
summary: Snap Creator Agent 서비스를 시작 및 중지하고 Snap Creator Agent 서비스가 Windows 시스템에서 실행 중인지 확인할 수 있습니다. 
---
= Windows에서 Snap Creator Agent 시작, 확인 및 중지
:icons: font
:imagesdir: ../media/


[role="lead"]
Snap Creator Agent 서비스를 시작 및 중지하고 Snap Creator Agent 서비스가 Windows 시스템에서 실행 중인지 확인할 수 있습니다.

. 명령 프롬프트에서 Snap Creator Agent 서비스를 시작 또는 중지하거나 Snap Creator Agent 서비스가 실행 중인지 확인합니다(해당하는 경우).
+
|===
| 원하는 작업 | 다음을 입력하십시오. 


 a| 
Snap Creator 에이전트 서비스를 시작합니다
 a| 
sc start snapcreatoragentservice



 a| 
Snap Creator Agent 서비스가 실행 중인지 확인합니다
 a| 
SC 쿼리 snapcreatoragentservice



 a| 
Snap Creator 에이전트 서비스를 중지합니다
 a| 
sc stop snapcreatoragentservice

|===
+
Snap Creator를 포그라운드에서 실행하려면 SC start 명령을 사용하는 대신 다음 단계를 수행하십시오.

+
.. Snap Creator Agent가 설치된 호스트에서 명령 프롬프트를 열고 Snap Creator AgentDirectory로 이동합니다. cd '\install_path\scAgent4.3.0\bin\'
.. Snap Creator Agent 서비스를 시작하려면 배치 스크립트 scAgent.bat start를 실행합니다
+
명령 프롬프트를 닫으면 Snap Creator Agent 서비스가 중지됩니다. 배치 스크립트(scAgent.bat)는 포그라운드에서 Snap Creator를 실행하기 때문에 명령 프롬프트가 열려 있는 경우에만 Snap Creator Agent가 실행됩니다. 백그라운드에서 Snap Creator를 실행하려면 Snap Creator 에이전트 서비스를 사용해야 합니다.




