---
permalink: administration/task_creating_global_configuration_files.html 
sidebar: sidebar 
keywords: global, configuration, storage, controller, file, create, backup, super, profile 
summary: '글로벌 구성 파일을 생성하여 스토리지 컨트롤러, SVM(스토리지 가상 시스템) 또는 VMware 자격 증명 구성을 백업 정책에서 분리할 수 있습니다.' 
---
= 글로벌 구성 파일 생성 중
:icons: font
:imagesdir: ../media/


[role="lead"]
글로벌 구성 파일을 생성하여 스토리지 컨트롤러, SVM(스토리지 가상 머신) 또는 VMware 자격 증명 구성을 백업 정책에서 분리할 수 있습니다.

글로벌 구성 파일을 사용하면 액세스를 제어하고 백업 및 복원 작업을 처리할 수 있습니다.

두 가지 유형의 글로벌 구성 파일을 생성할 수 있습니다.

* * 슈퍼 글로벌 *
+
이 설정은 모든 프로파일의 모든 설정에 적용됩니다.

* * 글로벌 프로필 *
+
이 설정은 프로파일 내에서 작성된 모든 설정에 적용됩니다.

+
.. Snap Creator GUI의 기본 메뉴에서 * 관리 * > * 글로벌 구성 * 을 선택합니다.
.. 글로벌 구성 창에서 * 글로벌 생성 * 을 클릭합니다.
+
오른쪽 창에 글로벌 설정에 대한 구성 마법사가 열립니다.

.. 구성 마법사를 완료하여 구성 파일을 생성합니다.
+
... Configuration * 페이지에서 글로벌 구성 유형(Super Global 또는 Profile Global)을 선택합니다.
+
구성 파일의 이름은 기본적으로 전역으로 설정됩니다. 이 이름은 변경할 수 없습니다.

+
글로벌 구성 유형으로 프로파일 글로벌을 선택한 경우 프로파일을 선택합니다.

+

NOTE: 기본적으로 구성 파일에서 암호가 일반 텍스트로 표시되지 않도록 암호 암호화가 사용됩니다.

... 플러그인 유형 페이지에서 플러그인 유형을 선택합니다.
+
마법사에서 앞으로 이동할 페이지는 선택한 옵션에 따라 다릅니다.

+
|===
| 플러그인 유형 옵션입니다 | 다음 페이지 | 다음 페이지 


 a| 
가상화 플러그인
 a| 
* 가상화 플러그인 * 구성할 플러그인을 선택합니다.
 a| 
* 인증 정보 * 선택한 플러그인 옵션에 대한 인증 정보를 제공합니다.



 a| 
없음
 a| 
* 스토리지 연결 설정 *
 a| 
--

--
|===
+
플러그인 자격 증명에 대한 자세한 내용은 플러그인 설명서를 참조하십시오.

... 저장소 연결 설정 페이지에서 전송 유형(HTTP 또는 HTTPS)을 선택합니다.
+
선택한 전송 유형에 대한 표준 포트가 표시됩니다. 스토리지 시스템이 비표준 포트를 사용하는 경우 포트 필드에 포트 정보를 입력합니다.

... 컨트롤러/Vserver 자격 증명 페이지에서 이 구성 파일의 볼륨이 포함된 SVM당 IP 주소와 로그인 자격 증명을 입력합니다.
+

NOTE: 구성에 스토리지 컨트롤러 또는 SVM을 하나 이상 추가해야 합니다.

... 컨트롤러 자격 증명 페이지에서 컨트롤러에 올바른 정보가 표시되는지 확인합니다.
+
변경이 필요한 경우 컨트롤러를 선택한 다음 * 편집 * 을 클릭합니다.

... DFM/OnCommand 설정 페이지에서 Snap Creator 구성을 NetApp OnCommand 관리 툴과 통합하려는 경우 을 선택하고 세부 정보를 제공합니다.
... 요약을 검토하고 * Finish * 를 클릭합니다.





