---
permalink: installation/concept_plug_ins_for_application_integration.html 
sidebar: sidebar 
keywords: plug-in, application, integration 
summary: 플러그인은 애플리케이션 또는 데이터베이스를 일관된 상태로 전환하는 데 사용됩니다. Snap Creator에는 이미 바이너리 파일의 일부이며 추가 설치가 필요하지 않은 여러 플러그인이 포함되어 있습니다. 
---
= 애플리케이션 통합을 위한 플러그인
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
플러그인은 애플리케이션 또는 데이터베이스를 일관된 상태로 전환하는 데 사용됩니다. Snap Creator에는 이미 바이너리 파일의 일부이며 추가 설치가 필요하지 않은 여러 플러그인이 포함되어 있습니다.

지원되는 애플리케이션 유형으로는 데이터베이스, 이메일, 하이퍼바이저 또는 맞춤형 애플리케이션이 있습니다. Snap Creator에 사용할 수 있는 플러그인은 다음과 같습니다.

* 애플리케이션 및 데이터베이스 플러그인:
+
** DB2
** IBM Domino(Domino)
** 최대 DB
** MySQL
+

NOTE: MySQL 플러그인은 여러 데이터베이스의 백업 및 복원 작업을 지원하지 않습니다.

** 오라클
** SAP 고성능 분석 어플라이언스(HANA)
** Sybase Adaptive Server Enterprise(ASE)


* SnapManager 플러그인:
+
** Microsoft Exchange용 SnapManager
** Microsoft SQL Server용 SnapManager


* 하이퍼바이저 플러그인:
+
** Citrix XenServer를 참조하십시오
** Red Hat 커널 기반 가상 머신(KVM)
** VMware(개별 가상 머신 백업을 위한 vSphere 및 vApp 백업을 위한 vCloud Director)




사용자 지정("커뮤니티"라고도 함) 플러그인은 개발자 커뮤니티에서 작성하며 Snap Creator에서 활성화할 수 있지만 지원되지는 않습니다. 이 플러그인은 Snap Creator에서 제공하는 인터페이스를 활용하며 개발자가 자신의 개발 작업을 타겟 애플리케이션에 집중할 수 있도록 지원합니다.

자세한 내용은 를 참조하십시오 http://community.netapp.com/t5/Snap-Creator-Framework-Discussions/bd-p/snap-creator-framework-discussions["Snap Creator 프레임워크 토론 커뮤니티 포럼"] 사이트.

https://library.netapp.com/ecm/ecm_download_file/ECMLP2854418["Snap Creator Framework 4.3.3 관리 가이드"]
