---
permalink: installation/task_upgrading_the_snap_creator_agent_4_0_x_on_unix.html 
sidebar: sidebar 
keywords: upgrading, upgrade, snap, creator, agent, 4.0.x, unix 
summary: UNIX의 Snap Creator Agent 4.0.x에서 직접 업그레이드할 수 있습니다. 
---
= UNIX에서 Snap Creator Agent 4.0.x 업그레이드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
UNIX의 Snap Creator Agent 4.0.x에서 직접 업그레이드할 수 있습니다.

* Snap Creator Agent 디렉토리를 백업하기 전에 Snap Creator Agent를 중지하여 백업된 데이터가 완료되었는지 확인합니다.
+
예를 들어 다음 명령을 입력합니다.

+
[listing]
----
/install_path/scAgent4.0.x/bin/scAgent stop
----
* Snap Creator Agent 디렉토리(/install_path/scAgent4.0.x) 내에서 다음 디렉토리와 모든 관련 하위 디렉토리 및 파일을 백업했습니다.
+
** agent.conf 파일(.../config/agent.conf)
** 로그 디렉토리(활성화된 경우)(../logs)
** 플러그인 디렉토리(.../plugins)




4.1 이전 버전의 Snap Creator Agent에서는 agent.conf라는 파일을 사용하여 Snap Creator Agent에서 실행될 수 있는 Snap Creator 외부의 명령을 나열했습니다. 4.1에서는 Allowed_commands.config 파일이 사용됩니다.

마찬가지로, Snap Creator Agent가 통신할 수 있는 agent.conf 파일이 나열된 호스트입니다. 기본적으로 Snap Creator Agent는 모든 Snap Creator Server와 통신을 허용했습니다. 그러나 이전 버전의 Snap Creator에서 이 기능을 사용하도록 선택한 경우 agent.properties 파일의 authorized_hosts 매개 변수가 이 기능을 대체합니다.


NOTE: 이러한 매개변수를 사용하지 않은 경우 새 에이전트를 간단히 설치하는 것이 좋습니다.

다음 단계에서 제공되는 경로는 기본 설치 경로를 나타냅니다. 아래 명령의 경로는 설치 경로와 다를 수 있습니다.

. Snap Creator Agent를 아직 중지하지 않은 경우 중지합니다.
+
자세한 내용은 이 항목 앞부분의 세부 정보를 참조하십시오.

. 최신 Snap Creator Agent를 설치하되 Snap Creator Agent는 시작하지 마십시오.
+
자세한 내용은 UNIX에서 Snap Creator Agent 설치에 대한 정보를 참조하십시오.

. 텍스트 편집기에서 agent.conf 파일의 백업된 복사본을 엽니다.
+
다음은 agent.conf 파일의 예입니다.

+
[listing]
----
host: scServer@Lyon
command: rc_domino
----
. 새 allowed_commands.config 파일(/install_path/scAgent4.1.x/etc/allowed_commands.config)을 텍스트 편집기에서 열고 agent.conf의 명령줄을 allowed_commands.config 파일로 복사합니다. 그러나 최신 Snap Creator의 향상된 보안으로 인해 명령이 완전히 정규화되었는지 확인합니다.
+
앞의 예제에서 allowed_commands.config 파일에는 다음 사항이 포함되어 있어야 합니다.

+
[listing]
----
command: /etc/init.d/rc_domino
----
+

NOTE: 명령에 공백이 있으면 명령을 따옴표로 묶어야 합니다.

+
각 명령을 별도의 줄에 추가하여 필요에 따라 명령을 추가할 수 있습니다.

+
변경 후 파일을 저장하고 닫습니다.

. 텍스트 편집기에서 agent.properties 파일(/install_path/scAgent4.1.x/etc/agent.properties)을 열고 authorized_hosts= * 의 기본 항목을 변경하여 agent.conf 파일의 호스트 설정을 반영합니다.
+
앞의 예제에서 authorized_hosts 매개 변수는 다음을 포함해야 합니다.

+
[listing]
----
AUTHORIZED_HOSTS=Lyon
----
+
필요에 따라 호스트를 추가할 수 있습니다. 호스트 이름을 구분하려면 쉼표를 사용하십시오. 호스트 이름과 IP 주소가 모두 지원됩니다.

+
[listing]
----
AUTHORIZED_HOSTS=Lyon, 10.10.10.192, Fuji01
----
+
변경 후 파일을 저장하고 닫습니다.

. 다음 명령을 입력하여 Snap Creator Agent를 시작합니다.
+
[listing]
----
/install_path/scAgent4.1.x/bin/scAgent start
----
+

NOTE: allowed_commands.config 또는 agent.properties 파일을 변경한 경우 변경 사항이 있을 때 Snap Creator Agent를 다시 시작해야 합니다.



* 관련 정보 *

xref:task_installing_the_snap_creator_agent_on_unix.adoc[UNIX 기반 시스템에 Snap Creator Agent 설치]
