---
permalink: installation/task_uninstalling_snap_creator_on_windows.html 
sidebar: sidebar 
keywords: uninstalling, uninstall, snap, creator, windows 
summary: 'Windows 시작 메뉴를 사용하여 Snap Creator를 제거할 수 있습니다. Windows 제거 프로그램은 설치된 Snap Creator 구성 요소를 제거합니다\(예: Snap Creator Server와 Snap Creator Agent가 모두 설치된 경우 둘 다 제거됩니다\). 마찬가지로, 구성 요소 중 하나만 설치된 경우 해당 구성 요소가 제거됩니다.' 
---
= Windows에서 Snap Creator를 제거합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows* 시작* 메뉴를 사용하여 Snap Creator를 제거할 수 있습니다. Windows 제거 프로그램은 설치된 Snap Creator 구성 요소를 제거합니다(예: Snap Creator Server와 Snap Creator Agent가 모두 설치된 경우 둘 다 제거됩니다). 마찬가지로, 구성 요소 중 하나만 설치된 경우 해당 구성 요소가 제거됩니다.

* Snap Creator Server 엔진 디렉토리(C:\Program Files\NetApp\Snap_Creator_Framework\scServer4.1.0\engine) 내에 다음 디렉토리와 모든 관련 하위 디렉토리 및 파일을 백업합니다.
+
** Snap Creator 데이터베이스(..\snapcreator)
** Snap Creator 서버 속성(..\etc)
** 구성 파일(..\configs)
** 로그(..\logs)
** 플러그인 리포지토리(활성화된 경우)(..\snapcreatorPlugin)


* Snap Creator Agent 디렉토리(C:\Program Files\NetApp\Snap_Creator_Framework\scAgent4.1.0) 내에 다음 디렉토리 및 모든 관련 하위 디렉토리와 파일을 백업합니다.
+
** 로그(..\logs)
** 플러그인(..\plugins)
** 허용되는_command.config 및 agent.properties 파일이 포함된 Snap Creator Agent 속성(..\etc


* 명령 프롬프트에서 Snap Creator를 수동으로 시작한 경우 명령 프롬프트를 닫아 Snap Creator를 중지하고 종료합니다.
+

NOTE: Snap Creator가 서비스에서 시작된 경우 제거 프로그램은 제거 프로세스의 일부로 서비스를 중지합니다.

+
.. Start * > * All programs * > * Snap Creator * > * Uninstall NetApp Snap Creator Framework * 를 선택합니다.
.. Snap Creator를 제거하기 전에 로그 및 구성 파일을 백업했는지 여부를 묻는 메시지가 표시되면 * 예 * 를 클릭합니다.
.. 제거 프로세스가 완료된 후 메시지가 나타나면 * 닫기 * 를 클릭합니다.



