---
permalink: installation/task_upgrading_snap_creator_server_4_1_x_on_windows.html 
sidebar: sidebar 
keywords: upgrading, upgrade, snap, creator, server, 4.1.x, windows 
summary: Windows의 Snap Creator Server 4.1.x에서 업그레이드할 수 있습니다. 
---
= Windows에서 Snap Creator Server 4.1.x 업그레이드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows의 Snap Creator Server 4.1.x에서 업그레이드할 수 있습니다.

* Snap Creator 디렉토리를 백업하기 전에 Snap Creator 서비스('s napcreatorserverservice' 및 's napcreatoragentservice')를 중지하여 백업된 데이터가 완전한지 확인해야 합니다.
+
예를 들어 서비스 스냅인을 사용하여 서비스를 중지할 수 있습니다.

+
.. 시작 * > * 실행 * 을 선택하고 'services.msc'를 입력합니다.
.. Snap Creator 서비스를 찾아 선택한 다음 서비스를 중지합니다. 또는 명령 프롬프트를 열고 다음 명령을 입력할 수 있습니다.


+
[listing]
----
sc stop snapcreatorserverservice
sc stop snapcreatoragentservice
----
* Snap Creator 4.1.x 서버 엔진 하위 디렉토리(C:\Program Files\NetApp\Snap_Creator_Framework\scServer4.1.x\engine) 내에 다음 디렉토리와 모든 관련 하위 디렉토리 및 파일을 백업해야 합니다.
+
** Snap Creator 데이터베이스(..\snapcreator)
** Snap Creator 서버 속성(..\etc)
** 구성 파일(..\configs)
** 로그(..\logs)
** 플러그인 리포지토리(활성화된 경우)(..\snapcreatorPlugin)


* (선택 사항) Snap Creator Agent가 Snap Creator Server와 동일한 호스트에 설치되어 있는 경우, Snap Creator Agent 디렉토리(C:\Program Files\NetApp\Snap_Creator_Framework\Agent4.1.x) 내에 다음 디렉토리와 모든 관련 하위 디렉토리 및 파일을 백업해야 합니다.
+
** 허용되는_command.config 및 agent.properties 파일이 포함된 Snap Creator Agent 속성(..\etc
** 로그(..\logs)
** 플러그인(..\plugins)


* 명령 프롬프트에서 Snap Creator를 수동으로 시작한 경우 명령 프롬프트를 닫고 중지해야 합니다.
+

NOTE: Snap Creator가 서비스에서 시작된 경우 제거 프로그램은 제거 프로세스의 일부로 서비스를 중지합니다.



다음 단계에서 제공되는 경로는 Windows의 기본 설치 경로를 나타냅니다. 기본값이 사용되지 않은 경우 경로 정보가 설치 경로와 다를 수 있습니다.

업그레이드 프로세스가 완료된 후 다음 문제를 고려하십시오.

* 업그레이드된 Snap Creator 데이터베이스에 ""진행 중""으로 표시된 일부 작업이 포함되어 있는 경우 업그레이드 프로세스가 완료된 후에도 상태는 동일하게 유지됩니다.
* 최신 Snap Creator 4.1의 기본 관리자는 Snap Creator 4.1의 관리자여야 합니다.
+
4.1.x 사용자가 관리자가 아닌 경우 업그레이드에서는 4.1.x 사용자에게 운영자 역할을 할당합니다.

+
.. Snap Creator 서비스를 아직 중지하지 않은 경우 중지하십시오.
+
서비스 중단에 대한 자세한 내용은 이 항목 앞부분의 세부 정보를 참조하십시오.

.. Start * > * Programs * > * Snap Creator * > * Uninstall NetApp Snap Creator Framework * 를 선택하여 Snap Creator(Windows용)를 제거합니다.
+
자세한 내용은 Windows에서 Snap Creator 제거에 대한 정보를 참조하십시오.

.. 최신 Snap Creator Server를 설치합니다.
+
자세한 내용은 Snap Creator Server on Windows 설치에 대한 정보를 참조하십시오.

.. 최신 Snap Creator Server를 설치할 때 Snap Creator Server를 서비스로 시작하도록 선택한 경우 서비스를 중지합니다.
+
서비스 중단에 대한 자세한 내용은 이 항목 앞부분의 세부 정보를 참조하십시오.

.. C:\Program Files\NetApp\Snap_Creator_Framework\scServer4.1.x\engine\snapcreator에서 최신 Snap Creator Server 데이터베이스 폴더를 삭제합니다.)
.. 백업된 Snap Creator 4.1 데이터베이스 디렉토리를 C:\Program Files\NetApp\Snap_Creator_Framework\scServer4.1.x\engine\snapcreator의 최신 위치로 복사합니다.
.. 백업된 Snap Creator 4.1 구성 디렉토리를 C:\Program Files\NetApp\Snap_Creator_Framework\scServer4.1.x\engine\configs의 최신 위치로 복사합니다.
.. 백업된 Snap Creator 4.1 로그 디렉토리를 C:\Program Files\NetApp\Snap_Creator_Framework\scServer4.1.x\engine\logs의 최신 위치로 복사합니다.
.. 명령 프롬프트를 열고 C:\Program Files\NetApp\Snap_Creator_Framework\scServer4.1.x\engine의 Snap Creator 설치 경로에서 디렉토리를 엔진 하위 디렉토리로 변경하십시오.
.. 다음 명령을 입력하여 Snap Creator를 업그레이드합니다. java-jar snapcreator.jar -upgrade




업그레이드 프로세스가 완료되면 다음 중 하나를 수행하여 Snap Creator Server 서비스를 시작합니다.

* 서비스 스냅인을 사용하여 서비스를 시작합니다.
* 명령 프롬프트에서 다음 명령을 입력합니다.
+
[listing]
----
sc start snapcreatorserverservice
----


또한 지정된 포트에서 로컬 호스트로 이동하여 Snap Creator Framework GUI 시작을 검증해야 합니다 .

HTTPS를 사용하여 연결해야 합니다. 그렇지 않으면 연결이 자동으로 HTTPS 연결로 리디렉션되지 않고 GUI가 작동하지 않습니다.
