---
permalink: installation/task_creating_a_snap_creator_user_for_clustered_ontap.html 
sidebar: sidebar 
keywords: creating, create, snap, center, user, ontap 
summary: 'Clustered Data ONTAP의 경우 Snap Creator를 위한 사용자를 생성해야 합니다. 하지만 생성하는 사용자 유형은 clustered Data ONTAP 버전에 따라 다릅니다. 두 유형의 사용자는 클러스터 사용자와 SVM(스토리지 가상 시스템) 사용자입니다.' 
---
= Clustered Data ONTAP용 Snap Creator 사용자 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Clustered Data ONTAP의 경우 Snap Creator를 위한 사용자를 생성해야 합니다. 하지만 생성하는 사용자 유형은 clustered Data ONTAP 버전에 따라 다릅니다. 두 유형의 사용자는 클러스터 사용자와 SVM(스토리지 가상 시스템) 사용자입니다.

Data ONTAP 버전에 대해 _Snap Creator Framework 관리 가이드_에 정의된 대로 적절한 역할을 가진 다음 사용자를 생성합니다.

* Clustered Data ONTAP 8.2 이전 Data ONTAP 릴리즈: 클러스터 및 SVM 사용자 생성
* Clustered Data ONTAP 8.2 이상: SVM 사용자 생성


보안을 강화하려면 Snap Creator에 적합한 Data ONTAP 사용자 및 역할을 생성해야 합니다. 또는 admin 또는 vsadmin과 같은 다른 사용자 계정을 사용할 수도 있습니다.

CLI를 사용하여 Snap Creator 역할을 생성하는 방법에 대한 자세한 내용은 관련 참조 를 참조하십시오.

두 사용자 모두 Data ONTAPI 라이브러리에 액세스해야 합니다. 또한 Clustered Data ONTAP에는 버전에 관계없이 관리 LIF도 필요합니다.

두 사용자는 서로 바꿔 사용할 수 없습니다. 예를 들어, 클러스터 사용자는 스냅샷 복사본 생성과 같은 특정 작업을 수행하는 데 필요한 API에 액세스할 수 없습니다. 이는 기본 클러스터 admin 계정을 사용하는 경우에도 마찬가지입니다. SVM 계정은 * vsadmin * 역할 또는 고객이 생성한 역할을 사용하여 Snap Creator가 제대로 작동하도록 해야 합니다.

이 절차는 Snap Creator를 사용하는 각 SVM 및 클러스터에서 한 번 수행해야 합니다.

사용 편의성을 위해 다음 지침은 admin 및 vsadmin 역할을 참조하지만 이러한 역할 이름을 사용자가 만든 역할로 바꿀 수 있습니다.


NOTE: 이 문서에서 직접 명령을 복사하여 붙여넣으면 안 됩니다. 줄 바꿈 및 하드 리턴으로 인해 잘못 전송된 문자 등의 오류가 발생할 수 있습니다. 이 절차의 명령을 복사하여 텍스트 편집기에 붙여 넣고 명령을 확인한 다음 CLI에 입력합니다.

. svm_nameSVM에서 적절한 역할(vsadmin 또는 사용자를 위해 생성된 역할)을 사용하여 SVM 사용자 svm_username01을 생성하고 다음 명령과 사용자 암호를 입력하여 ONTAPI 라이브러리에 액세스할 수 있도록 합니다.
+
[listing]
----
security login create -username svm_username01
-vserver svm_name -application ontapi
-authmethod password -role vsadmin

Please enter a password for user 'svm_username01':
Please enter it again:
----
. _ (clustered Data ONTAP 8.2 이전 버전에만 해당) _ 다음 명령과 사용자 암호를 입력하여 클러스터 사용자를 생성합니다.
+
[listing]
----
security login create -username svm_username02
-vserver svm_clustername -application ontapi
-authmethod password -role admin

Please enter a password for user 'svm_username02':
Please enter it again:
----


* 관련 정보 *

xref:reference_cli_commands_for_creating_a_role_for_a_snap_creator_user_in_clustered_data_ontap.adoc[Clustered Data ONTAP에서 Snap Creator 사용자에 대한 역할을 생성하는 CLI 명령입니다]
