---
permalink: installation/task_installing_the_snap_creator_server_on_unix.html 
sidebar: sidebar 
keywords: installing, install, snap, creator, server, unix, unix-based 
summary: 'UNIX 플랫폼(AIX, HP-UX, Linux 및 Solaris)의 경우 Snap Creator 설치 프로세스는 Snap Creator 소프트웨어 패키지(Snap Creator Server와 Snap Creator Agent가 모두 포함된 .tar 파일)를 압축 해제하고, 설치 스크립트를 실행하고, 서비스를 시작하고, 포트의 유효성을 검사하는 과정으로 구성됩니다.' 
---
= UNIX 기반 시스템에 Snap Creator Server 설치
:icons: font
:imagesdir: ../media/


[role="lead"]
UNIX 플랫폼(AIX, HP-UX, Linux 및 Solaris)의 경우 Snap Creator 설치 프로세스는 Snap Creator 소프트웨어 패키지(Snap Creator Server와 Snap Creator Agent가 모두 포함된 .tar 파일)를 압축 해제하고, 설치 스크립트를 실행하고, 서비스를 시작하고, 포트의 유효성을 검사하는 과정으로 구성됩니다.

JRE 1.8 업데이트 72 이상이 설치되어 있어야 합니다.

설치를 수행하는 사람은 설치를 수행할 수 있는 충분한 액세스 권한과 권한이 있어야 합니다.


NOTE: 초기 설정을 수행하려면 루트 레벨 권한이 있어야 합니다.

Snap Creator Server의 기본 포트는 8443입니다. netstat 또는 이와 유사한 툴을 사용하여 사용하려는 네트워크 포트가 HTTPS를 지원하고 사용 가능하며 아직 사용 중이 아닌지 확인할 수 있습니다(예: UNIX 호스트의 경우 "netstat-nap | grep 8443"을 입력할 수 있음).

Snap Creator를 이미 다운로드해야 합니다.

UNIX 서비스(서버 및 에이전트) 기능은 Snap Creator Server 및 Snap Creator Agent에 대한 시작 스크립트를 제공합니다. 시작 스크립트는 UNIX 셸 스크립트(Bourne 셸)로 작성되며 Snap Creator가 지원하는 모든 UNIX 환경에서 실행되도록 설계되었습니다.

. 다운로드한 Snap Creatortar.gz 파일을 Snap Creator Server를 설치할 위치에 복사합니다.
+
.. 하위 디렉토리를 만듭니다. mkdir snap_creator_directoryCreate 하위 디렉토리를 만듭니다.
+
mkdir snap_creator_directory

+
[listing]
----
mkdir /SC_41
----
.. Snap Creatortar.gz 파일을 새로 생성된 디렉토리에 복사합니다.
+
[listing]
----
cp NetApp_Snap_Creator_Frameworkrelease-os.tar.gz
/snap_creator_directory
----
+
[listing]
----
cp NetApp_Snap_Creator_Framework4.1.0-Linux32.tar.gz
/SC_41
----


. Snap Creator Framework.tar 파일이 있는 디렉토리로 이동한 다음 파일을 추출합니다.
+

NOTE: UNIX 환경에 따라 tar 명령을 입력하기 전에 파일의 압축을 풀어야 할 수도 있습니다.

+
[listing]
----
cd snap_creator_directory
tar -xvf NetApp_Snap_Creator_Frameworkrelease-os.tar.gz
----
+
** Snap_creator_directory는 Snap Creator가 설치될 위치입니다.
** Release는 Snap Creator 소프트웨어 패키지의 최신 릴리즈입니다.
** OS는 운영 체제입니다.
+
[listing]
----
cd /sc_41
tar -xvf NetApp_Snap_Creator_Framework4.1.0-Linux32.tar.gz
----


+
그러면 Server 및 Agent 소프트웨어가 모두 추출됩니다. 일반적으로 Snap Creator Server만 구성됩니다. 일반적으로 에이전트는 다음 예와 같이 보호할 데이터베이스 또는 애플리케이션 서버에 상주합니다.

+
를 누릅니다

+
[listing]
----
NetApp_Snap_Creator_Framework4.1.0-Linux32.tar.gz  scServer4.1.0
scAgent4.1.0
----
. Snap Creator의 초기 설정을 수행합니다.
+
[listing]
----
cd scServer*
./snapcreator --setup
Welcome to the NetApp Snap Creator Framework release-version!
\#\#\# Installation options \#\#\#
01. NetApp Snap Creator Framework release-version Server
02. NetApp Snap Creator Framework release-version Remote CLI
Select install option (enter a number or "q" to quit):
----
+
Snap Creator 서버를 설치하려면 '01'을 입력하십시오.

+
** Option 01은 Snap Creator 사용자 및 암호를 구성하고, Snap Creator Server가 실행될 GUI 포트를 지정하고, 기타 매개 변수를 구성하여 Snap Creator Server의 초기 설정을 수행합니다.
** Option 02는 Snap Creator Server를 로컬 바이너리로 설정하고 로컬 시스템 CLI에서 원격 Snap Creator Server로 명령을 실행할 수 있도록 합니다.


. 여기에 y를 입력하여 최종 사용자 사용권 계약에 동의합니다.
+
[listing]
----
END USER LICENSE AGREEMENT
...the EULA displays...

Do you accept the End User License Agreement (y|n): <Enter y>

Enter controller serial number (Recommended): <OPTIONAL: Enter serial number for one of your storage controllers>
----
. 컨트롤러의 일련 번호를 입력합니다.
+
컨트롤러 일련 번호는 Snap Creator 속성 파일에 포함되며 지원 및 로그 출력에 포함됩니다. 이 정보를 사용하여 나중에 발생할 수 있는 문제를 해결할 수 있습니다.

. 서버 포트, 시스템 IP 및 Java 입력 용지함 경로를 입력한 다음 메시지를 계속 표시합니다.
+
[listing]
----
Enter Snap Creator server port [8443]: <Enter server port>

Enable job monitor (Y|N): <Enter Y>

Enter job monitor size, how many jobs to allow [100]: <Enter the number of jobs from 1-1000>
----
+

NOTE: 작업 모니터 크기 * 에 허용되는 최대 값은 10,000이지만 최대 크기는 1000입니다.

+
[listing]
----
Enter scServer Administrator Username: <Enter the Administrator username>
Enter password for snap_creator_administrator: <Enter the password>
Confirm password for snap_creator_administrator: <Enter the password again>

Enter JAVA Bin Path: /usr/java/default/bin
Enter Your System IP: 10.232.30.18
INFO: Updated NetApp Snap Creator Framework release-version
/install_path/scServerrelease-version/engine/etc/snapcreator.properties
INFO: Updated NetApp Snap Creator Framework release-version
/install_path/scServerrelease-version/bin/scServer

INFO: To start scServer please do the following:

/install_path/scServerrelease-version/bin/scServer start

INFO: To access NetApp Snap Creator Framework release-version GUI goto https://hostname:gui_port
----
. Snap Creator Framework Server를 시작합니다.
+
[listing]
----
/install_path/scServerrelease-version/bin/scServer start
Checking Status of scServer:
Running
----
. 지정된 포트에서 로컬 호스트(예: https://10.12.123.123:8443)[].
+
HTTPS를 사용하여 연결해야 합니다. 그렇지 않으면 GUI가 작동하지 않습니다.

+
통신이 방화벽을 통과하는 경우 네트워크 포트를 엽니다.



* 관련 정보 *

xref:task_installing_java_on_snap_creator_hosts.adoc[Snap Creator 호스트에 Java 설치]

xref:task_downloading_the_snap_creator_software.adoc[Snap Creator 소프트웨어 다운로드]
