---
permalink: sap-hana-ops/concept_considerations_for_backing_up_sap_hana_systems.html 
sidebar: sidebar 
keywords: considerations, backup, backing, up, sap, hana 
summary: SAP HANA 관리자는 신뢰할 수 있는 수준의 서비스를 제공하여 백업으로 인한 다운타임 또는 성능 저하를 최소화해야 합니다. 
---
= SAP HANA 시스템 백업을 위한 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SAP HANA 관리자는 신뢰할 수 있는 수준의 서비스를 제공하여 백업으로 인한 다운타임 또는 성능 저하를 최소화해야 합니다.

SAP HANA 관리자는 이러한 수준의 서비스를 제공하기 위해 다음과 같은 분야에서 어려움을 겪고 있습니다.

* 운영 SAP 시스템에 대한 성능 영향
+
백업 중에 데이터베이스 서버, 스토리지 시스템 및 스토리지 네트워크에 많은 로드가 발생하기 때문에 백업은 일반적으로 운영 SAP 시스템에 상당한 성능 영향을 미칩니다.

* 백업 윈도우 단축
+
SAP 시스템에서 입출력 또는 배치 작업이 적은 경우에만 백업을 생성할 수 있습니다. SAP 시스템이 항상 활성 상태일 때는 백업 윈도우를 정의하기가 매우 어렵습니다.

* 급속하게 증가하는 데이터
+
백업 시간이 단축되면서 데이터가 빠르게 증가할수록 백업 인프라에 대한 지속적인 투자가 발생합니다. 테이프 드라이브 증가, 새로운 테이프 드라이브 기술, 스토리지 네트워크 속도 향상 등이 그 예입니다. 또한 데이터베이스가 커질수록 백업용 테이프 미디어 또는 디스크 공간이 늘어납니다. 증분 백업은 이러한 문제를 해결할 수 있지만 복원 프로세스가 매우 느려지므로 일반적으로 허용되지 않습니다.

* 가동 중지 시간의 비용 증가
+
SAP 시스템의 계획되지 않은 다운타임은 비즈니스에 항상 재정적인 영향을 미칩니다. 계획되지 않은 다운타임의 중요한 부분은 장애 발생 시 SAP 시스템을 복원 및 복구하는 데 필요한 시간입니다. 백업 및 복구 아키텍처는 허용되는 RTO(복구 시간 목표)를 기반으로 설계되어야 합니다.

* 백업 및 복구 시간입니다
+
SAP 업그레이드 프로젝트에는 백업 및 복구 시간이 포함됩니다. SAP 업그레이드를 위한 프로젝트 계획에는 항상 SAP 데이터베이스의 백업이 3개 이상 포함됩니다. 이러한 백업을 수행하는 데 소요되는 시간은 업그레이드 프로세스에 사용할 수 있는 총 시간을 줄여 줍니다. 백업 및 복구 여부는 일반적으로 이전에 생성된 백업에서 데이터베이스를 복원 및 복구하는 데 필요한 시간에 따라 결정됩니다. 매우 빠르게 복원하는 옵션은 시스템을 이전 상태로 복원하는 것이 아니라 업그레이드 중에 발생할 수 있는 문제를 해결하는 데 더 많은 시간을 제공합니다.


