---
permalink: sap-hana-ops/reference_troubleshooting.html 
sidebar: sidebar 
keywords: troubleshooting 
summary: 문제 해결 섹션에서는 오류 코드, 오류 메시지에 대한 정보를 제공하며 문제 해결을 위한 설명 또는 해결 방법을 제공합니다. 
---
= 문제 해결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
문제 해결 섹션에서는 오류 코드, 오류 메시지에 대한 정보를 제공하며 문제 해결을 위한 설명 또는 해결 방법을 제공합니다.

다음 표에는 SAP HANA 플러그인 오류 메시지가 나와 있습니다.

|===
| 오류 코드 | 오류 메시지 | 설명/해상도 


 a| 
HDB-00001
 a| 
제공된 구성 매개 변수를 사용하여 hdbsql 명령을 실행하기 위한 액세스 가능한 HANA 노드를 찾을 수 없습니다. 구성에서 HANA 설정을 확인하고 업데이트하고 다시 시도하십시오.
 a| 
HANA 노드가 실행되고 있고 연결할 수 있으며 제공된 인스턴스 번호가 올바른지 확인합니다.



 a| 
HDB-00002
 a| 
[$sid]에 대한 데이터베이스 스냅샷을 생성하지 못했습니다.
 a| 
HANA 데이터베이스 스냅샷이 이미 데이터베이스에 생성되었는지 확인합니다. 이미 생성된 경우 HANA 데이터베이스 스냅샷을 삭제하거나 일시 중지 해제 작업을 실행합니다. 아직 생성되지 않은 경우 로그에서 다른 오류 메시지 및 세부 정보를 확인합니다.



 a| 
HDB-00003
 a| 
[$sid]에 대한 데이터베이스 스냅샷을 삭제하지 못했습니다.
 a| 
HANA 데이터베이스 스냅샷이 이미 삭제되었는지 확인합니다. 예 인 경우 이 오류를 무시할 수 있습니다. 아니요 인 경우 SAP HANA 플러그인 매개 변수를 확인하고 노드에 연결할 수 있고 제공된 인스턴스 번호가 올바른지 확인합니다.



 a| 
HDB-00004
 a| 
연결이 거부되어 인스턴스 [$instance]이(가) 있는 [$HANA_NODE] 노드에 연결하지 못했습니다.
 a| 
메시지에 표시된 인스턴스가 있는 HANA 노드에 연결할 수 없습니다. 플러그인에서 다른 노드에서 hdbsql 명령을 실행하려고 하므로 이는 경고일 수 있습니다. 작업을 성공적으로 수행했는지 로그를 확인합니다.



 a| 
HDB-00005
 a| 
데이터베이스 [$sid]에 이미 스냅샷이 있습니다!
 a| 
HANA 데이터베이스 스냅샷이 이미 데이터베이스에 있습니다. 이 문제를 해결하려면 HANA 데이터베이스 스냅샷을 삭제하거나 일시 중지 해제 작업을 실행하십시오.



 a| 
HDB-00006
 a| 
호스트 이름 [$HANA_NODE]을(를) 확인할 수 없습니다.
 a| 
HANA 노드 호스트 이름을 확인할 수 없습니다. DNS 서버 또는 ETC 호스트 항목을 확인합니다.



 a| 
HDB-00007
 a| 
사용자 이름 또는 암호가 잘못되었습니다. 자격 증명을 확인하고 다시 시도하십시오.
 a| 
HANA 데이터베이스에 대해 제공된 사용자 이름과 암호가 잘못되었습니다. 구성 파일의 항목을 수정하고 다시 시도하십시오.



 a| 
HDB-00008
 a| 
[$HANA_NODE]에서 [$hdbsql_cmd] 명령을 실행하지 못했습니다.
 a| 
플러그인이 구성에 제공된 모든 HANA 노드에서 hdbsql 명령을 실행하지 못했습니다. HANA 노드 및 인스턴스 매개 변수를 확인하고 하나 이상의 HANA 노드가 가동되어 있고 연결할 수 있는지 확인합니다.



 a| 
HDB-00009
 a| 
HANA [$info]를 찾을 수 없습니다.
 a| 
SAP HANA 플러그인 SCDUMP 작업이 HANA 데이터베이스에서 특정 정보를 검색할 수 없습니다. HANA 노드 및 인스턴스 매개 변수를 확인하고 하나 이상의 HANA 노드가 가동되어 있고 연결할 수 있는지 확인합니다.



 a| 
HDB-00010
 a| 
OS 정보를 수집하지 못했습니다.
 a| 
Windows 환경에서 OS 정보 수집에 실패했습니다. Windows에서는 SAP HANA 플러그인이 지원되지 않습니다. 대신 SLES 운영 체제를 사용하십시오.



 a| 
HDB-00011
 a| 
OS 정보를 수집하지 못했습니다.
 a| 
Snap Creator가 SCDUMP 작업에 대한 OS 정보를 수집할 수 없습니다. 상담원 구성 파일을 확인하고 설정을 수정하십시오.



 a| 
HDB-00012
 a| 
SnapDrive 정보를 수집하지 못했습니다.
 a| 
SAP HANA 플러그인은 NFS 환경에서만 지원됩니다. HANA 데이터베이스에 대한 구성에 SnapDrive가 활성화되어 있습니다. 구성 파일에 SnapDrive=를 설정합니다.



 a| 
HDB-00013
 a| 
hana_nodes 매개 변수가 설정되지 않았습니다. 구성 파일에서 HANA 설정을 확인합니다.
 a| 
SAP HANA 플러그인에 필요한 HANA 노드(HANA_nodes) 매개 변수 매개 변수를 설정하고 다시 시도하십시오.



 a| 
HDB-00014
 a| 
제공된 구성 매개 변수를 사용하여 hdbsql명령을 실행하기 위한 액세스 가능한 HANA 노드를 찾을 수 없습니다. 구성에서 HANA 설정을 확인하고 업데이트하고 다시 시도하십시오.
 a| 
HANA 노드가 실행되고 있고 연결할 수 있으며 제공된 인스턴스 번호가 올바른지 확인합니다.



 a| 
HDB-00015
 a| 
hana_instance 매개 변수가 설정되지 않았습니다. 구성 파일에서 HANA 설정을 확인합니다.
 a| 
SAP HANA 플러그인에 필요한 HANA 인스턴스(HANA_Instance) 매개 변수 매개 변수를 설정하고 다시 시도하십시오.



 a| 
HDB-00016
 a| 
hana_password 매개 변수가 설정되지 않았습니다. 구성 파일에서 HANA 설정을 확인합니다.
 a| 
SAP HANA 플러그인에 필요한 HANA 암호(HANA_password) 매개 변수 매개 변수를 설정하고 다시 시도하십시오.



 a| 
HDB-00017
 a| 
hdbsql 경로, hana_HDBSQL_CMD 매개 변수 값이 잘못되었습니다!
 a| 
다음 중 하나가 발생했습니다.

* hdbsql 경로를 제공하지 않았습니다
* 제공된 hdbsql 경로가 잘못되었습니다.


Snap Creator Agent가 설치된 관리 호스트에 HANA hdbsql 클라이언트가 설치되어 있는지 확인하고 HANA 매개 변수에서 hdbsql 바이너리의 올바른 경로를 제공한 다음 다시 시도하십시오.

|===