---
permalink: sap-hana-ops/task_configuring_sap_hana_for_san_environments.html 
sidebar: sidebar 
keywords: configuring, sap, hana, san, environments 
summary: '데이터 백업을 구성한 후에는 SAP HANA 시스템이 파이버 채널 SAN(Storage Area Network)을 사용하여 스토리지 컨트롤러에 연결된 환경에서 Snap Creator 구성 파일에 새로운 명령을 추가해야 합니다.' 
---
= SAN 환경을 위한 SAP HANA 구성
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 백업을 구성한 후에는 SAP HANA 시스템이 파이버 채널 SAN(Storage Area Network)을 사용하여 스토리지 컨트롤러에 연결된 환경에서 Snap Creator 구성 파일에 새로운 명령을 추가해야 합니다.

SAP HANA 내의 Snap Creator에 의해 글로벌 동기화된 백업 저장점이 트리거되면 SAP HANA가 /HANA/data/SID/mnt00001/hdb00001/snapshot_DataBackup_0_1 파일을 쓸 때 마지막 단계가 발생합니다. 이 파일은 스토리지의 데이터 볼륨에 포함되어 있으므로 스토리지 스냅샷 복사본의 일부입니다. 백업이 복원되는 경우 복구를 수행할 때 이 파일은 필수입니다. Linux 호스트에서 'X' 파일 시스템(XFS)을 사용한 메타데이터 캐싱으로 인해 파일이 스토리지 계층에서 즉시 표시되지 않습니다. 메타데이터 캐싱을 위한 표준 XFS 구성은 30초입니다.

Snap Creator 내에서 XFS 메타 데이터 캐시가 디스크 계층으로 플러시될 때까지 대기하는 사후 애플리케이션 일시 중지 명령을 추가해야 합니다.

다음 명령을 사용하여 메타데이터 캐싱 구성을 확인할 수 있습니다.

[listing]
----
stlrx300s8-2:/ # sysctl -A | grep xfssyncd_centisecs
fs.xfs.xfssyncd_centisecs = 3000
----
. 구성 파일(install_path/scServerversion_number/engine/configs)에서 다음 예와 같이 Post 명령 섹션에 /bin/sleep 명령을 추가합니다.
+
[listing]
----
############################################################
#     Post Commands      ############################################
POST_NTAP_DATA_TRANSFER_CMD01=
POST_APP_QUIESCE_CMD01=/bin/sleep 60
POST_CLONE_CREATE_CMD01=
----
+

NOTE: fs.xfs.xfssyncd_centisecs 매개 변수의 값에 두 배인 대기 시간을 허용해야 합니다. 예를 들어 기본값 30초에서는 sleep 명령을 60초로 구성해야 합니다.


