---
permalink: domino-ops/concept_backup_operations_using_domino_plug_in.html 
sidebar: sidebar 
keywords: domino, ibm, backup, operations, ibm, understanding 
summary: 다른 백업 기술과 달리 IBM Domino 플러그인을 사용하면 백업 작업 중에 데이터를 데이터베이스에 쓸 수 있습니다. 이 기능을 사용하면 백업 작업 중에 변경 내용을 데이터베이스에 기록하여 변경 정보라는 임시 디렉토리에 백업함으로써 애플리케이션 데이터와 일관성을 유지할 수 있습니다. 복원 시 스냅샷 복사본에서 데이터를 복원한 후에 변경 내용이 데이터베이스에 적용됩니다. 
---
= IBM Domino 플러그인 백업 작업 이해
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다른 백업 기술과 달리 IBM Domino 플러그인을 사용하면 백업 작업 중에 데이터를 데이터베이스에 쓸 수 있습니다. 이 기능을 사용하면 백업 작업 중에 변경 내용을 데이터베이스에 기록하여 변경 정보라는 임시 디렉토리에 백업함으로써 애플리케이션 데이터와 일관성을 유지할 수 있습니다. 복원 시 스냅샷 복사본에서 데이터를 복원한 후에 변경 내용이 데이터베이스에 적용됩니다.

백업 작업 중에 데이터베이스 파일이 백업 모드라고 합니다. Snap Creator 프레임워크에서 이러한 파일을 "중지"라고 부르지만, 이는 그렇지 않습니다. 스냅샷 복사본이 만들어지는 동안 데이터는 파일에 계속 쓰입니다.

상위 단계는 다음과 같습니다.

. 백업할 볼륨의 데이터베이스, 템플릿 및 메일박스 목록을 표시합니다.
. 한 번에 하나의 데이터베이스씩 백업 모드로 파일을 저장합니다.
. 일관되지 않거나 손상된 데이터베이스가 있는지 확인합니다.
+

NOTE: 단계에서 설명한 대로 오류가 발생해도 플러그인이 백업 작업을 계속 진행하도록 할 수 있습니다 link:task_using_the_gui_to_create_a_configuration_file.md#STEP_AA41331683A24598B7845367CB967F99["Task_using_the_GUI_to_create_a_configuration_file.md#step_AA41331683A24598B7845367CB967F99"].

. 각 볼륨의 스냅샷 복사본을 만듭니다.
. Domino 트랜잭션 로깅을 사용하는 경우 최신 복원 작업에 사용할 Domino 트랜잭션 로그의 아카이브 복제본입니다.
. 한 번에 한 데이터베이스씩 백업 모드에서 파일을 꺼냅니다.
. 파일이 changeinfo 디렉터리에 백업 모드로 전환된 이후에 데이터베이스에 대한 변경 내용을 기록합니다.

