---
permalink: domino-ops/concept_domino_database_restore_overview.html 
sidebar: sidebar 
keywords: domino, ibm, restore, restoring, databases, understanding, snapmirror, snapvault, destination, directories 
summary: IBM Domino 플러그인은 데이터베이스가 저장된 볼륨의 스냅샷 복사본에서 데이터베이스 파일을 복원합니다. 스냅샷 복원이 완료되면 플러그인이 changeinfo 디렉토리에 기록된 모든 변경 사항을 적용합니다. 
---
= 데이터베이스를 복원하는 중입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
IBM Domino 플러그인은 데이터베이스가 저장된 볼륨의 스냅샷 복사본에서 데이터베이스 파일을 복원합니다. 스냅샷 복원이 완료되면 플러그인이 changeinfo 디렉토리에 기록된 모든 변경 사항을 적용합니다.



== SnapMirror 및 SnapVault 복원 작업 이해

Snap Creator를 사용하여 데이터의 SnapMirror 복사본을 복원할 수는 없습니다. 미러 복제본을 복구하려면 먼저 미러를 해제한 다음 데이터를 수동으로 복구해야 합니다. 자세한 내용은 를 참조하십시오 link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-sm-ic-fr/home.html["ONTAP 9 볼륨 재해 복구 익스프레스 가이드"].

보조 스토리지에서 SnapVault 복사본을 복원할 때는 시점 볼륨 복원만 가능합니다. 최신 볼륨 복원 또는 단일 파일 복원을 수행할 수 없습니다. 먼저 보조 스토리지에서 운영 스토리지로 복원하여 이러한 제한 사항을 해결할 수 있습니다. 그런 다음 운영 스토리지에서 최신 볼륨 복원 또는 단일 파일 복원을 필요에 따라 수행할 수 있습니다.



== 대상 디렉토리 이해

볼륨 복원 및 단일 파일 복원에는 일반적으로 서로 다른 대상 디렉토리가 있습니다. 백업 및 복원 구성 파일의 Data Restore Directory 매개 변수에서 대상 디렉토리를 지정합니다(단계 참조) link:task_using_the_gui_to_create_a_configuration_file.md#STEP_E6C507729B3647FD8B2E8D0818F22D3B["Task_using_the_GUI_to_create_a_configuration_file.md#step_E6C507729B3647FD8B2E8D0818F22D3B"]):

* 볼륨 복구의 경우 데이터 복원 디렉토리를 Domino 데이터 디렉토리로 설정해야 합니다.
* 단일 파일 복구의 경우 데이터 복원 디렉토리를 Domino 데이터 볼륨의 하위 디렉토리로 설정해야 합니다.


즉, 대체 복원 유형을 사용하는 경우 각 복원 유형에 대해 올바른 설정을 가리키도록 데이터 복원 디렉터리를 수정해야 합니다. 그렇지 않으면 변경 정보가 올바르게 적용되지 않으며 데이터가 복원하려는 데이터베이스 상태와 일치하지 않습니다. 물론 원하는 경우 볼륨 및 단일 파일 복원을 위한 다양한 구성을 생성할 수 있습니다.



== 복원을 실행할 위치

한 가지 예외를 제외하고 Snap Creator GUI 또는 Snap Creator CLI를 사용하여 데이터베이스를 복원할 수 있습니다. SAN 환경에서 단일 파일 복구의 경우 에 설명된 대로 CLI를 사용해야 합니다 xref:concept_single_file_restore_in_fc_iscsi_environments.adoc[SAN 환경에서 단일 파일 복원 수행].


NOTE: 이 가이드에서는 SAN 환경에서 단일 파일 복원에만 CLI를 사용하는 방법을 보여 줍니다. 그렇지 않으면 GUI를 사용하여 데이터베이스를 복원하는 방법을 보여줍니다. CLI 사용 방법에 대한 자세한 내용은 를 참조하십시오 https://library.netapp.com/ecm/ecm_download_file/ECMP12395422["Snap Creator Framework 4.1.2 관리 가이드"].

* 관련 정보 *

link:task_performing_point_in_time_volume_restore.adoc["볼륨 복원 수행"]


