---
permalink: domino-ops/concept_use_meta_data_volumes_setting_to_back_up_the_changeinfo_directory.html 
sidebar: sidebar 
keywords: domino, ibm, backing up, backup, changeinfo, directory 
summary: changeinfo 디렉토리를 백업하려는 경우 디렉토리가 포함된 볼륨을 메타데이터 볼륨으로 구성해야 합니다. 이렇게 하면 데이터베이스 파일의 스냅샷 복사본을 생성한 후 IBM Domino 플러그인에서 changeinfo 볼륨의 스냅샷 복사본을 생성합니다. 
---
= changeinfo 디렉토리를 백업하는 중입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
changeinfo 디렉토리를 백업하려는 경우 디렉토리가 포함된 볼륨을 메타데이터 볼륨으로 구성해야 합니다. 이렇게 하면 IBM Domino 플러그인에서 데이터베이스 파일의 스냅샷 복사본을 생성하는 _after_changeinfo 볼륨의 스냅샷 복사본을 생성합니다.

구성 파일을 만들 때 changeinfo 볼륨을 백업할 볼륨으로 이미 식별했어야 합니다. 자세한 내용은 단계를 참조하십시오 link:task_using_the_gui_to_create_a_configuration_file.md#STEP_2036E43A6921415985798979F2226786["GUI를 사용하여 구성을 생성하는 작업"].

구성 파일에서 meta_data_volume 매개 변수를 사용하여 changeinfo 볼륨을 메타데이터 볼륨으로 식별합니다. GUI에서 매개변수를 사용할 수 없습니다.

. 텍스트 편집기에서 구성 파일을 엽니다.
+
구성 파일은 Snap Creator 설치 디렉토리의 프로파일 이름이 인 하위 디렉토리에 있습니다. 예를 들어, Windows 호스트에서 C:\Program Files\NetApp\Snap_Creator_Framework\scServer4.1.x\engine\configs\Domino\Fuji15.conf는 프로파일의 이름이고 Fuji15.conf는 구성 파일의 이름입니다.

. meta_data_volume 매개 변수에 changeinfo 볼륨의 이름을 입력합니다.
+
볼륨 매개 변수에 changeinfo 볼륨이 이미 나열되어 있어야 합니다.

+
다음 예에서는 Fuji15_DomChangeInfo를 메타데이터 볼륨으로 구성하는 방법을 보여 줍니다.

+
[listing]
----
VOLUMES=domino_vserver:Fuji15_DomDAOS,Fuji15_DomChangeInfo,
Fuji15_DomTxn,Fuji15_DomData
META_DATA_VOLUME=domino_vserver:Fuji15_DomChangeInfo
----

