---
permalink: domino-ops/concept_restore_operations_using_domino_plug_in.html 
sidebar: sidebar 
keywords: domino, ibm, understanding, plug-in, restore 
summary: IBM Domino 플러그인은 데이터베이스가 저장된 볼륨의 스냅샷 복사본에서 데이터베이스 파일을 복원합니다. 스냅샷 복원 작업이 완료되면 플러그인은 changeinfo 디렉토리에 기록된 모든 변경 사항을 적용합니다. 
---
= IBM Domino 플러그인 복구 작업 이해
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IBM Domino 플러그인은 데이터베이스가 저장된 볼륨의 스냅샷 복사본에서 데이터베이스 파일을 복원합니다. 스냅샷 복원 작업이 완료되면 플러그인은 changeinfo 디렉토리에 기록된 모든 변경 사항을 적용합니다.

상위 단계는 다음과 같습니다.

. 스냅샷 복사본에서 데이터베이스 파일을 복원합니다.
. changeinfo 디렉토리에 기록된 변경 사항을 적용합니다.
. 사용 가능한 경우 트랜잭션 로그 정보를 적용합니다.




== 복원 옵션

플러그인은 다양한 복원 옵션을 제공합니다.

|===


| 복원 유형 | 설명 


 a| 
볼륨 복원(시점)
 a| 
스냅샷 복사본 시점의 전체 볼륨을 해당 상태로 복원합니다.



 a| 
볼륨 복원(최신)
 a| 
스냅샷 복사본 시점의 전체 볼륨을 해당 상태로 복원한 다음 Domino 트랜잭션 로그를 최신 복사본으로 전달합니다.



 a| 
볼륨 복원(최신 선택 가능)
 a| 
Snapshot 복사본 시점의 전체 볼륨을 해당 상태로 복원하고 나서 Domino 트랜잭션 로그를 지정된 시간으로 전달합니다.



 a| 
단일 파일 복원(시점)
 a| 
스냅샷 복사본 시점의 단일 파일 상태로 복원(NFS만 해당)



 a| 
단일 파일 복원(최신)
 a| 
스냅샷 복사본 시점의 단일 파일로 복원한 다음 Domino 트랜잭션 로그를 최신 복사본(NFS만 해당)으로 전달합니다.



 a| 
단일 파일 복원(최신 선택 가능)
 a| 
스냅샷 복사본 시점의 단일 파일로 복원한 다음 Domino 트랜잭션 로그를 지정된 시간(NFS만 해당)으로 전달합니다.

|===
* 참고: * 최신 복원 및 선택 가능한 최신 복원의 경우 Domino 트랜잭션 로깅을 사용하도록 설정해야 합니다.

트랜잭션 로그는 앞으로만 재생할 수 있습니다. 스냅샷 복사본이 생성되기 전에 시간을 선택하면 복원 오류가 발생합니다.
