---
permalink: domino-ops/task_using_snapdrive_for_windows_to_mount_snapshot_copy.html 
sidebar: sidebar 
keywords: domino, ibm, using, snapdrive, mount, snapshot, copy 
summary: SnapDrive를 사용하여 복원하려는 파일의 스냅샷 복사본을 마운트할 수 있습니다. 그런 다음 파일을 데이터 복원 디렉터리에 수동으로 복사할 수 있습니다. 
---
= SnapDrive를 사용하여 스냅샷 복사본 마운트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive를 사용하여 복원하려는 파일의 스냅샷 복사본을 마운트할 수 있습니다. 그런 다음 파일을 데이터 복원 디렉터리에 수동으로 복사할 수 있습니다.

다음 절차에서는 Windows용 SnapDrive를 사용하여 Windows Server 2008 호스트에 스냅샷 복사본을 마운트하는 방법을 보여 줍니다. Windows용 SnapDrive 및 Snap Creator 에이전트가 호스트에서 실행되고 있어야 합니다.

. 서버 관리자에서 * 스토리지 * > * SnapDrive * > * Physical_server_name * > * 디스크 * 를 클릭합니다.
. 디스크 식별 창에서 복원하려는 파일 복사본이 들어 있는 스냅샷 복사본으로 이동한 다음 오른쪽 클릭 메뉴에서 * Connect Disk * 를 선택합니다.
+
디스크 연결 마법사가 열립니다.

+
디스크 연결 마법사에서 * 다음 * 을 클릭하여 다음 페이지로 이동합니다. 이전 페이지로 돌아가려면 * 뒤로 * 를 클릭합니다.

+

TIP: 스냅샷 복사본의 이름을 기록합니다. 파일을 데이터 복원 디렉터리에 복사할 때 이름이 필요합니다.

. 스토리지 시스템 이름, LUN 경로 및 이름 제공 페이지에서 선택적으로 LUN에 대한 설명 텍스트를 입력합니다.
. LUN 유형 선택 페이지에서 기본값을 그대로 둡니다.
. LUN 속성 선택 페이지에서 스냅샷 복사본의 드라이브 문자 또는 마운트 지점을 선택합니다.
. iSCSI 이니시에이터/FC HBA(호스트 버스 어댑터) 페이지에서 iSCSI 이니시에이터 또는 FC HBA(호스트 버스 어댑터)를 선택합니다.
. 관리 유형 페이지에서 LUN에 매핑하는 데 사용할 관리 유형(자동 또는 수동)을 선택합니다.
. Finish * 를 클릭하여 스냅샷 복사본을 지정된 마운트 지점에 마운트합니다.

