---
permalink: domino-ops/task_running_snap_creator_by_using_the_custom_action.html 
sidebar: sidebar 
keywords: domino, ibm,using, use, snap, creator, custom, action complete, restore 
summary: Snap Creator 맞춤형 작업을 사용하면 Snap Creator 외부에서 시작된 복원을 완벽하게 처리할 수 있습니다. 
---
= Snap Creator 사용자 지정 작업을 사용하여 복원 처리 완료
:icons: font
:imagesdir: ../media/


[role="lead"]
Snap Creator 맞춤형 작업을 사용하면 Snap Creator 외부에서 시작된 복원을 완벽하게 처리할 수 있습니다.

이 작업은 Snap Creator CLI에서만 수행할 수 있습니다.

. Snap Creator CLI에서 다음 명령을 입력합니다. snapcreator.exe -- action custom -- server -port port port -- user user -- passwd password -- profile profile -- config config config config -- params snapname=snapshot_name datapath=datapath restoretype=u2m | su2m | sudletime="MM/DD/YYYY HH:MM:SS" disablepoplication=Y
+
위치

+
** server는 Snap Creator Server의 호스트 이름 또는 IP 주소입니다.
** port는 Snap Creator Server가 실행 중인 포트 번호입니다.
** user 는 Snap Creator 사용자의 이름입니다.
** 암호는 Snap Creator 사용자의 암호입니다.
+

NOTE: 일반 텍스트로 암호를 입력하지 않으려면 -passwd 옵션을 생략할 수 있습니다. Snap Creator는 명령을 실행할 때 암호를 묻는 메시지를 표시합니다

** Profile은 Snap Creator 프로파일의 이름입니다.
** Config는 Snap Creator 구성 파일의 이름입니다.
** snapshot_name 은 파일을 복원할 스냅샷 복사본의 이름입니다.
** datapath는 파일을 복원하려는 디렉토리의 경로 이름입니다.
** Restoretype은 수행할 복원 유형입니다.
+
*** u2m 는 최신 복원을 수행합니다.
*** SU2m 는 선택 가능한 최신 복원을 수행합니다. Domino 트랜잭션 로그를 재생할 날짜와 시간을 -restoretime 옵션에서 MM/DD/YYYY HH:MM:SS 형식으로 지정합니다. 예: 2014년 1월 23일 12:45:00


** 복제 해제는 Domino 복제를 비활성화합니다.
+
*** Domino 복제를 허용하려면 N(기본값)을 입력합니다. 플러그인은 복구된 데이터베이스 파일에 기존 Domino 복제본 ID를 사용합니다.
+

NOTE: Domino 복제를 허용하는 다른 방법은 이 매개 변수를 명령 밖으로 나가는 것입니다.

*** Domino 복제를 사용하지 않으려면 Y를 입력합니다. 플러그인은 복구된 데이터베이스 파일에 대한 새 Domino 복제본 ID를 설정합니다. 참고: 명령에 -verbose를 추가하면 복원 작업에 대한 추가 정보가 표시됩니다. 그렇지 않으면 명령 실행이 완료되면 명령 프롬프트로 즉시 반환됩니다.




+
[listing]
----
snapcreator.exe --action custom --server Tampico --port 8443
--user admin --profile Domino --config Nantes
--params snapname=Nantes-Test_Policy_20140123121459
datapath=F:\Domino\data\restore\mail\t04.nsf
restoretype=su2m restoretime="01/23/2014 12:45:00"
disablereplication=y
----

