---
permalink: domino-ops/task_performing_point_in_time_volume_restore.html 
sidebar: sidebar 
keywords: domino, ibm, volume, restore 
summary: IBM Domino 플러그인을 사용하면 모든 주요 스토리지 유형에 대해 시점, 최신 또는 선택 가능한 최신 볼륨 복원을 수행할 수 있습니다. 
---
= 볼륨 복원 수행
:icons: font
:imagesdir: ../media/


[role="lead"]
IBM Domino 플러그인을 사용하면 모든 주요 스토리지 유형에 대해 시점, 최신 또는 선택 가능한 최신 볼륨 복원을 수행할 수 있습니다.

다음 사항을 확인하십시오.

* 구성 파일의 데이터 복원 디렉토리를 Domino 데이터 디렉토리로 설정합니다.
* Domino 서버를 중지합니다.


볼륨 복원 옵션은 다음과 같습니다.

|===
| 복원 유형 | 설명 


 a| 
볼륨 복원(시점)
 a| 
스냅샷 복사본 시점의 전체 볼륨을 해당 상태로 복원합니다.



 a| 
볼륨 복원(최신)
 a| 
스냅샷 복사본 시점의 전체 볼륨을 해당 상태로 복원한 다음 Domino 트랜잭션 로그를 최신 복사본으로 전달합니다.



 a| 
볼륨 복원(최신 선택 가능)
 a| 
Snapshot 복사본 시점의 전체 볼륨을 해당 상태로 복원하고 나서 Domino 트랜잭션 로그를 지정된 시간으로 전달합니다.

|===

NOTE: 시점 복구를 최신 상태로 선택할 수 있으려면 Domino 트랜잭션 로깅을 활성화해야 합니다.

트랜잭션 로그는 앞으로만 재생할 수 있습니다. 스냅샷 복사본이 생성되기 전에 시간을 선택하면 복원 오류가 발생합니다.

. 프로파일 및 구성 창에서 구성 파일을 선택하고 * 작업 * > * 복원 * 을 클릭합니다.
+
Restore * 를 선택하면 Snap Creator Framework Restore 마법사가 자동으로 시작됩니다. 복원 마법사 전체에서 다음 페이지로 이동하려면 * 다음 * 을 클릭합니다. 이전 페이지로 돌아가려면 * 뒤로 * 를 클릭합니다.

+

NOTE: SnapVault 복제본에서 복구하는 경우 운영 또는 보조 스토리지에서 복구하라는 메시지가 표시됩니다. 선택 사항은 에 설명된 제한 사항을 처리하는 방법에 따라 달라집니다 link:concept_domino_database_restore_overview.html["데이터베이스를 복원하는 중입니다"].

. Restore details 페이지에서 복구 세부 정보를 지정합니다.
+
|===
| 이 필드의 내용... | 수행할 작업... 


 a| 
컨트롤러/Vserver 이름
 a| 
복원할 스토리지 시스템에서 SVM을 선택합니다.



 a| 
볼륨 이름을 복원합니다
 a| 
복원할 볼륨을 선택합니다.



 a| 
정책
 a| 
복원할 백업에 대한 정책을 선택합니다.



 a| 
Snap Creator Snapshot 복사본/모든 스냅샷 복사본
 a| 
기본값을 그대로 둡니다.



 a| 
스냅샷 복사본 이름을 복원합니다
 a| 
복원할 스냅샷 복사본을 선택합니다.



 a| 
복원 유형
 a| 
볼륨 복원 * 을 선택합니다.

|===
. 다음 페이지에서 볼륨 복원 유형을 지정합니다.
+
|===
| 이 필드의 내용... | 수행할 작업... 


 a| 
복원 유형
 a| 
볼륨 복원 유형을 클릭합니다. 분 단위 * 선택 가능 * 을 선택하면 새 필드가 표시되며, 여기서 Domino 트랜잭션 로그를 전달할 날짜와 시간을 지정할 수 있습니다. Snap Creator Server의 시간이 스토리지 컨트롤러의 시간과 일치하지 않으면 * Ignore Validation * 을 클릭합니다.



 a| 
복제를 사용하지 않도록 설정합니다
 a| 
복구된 데이터베이스 파일에 대한 새 Domino 복제본 ID를 설정하려면 이 상자를 선택합니다.

|===
. 요약을 검토하고 * Finish * 를 클릭합니다.
. 볼륨 복원 대화 상자에서 * 확인 * 을 클릭합니다.
+
Snap Creator가 복원 작업을 시작합니다. 작업 정보가 콘솔 창에 표시됩니다.



복구 작업이 완료되면 Domino 서버를 다시 시작합니다.
