---
permalink: domino-ops/task_setting_the_snap_creator_archive_log_management_settings.html 
sidebar: sidebar 
keywords: domino, ibm, cleaning up, purging, archives, archived, copies, transaction, logs 
summary: Domino 트랜잭션 로깅을 사용하는 경우 IBM Domino 플러그인은 최신 복원 작업에 사용할 수 있도록 Domino 트랜잭션 로그의 복사본을 changeinfo 디렉토리에 아카이빙합니다. Snap Creator가 더 이상 필요하지 않은 트랜잭션 로그 복사본을 정리하기 전에 트랜잭션 로그 관리를 활성화해야 합니다. 
---
= Domino 트랜잭션 로그의 아카이빙된 복제본을 정리하는 중입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Domino 트랜잭션 로깅을 사용하는 경우 IBM Domino 플러그인은 최신 복원 작업에 사용할 수 있도록 Domino 트랜잭션 로그의 복사본을 changeinfo 디렉토리에 아카이빙합니다. Snap Creator가 더 이상 필요하지 않은 트랜잭션 로그 복사본을 정리하기 전에 트랜잭션 로그 관리를 활성화해야 합니다.

Domino 플러그인은 changeinfo 디렉토리에 changeinfo 파일과 Domino 트랜잭션 로그의 아카이브 복사본을 저장합니다. 플러그인은 구성에 대한 보존 정책을 기반으로 .info 파일을 자동으로 정리합니다. Snap Creator에서 트랜잭션 로그 관리를 명시적으로 설정하지 않으면 불필요한 트랜잭션 로그 복사본이 정리되지 않습니다.

트랜잭션 로그 관리를 설정할 때는 최신 복원 작업과 changeinfo 디렉토리가 포함된 볼륨의 크기 간에 보관하려는 트랜잭션 로그의 보관된 복사본 수 간에 적절한 균형을 유지해야 합니다.


IMPORTANT: 아카이브 로그 디렉토리 매개 변수를 Domino 트랜잭션 로그 경로로 설정하지 마십시오. 이렇게 하면 Domino 환경이 손상될 수 있습니다.

. 프로파일 및 구성 창에서 구성 파일을 선택하고 * 아카이브 로그 관리 * 탭을 클릭합니다.
. 아카이브 로그 관리 * 탭에서 트랜잭션 로그 관리 설정에 대해 다음 값을 지정합니다.
+
|===
| 매개 변수 | 설정 | 설명 


 a| 
아카이브 로그 활성화
 a| 
예
 a| 
트랜잭션 로그 정리를 활성화합니다.



 a| 
아카이브 로그 보존
 a| 
스냅샷 복사본이 유지되는 일 수보다 크거나 같은 값을 입력합니다.
 a| 
트랜잭션 로그를 보존할 일 수입니다.



 a| 
보관 로그 디렉터리
 a| 
변경 정보/로그
 a| 
정리할 디렉터리입니다. * 중요: * Domino 트랜잭션 로그의 경로를 지정하지 마십시오. 이렇게 하면 Domino 환경이 손상될 수 있습니다.



 a| 
아카이브 로그 확장
 a| 
 a| 
Domino 트랜잭션 로그 파일 복제본의 확장명입니다.



 a| 
로그 반복 검색 보관
 a| 
해당 없음
 a| 
Snap Creator 플러그인은 changeinfo 디렉터리의 logs 하위 디렉터리에 .txn 파일을 제공하므로 재귀 검색이 필요하지 않습니다.

|===
. 구성 내용 창에서 * 저장 * 을 클릭하여 변경 사항을 저장합니다.

